# Generated by Django 5.0.10 on 2026-03-30 00:45

import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIRecommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("entity_type", models.CharField(max_length=50)),
                ("entity_id", models.UUIDField(db_index=True)),
                ("model_used", models.CharField(max_length=50)),
                ("items", models.JSONField(default=list)),
                ("accepted_items", models.JSONField(default=list)),
                ("rejected_items", models.JSONField(default=list)),
            ],
            options={
                "verbose_name": "Recomendação IA",
                "verbose_name_plural": "Recomendações IA",
                "db_table": "ai_recommendation",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="KnowledgeChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("source_type", models.CharField(max_length=50)),
                ("source_id", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("embedding", pgvector.django.vector.VectorField(dimensions=1536, null=True)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Chunk de Conhecimento",
                "verbose_name_plural": "Chunks de Conhecimento",
                "db_table": "ai_knowledge_chunk",
            },
        ),
    ]
