# Generated by Django 5.0.10 on 2026-04-17 02:08

import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.conf import settings
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("persons", "0004_person_job_title_department_choices"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        CreateExtension("vector"),    # pgvector — vetores semânticos
        CreateExtension("pg_trgm"),   # fuzzy search via GIN trgm
        migrations.CreateModel(
            name="CategoriaMaoObra",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "codigo",
                    models.SlugField(
                        help_text='Slug único, ex: "funileiro-senior", "pintor".',
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                ("nome", models.CharField(max_length=80, verbose_name="Nome")),
                (
                    "ordem",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="Menor valor aparece primeiro.",
                        verbose_name="Ordem de exibição",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria de Mão de Obra",
                "verbose_name_plural": "Categorias de Mão de Obra",
                "ordering": ["ordem", "nome"],
            },
        ),
        migrations.CreateModel(
            name="CategoriaServico",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "codigo",
                    models.SlugField(
                        help_text='Slug único, ex: "funilaria", "pintura".',
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "ordem",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="Menor valor aparece primeiro.",
                        verbose_name="Ordem de exibição",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria de Serviço",
                "verbose_name_plural": "Categorias de Serviço",
                "ordering": ["ordem", "nome"],
            },
        ),
        migrations.CreateModel(
            name="Fornecedor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "condicoes_pagamento",
                    models.CharField(
                        blank=True,
                        help_text='Ex: "30/60/90 dias", "À vista 5% desconto".',
                        max_length=100,
                        verbose_name="Condições de pagamento",
                    ),
                ),
                (
                    "prazo_entrega_dias",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Prazo de entrega (dias)"
                    ),
                ),
                (
                    "avaliacao",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Nota de 1 a 5 estrelas.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Avaliação",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pessoa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil_fornecedor",
                        to="persons.person",
                        verbose_name="Pessoa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fornecedor",
                "verbose_name_plural": "Fornecedores",
                "ordering": ["pessoa__full_name"],
            },
        ),
        migrations.CreateModel(
            name="MaterialCanonico",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "codigo",
                    models.SlugField(
                        help_text='Slug único, ex: "tinta-base-1l", "lixa-400".',
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                ("nome", models.CharField(max_length=150, verbose_name="Nome")),
                (
                    "unidade_base",
                    models.CharField(
                        help_text="Unidade de medida principal: L, kg, m, un, m2.",
                        max_length=20,
                        verbose_name="Unidade base",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("consumivel", "Consumível"), ("ferramenta", "Ferramenta")],
                        default="consumivel",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        dimensions=1024,
                        help_text="Vetor gerado pelo modelo de embeddings para busca por similaridade.",
                        null=True,
                        verbose_name="Embedding semântico",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Material Canônico",
                "verbose_name_plural": "Materiais Canônicos",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="InsumoMaterial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "sku_interno",
                    models.CharField(max_length=60, unique=True, verbose_name="SKU interno"),
                ),
                (
                    "gtin",
                    models.CharField(
                        blank=True, db_index=True, max_length=14, verbose_name="GTIN/EAN"
                    ),
                ),
                ("descricao", models.CharField(max_length=200, verbose_name="Descrição")),
                ("marca", models.CharField(blank=True, max_length=60, verbose_name="Marca")),
                (
                    "unidade_compra",
                    models.CharField(
                        help_text="Ex: galão, caixa, rolo.",
                        max_length=20,
                        verbose_name="Unidade de compra",
                    ),
                ),
                (
                    "fator_conversao",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Quantas unidades_base vêm em uma unidade_compra. Ex: galão 3.6L → 3.6 se unidade_base=L.",
                        max_digits=10,
                        verbose_name="Fator de conversão",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "material_canonico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="insumos",
                        to="pricing_catalog.materialcanonico",
                        verbose_name="Material canônico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Insumo / Material",
                "verbose_name_plural": "Insumos / Materiais",
                "ordering": ["material_canonico", "descricao"],
            },
        ),
        migrations.CreateModel(
            name="PecaCanonica",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "codigo",
                    models.SlugField(
                        help_text='Slug único, ex: "para-choque-dianteiro-corolla-2020".',
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="Nome")),
                (
                    "tipo_peca",
                    models.CharField(
                        choices=[
                            ("genuina", "Genuína"),
                            ("original", "Original"),
                            ("paralela", "Paralela"),
                            ("usada", "Usada"),
                            ("recondicionada", "Recondicionada"),
                        ],
                        default="paralela",
                        max_length=20,
                        verbose_name="Tipo de peça",
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        dimensions=1024,
                        help_text="Vetor gerado pelo modelo de embeddings para busca por similaridade.",
                        null=True,
                        verbose_name="Embedding semântico",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Peça Canônica",
                "verbose_name_plural": "Peças Canônicas",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="ServicoCanonico",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "codigo",
                    models.SlugField(
                        help_text='Slug único, ex: "pintura-para-choque".',
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="Nome")),
                (
                    "unidade",
                    models.CharField(
                        default="un",
                        help_text='Unidade de cobrança: "un", "h", "m2", etc.',
                        max_length=20,
                        verbose_name="Unidade",
                    ),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "aplica_multiplicador_tamanho",
                    models.BooleanField(
                        default=False,
                        help_text="TRUE para serviços que dependem do tamanho do veículo (pintura, funilaria, polimento). FALSE para serviços independentes de tamanho (elétrica, alinhamento, diagnóstico).",
                        verbose_name="Aplica multiplicador de tamanho",
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        dimensions=1024,
                        help_text="Vetor gerado pelo modelo de embeddings para busca por similaridade.",
                        null=True,
                        verbose_name="Embedding semântico",
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="servicos",
                        to="pricing_catalog.categoriaservico",
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Serviço Canônico",
                "verbose_name_plural": "Serviços Canônicos",
                "ordering": ["categoria", "nome"],
            },
        ),
        migrations.CreateModel(
            name="AliasMaterial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("texto", models.CharField(max_length=300, verbose_name="Texto original")),
                (
                    "texto_normalizado",
                    models.CharField(
                        db_index=True, max_length=300, verbose_name="Texto normalizado"
                    ),
                ),
                (
                    "origem",
                    models.CharField(
                        choices=[
                            ("import", "Importação"),
                            ("manual", "Cadastro manual"),
                            ("auto_alta", "Auto — confiança alta"),
                            ("auto_media", "Auto — confiança média (revisar)"),
                        ],
                        max_length=20,
                        verbose_name="Origem",
                    ),
                ),
                ("confianca", models.FloatField(blank=True, null=True, verbose_name="Confiança")),
                (
                    "confirmado_em",
                    models.DateTimeField(blank=True, null=True, verbose_name="Confirmado em"),
                ),
                ("ocorrencias", models.PositiveIntegerField(default=1, verbose_name="Ocorrências")),
                (
                    "confirmado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aliases_material_confirmados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Confirmado por",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "canonico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="pricing_catalog.materialcanonico",
                        verbose_name="Material canônico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alias de Material",
                "verbose_name_plural": "Aliases de Material",
                "ordering": ["-ocorrencias", "texto_normalizado"],
                "indexes": [
                    models.Index(
                        fields=["texto_normalizado"], name="pricing_cat_texto_n_3eb13e_idx"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["texto_normalizado"],
                        name="alias_material_trgm_idx",
                        opclasses=["gin_trgm_ops"],
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CompatibilidadePeca",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("marca", models.CharField(max_length=60, verbose_name="Marca")),
                (
                    "modelo",
                    models.CharField(
                        blank=True,
                        help_text="Deixar em branco para compatibilidade com toda a marca.",
                        max_length=100,
                        verbose_name="Modelo",
                    ),
                ),
                ("ano_inicio", models.IntegerField(verbose_name="Ano início")),
                ("ano_fim", models.IntegerField(verbose_name="Ano fim")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "peca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compatibilidades",
                        to="pricing_catalog.pecacanonica",
                        verbose_name="Peça",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compatibilidade de Peça",
                "verbose_name_plural": "Compatibilidades de Peças",
                "ordering": ["peca", "marca", "modelo"],
                "indexes": [
                    models.Index(
                        fields=["marca", "modelo", "ano_inicio", "ano_fim"],
                        name="pricing_cat_marca_782033_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CodigoFornecedorPeca",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "sku_fornecedor",
                    models.CharField(max_length=60, verbose_name="SKU do fornecedor"),
                ),
                (
                    "preco_referencia",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Preço de referência (R$)",
                    ),
                ),
                (
                    "data_referencia",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data do preço de referência"
                    ),
                ),
                (
                    "prioridade",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="Menor valor = fornecedor preferido para esta peça.",
                        verbose_name="Prioridade",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codigos_peca",
                        to="pricing_catalog.fornecedor",
                        verbose_name="Fornecedor",
                    ),
                ),
                (
                    "peca_canonica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codigos_fornecedor",
                        to="pricing_catalog.pecacanonica",
                        verbose_name="Peça canônica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Código Fornecedor / Peça",
                "verbose_name_plural": "Códigos Fornecedor / Peça",
                "ordering": ["peca_canonica", "prioridade"],
                "unique_together": {("peca_canonica", "fornecedor", "sku_fornecedor")},
            },
        ),
        migrations.CreateModel(
            name="AliasPeca",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("texto", models.CharField(max_length=300, verbose_name="Texto original")),
                (
                    "texto_normalizado",
                    models.CharField(
                        db_index=True, max_length=300, verbose_name="Texto normalizado"
                    ),
                ),
                (
                    "origem",
                    models.CharField(
                        choices=[
                            ("import", "Importação"),
                            ("manual", "Cadastro manual"),
                            ("auto_alta", "Auto — confiança alta"),
                            ("auto_media", "Auto — confiança média (revisar)"),
                        ],
                        max_length=20,
                        verbose_name="Origem",
                    ),
                ),
                ("confianca", models.FloatField(blank=True, null=True, verbose_name="Confiança")),
                (
                    "confirmado_em",
                    models.DateTimeField(blank=True, null=True, verbose_name="Confirmado em"),
                ),
                ("ocorrencias", models.PositiveIntegerField(default=1, verbose_name="Ocorrências")),
                (
                    "confirmado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aliases_peca_confirmados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Confirmado por",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "canonico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="pricing_catalog.pecacanonica",
                        verbose_name="Peça canônica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alias de Peça",
                "verbose_name_plural": "Aliases de Peça",
                "ordering": ["-ocorrencias", "texto_normalizado"],
                "indexes": [
                    models.Index(
                        fields=["texto_normalizado"], name="pricing_cat_texto_n_14b67f_idx"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["texto_normalizado"],
                        name="alias_peca_trgm_idx",
                        opclasses=["gin_trgm_ops"],
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AliasServico",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("texto", models.CharField(max_length=300, verbose_name="Texto original")),
                (
                    "texto_normalizado",
                    models.CharField(
                        db_index=True,
                        help_text="Lowercase sem acentos — usado para busca fuzzy.",
                        max_length=300,
                        verbose_name="Texto normalizado",
                    ),
                ),
                (
                    "origem",
                    models.CharField(
                        choices=[
                            ("import", "Importação"),
                            ("manual", "Cadastro manual"),
                            ("auto_alta", "Auto — confiança alta"),
                            ("auto_media", "Auto — confiança média (revisar)"),
                        ],
                        max_length=20,
                        verbose_name="Origem",
                    ),
                ),
                (
                    "confianca",
                    models.FloatField(
                        blank=True,
                        help_text="Score de confiança do mapeamento automático (0.0–1.0).",
                        null=True,
                        verbose_name="Confiança",
                    ),
                ),
                (
                    "confirmado_em",
                    models.DateTimeField(blank=True, null=True, verbose_name="Confirmado em"),
                ),
                (
                    "ocorrencias",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Quantas vezes este texto apareceu nas OS.",
                        verbose_name="Ocorrências",
                    ),
                ),
                (
                    "confirmado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aliases_servico_confirmados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Confirmado por",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "canonico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="pricing_catalog.servicocanonico",
                        verbose_name="Serviço canônico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alias de Serviço",
                "verbose_name_plural": "Aliases de Serviço",
                "ordering": ["-ocorrencias", "texto_normalizado"],
                "indexes": [
                    models.Index(
                        fields=["texto_normalizado"], name="pricing_cat_texto_n_5895ae_idx"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["texto_normalizado"],
                        name="alias_servico_trgm_idx",
                        opclasses=["gin_trgm_ops"],
                    ),
                ],
            },
        ),
    ]
