# Generated by Django 5.0.10 on 2026-04-24 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing_catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pecacanonica",
            name="ncm",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Código NCM/SH (8 dígitos). Ex: 87089990. Obrigatório para emissão de NF-e.",
                max_length=10,
                verbose_name="NCM",
            ),
        ),
    ]
