# Generated by Django 5.0.10 on 2026-03-30 00:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                ("number", models.PositiveIntegerField(auto_created=True, db_index=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("customer_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("customer_name", models.CharField(blank=True, default="", max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("completed", "Concluída"),
                            ("cancelled", "Cancelada"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash", "Dinheiro"),
                            ("credit", "Cartão de Crédito"),
                            ("debit", "Cartão de Débito"),
                            ("pix", "PIX"),
                            ("transfer", "Transferência"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("discount_total", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("total", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("nfce_key", models.CharField(blank=True, default="", max_length=44)),
                ("nfce_xml_s3_key", models.CharField(blank=True, default="", max_length=500)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Venda",
                "verbose_name_plural": "Vendas",
                "db_table": "store_sale",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("product_id", models.UUIDField()),
                ("sku", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=300)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=10)),
                ("unit_price", models.DecimalField(decimal_places=4, max_digits=12)),
                ("discount_pct", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                (
                    "discount_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("group_loyalty", "Fidelidade grupo"),
                            ("promotion", "Promoção"),
                            ("manual", "Manual"),
                        ],
                        default="",
                        max_length=30,
                    ),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="store.sale",
                    ),
                ),
            ],
            options={
                "db_table": "store_cart_item",
            },
        ),
    ]
