# Generated by Django 5.0.10 on 2026-03-30 00:45

import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UnifiedCustomer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                (
                    "cpf",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, null=True, verbose_name="CPF"
                    ),
                ),
                (
                    "cpf_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=64,
                        verbose_name="Hash CPF",
                    ),
                ),
                (
                    "email",
                    encrypted_model_fields.fields.EncryptedEmailField(
                        blank=True, null=True, verbose_name="E-mail"
                    ),
                ),
                (
                    "email_hash",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                (
                    "phone",
                    encrypted_model_fields.fields.EncryptedCharField(verbose_name="Telefone"),
                ),
                (
                    "phone_hash",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                ("lgpd_consent_version", models.CharField(default="1.0", max_length=10)),
                ("lgpd_consent_date", models.DateTimeField(blank=True, null=True)),
                ("lgpd_consent_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "group_sharing_consent",
                    models.BooleanField(
                        default=False,
                        help_text="Opt-in EXPLÍCITO — verificar antes de qualquer cross-sell",
                        verbose_name="Consentimento de compartilhamento no grupo",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente Unificado",
                "verbose_name_plural": "Clientes Unificados",
                "db_table": "customers_unified",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
