# Generated by Django 5.0.10 on 2026-04-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_unifiedcustomer_birth_date_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unifiedcustomer',
            name='address',
        ),
        migrations.AddField(
            model_name='unifiedcustomer',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='unifiedcustomer',
            name='complement',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='unifiedcustomer',
            name='neighborhood',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='unifiedcustomer',
            name='state',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='unifiedcustomer',
            name='street',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Rua / Av.'),
        ),
        migrations.AddField(
            model_name='unifiedcustomer',
            name='street_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='unifiedcustomer',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=9, verbose_name='CEP'),
        ),
    ]
