# Generated by Django 5.0.10 on 2026-05-09 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_address_split"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unifiedcustomer",
            name="cpf_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=64,
                null=True,
                unique=True,
                verbose_name="Hash CPF",
            ),
        ),
    ]
