[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -ra --tb=short --strict-markers
testpaths = apps
markers =
    slow: testes lentos que podem ser pulados com -m "not slow"
    integration: testes de integração com banco real
