# Generated by Django 5.0.10 on 2026-05-04 14:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pricing_catalog", "0002_pecacanonica_ncm"),
        ("service_orders", "0026_parts_wms_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrdemCompra",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "numero",
                    models.CharField(
                        help_text="Auto-gerado: OC-{year}-{seq:04d}", max_length=20, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("pendente_aprovacao", "Pendente de Aprovação"),
                            ("aprovada", "Aprovada"),
                            ("rejeitada", "Rejeitada"),
                            ("parcial_recebida", "Parcialmente Recebida"),
                            ("concluida", "Concluída"),
                        ],
                        default="rascunho",
                        max_length=20,
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Soma dos itens — recomputado no save().",
                        max_digits=14,
                    ),
                ),
                ("observacoes", models.TextField(blank=True, default="")),
                ("aprovado_em", models.DateTimeField(blank=True, null=True)),
                ("motivo_rejeicao", models.TextField(blank=True, default="")),
                (
                    "aprovado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ordens_compra_aprovadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordens_compra_criadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rejeitado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ordens_compra_rejeitadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordens_compra",
                        to="service_orders.serviceorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ordem de Compra",
                "verbose_name_plural": "Ordens de Compra",
                "db_table": "purchasing_ordem_compra",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PedidoCompra",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("descricao", models.CharField(max_length=300)),
                ("codigo_referencia", models.CharField(blank=True, default="", max_length=100)),
                (
                    "tipo_qualidade",
                    models.CharField(
                        choices=[
                            ("genuina", "Genuína"),
                            ("reposicao", "Reposição Original"),
                            ("similar", "Similar/Paralela"),
                            ("usada", "Usada/Recondicionada"),
                        ],
                        max_length=15,
                    ),
                ),
                ("quantidade", models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                (
                    "valor_cobrado_cliente",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor que será cobrado na OS (preço do orçamento — PC-9).",
                        max_digits=12,
                    ),
                ),
                ("observacoes", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("solicitado", "Solicitado"),
                            ("em_cotacao", "Em Cotação"),
                            ("oc_pendente", "OC Pendente"),
                            ("aprovado", "Aprovado"),
                            ("comprado", "Comprado"),
                            ("recebido", "Recebido"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="solicitado",
                        max_length=15,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pedidos_compra",
                        to="service_orders.serviceorder",
                    ),
                ),
                (
                    "service_order_part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pedidos_compra",
                        to="service_orders.serviceorderpart",
                    ),
                ),
                (
                    "solicitado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pedidos_compra_solicitados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido de Compra",
                "verbose_name_plural": "Pedidos de Compra",
                "db_table": "purchasing_pedido_compra",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ItemOrdemCompra",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("fornecedor_nome", models.CharField(max_length=150)),
                ("fornecedor_cnpj", models.CharField(blank=True, default="", max_length=20)),
                ("fornecedor_contato", models.CharField(blank=True, default="", max_length=100)),
                ("descricao", models.CharField(max_length=300)),
                ("codigo_referencia", models.CharField(blank=True, default="", max_length=100)),
                (
                    "tipo_qualidade",
                    models.CharField(
                        choices=[
                            ("genuina", "Genuína"),
                            ("reposicao", "Reposição Original"),
                            ("similar", "Similar/Paralela"),
                            ("usada", "Usada/Recondicionada"),
                        ],
                        max_length=15,
                    ),
                ),
                ("quantidade", models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ("valor_unitario", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="qty × unit — computed no save().",
                        max_digits=14,
                    ),
                ),
                ("prazo_entrega", models.CharField(blank=True, default="", max_length=100)),
                ("observacoes", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="itens_oc",
                        to="pricing_catalog.fornecedor",
                    ),
                ),
                (
                    "ordem_compra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="purchasing.ordemcompra",
                    ),
                ),
                (
                    "pedido_compra",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="itens_oc",
                        to="purchasing.pedidocompra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Ordem de Compra",
                "verbose_name_plural": "Itens de Ordem de Compra",
                "db_table": "purchasing_item_ordem_compra",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="ordemcompra",
            index=models.Index(fields=["service_order"], name="purchasing__service_b3ca24_idx"),
        ),
        migrations.AddIndex(
            model_name="ordemcompra",
            index=models.Index(fields=["status"], name="purchasing__status_d376a4_idx"),
        ),
        migrations.AddIndex(
            model_name="ordemcompra",
            index=models.Index(fields=["numero"], name="purchasing__numero_36c41d_idx"),
        ),
        migrations.AddIndex(
            model_name="pedidocompra",
            index=models.Index(fields=["service_order"], name="purchasing__service_9c9025_idx"),
        ),
        migrations.AddIndex(
            model_name="pedidocompra",
            index=models.Index(
                fields=["status", "created_at"], name="purchasing__status_fa34af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="itemordemcompra",
            index=models.Index(fields=["ordem_compra"], name="purchasing__ordem_c_d91cc2_idx"),
        ),
        migrations.AddIndex(
            model_name="itemordemcompra",
            index=models.Index(fields=["fornecedor"], name="purchasing__fornece_ab8c3b_idx"),
        ),
    ]
