# Generated by Django 5.0.10 on 2026-05-13 20:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_payable", "0006_suppliercontact"),
        ("purchasing", "0001_initial"),
        ("service_orders", "0030_alter_serviceorder_authorization_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CotacaoLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("mensagem", models.TextField(help_text="Texto da mensagem enviada")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enviado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cotacoes_enviadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pedidos_incluidos",
                    models.ManyToManyField(
                        blank=True, related_name="cotacao_logs", to="purchasing.pedidocompra"
                    ),
                ),
                (
                    "service_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cotacoes_enviadas",
                        to="service_orders.serviceorder",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cotacoes_recebidas",
                        to="accounts_payable.supplier",
                    ),
                ),
                (
                    "supplier_contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cotacoes",
                        to="accounts_payable.suppliercontact",
                    ),
                ),
            ],
            options={
                "db_table": "purchasing_cotacao_log",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RespostaCotacao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("valor_unitario", models.DecimalField(decimal_places=2, max_digits=12)),
                ("prazo_entrega", models.CharField(blank=True, default="", max_length=100)),
                ("condicoes_pagamento", models.CharField(blank=True, default="", max_length=200)),
                ("observacoes", models.TextField(blank=True, default="")),
                ("selecionada", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pedido_compra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respostas_cotacao",
                        to="purchasing.pedidocompra",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="respostas_cotacao_registradas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respostas_cotacao",
                        to="accounts_payable.supplier",
                    ),
                ),
            ],
            options={
                "db_table": "purchasing_resposta_cotacao",
                "ordering": ["valor_unitario"],
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="respostacotacao",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("pedido_compra", "supplier"),
                name="unique_resposta_por_fornecedor",
            ),
        ),
    ]
