# Generated by Django 5.0.10 on 2026-05-14 18:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0002_cotacaolog_respostacotacao_and_more"),
        ("service_orders", "0030_alter_serviceorder_authorization_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AprovacaoCotacao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("aprovada", "Aprovada"),
                            ("rejeitada", "Rejeitada"),
                        ],
                        default="pendente",
                        max_length=15,
                    ),
                ),
                ("aprovado_em", models.DateTimeField(blank=True, null=True)),
                ("observacoes_comprador", models.TextField(blank=True, default="")),
                ("observacoes_financeiro", models.TextField(blank=True, default="")),
                ("motivo_rejeicao", models.TextField(blank=True, default="")),
                (
                    "aprovado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aprovacoes_aprovadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enviado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aprovacoes_enviadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aprovacoes_cotacao",
                        to="service_orders.serviceorder",
                    ),
                ),
            ],
            options={
                "db_table": "purchasing_aprovacao_cotacao",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
