# Generated by Django 5.0.10 on 2026-05-14 19:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0010_nfeentrada_auto_import_fields"),
        ("purchasing", "0003_aprovacaocotacao"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="itemordemcompra",
            name="data_prevista",
            field=models.DateField(
                blank=True,
                help_text="Data prevista de entrega (calculada: aprovação + prazo).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="itemordemcompra",
            name="data_recebimento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="itemordemcompra",
            name="destino",
            field=models.CharField(
                blank=True,
                choices=[("os_direta", "Direto para OS"), ("estoque_geral", "Estoque Geral")],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="itemordemcompra",
            name="nfe_entrada",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="itens_oc",
                to="fiscal.nfeentrada",
            ),
        ),
        migrations.AddField(
            model_name="itemordemcompra",
            name="status_entrega",
            field=models.CharField(
                choices=[
                    ("aguardando", "Aguardando"),
                    ("em_transito", "Em Trânsito"),
                    ("recebido", "Recebido"),
                    ("atrasado", "Atrasado"),
                ],
                default="aguardando",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CondicaoPagamento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("label", models.CharField(max_length=80, unique=True)),
                (
                    "is_default",
                    models.BooleanField(default=False, help_text="Pré-cadastrado no seed."),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "purchasing_condicao_pagamento",
                "ordering": ["label"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="respostacotacao",
            name="condicao_pagamento_obj",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="respostas",
                to="purchasing.condicaopagamento",
            ),
        ),
        migrations.CreateModel(
            name="PrazoEntrega",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("label", models.CharField(max_length=50, unique=True)),
                (
                    "dias_uteis",
                    models.PositiveIntegerField(
                        help_text="Quantidade de dias úteis para cálculo de data prevista."
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, help_text="Pré-cadastrado no seed."),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "purchasing_prazo_entrega",
                "ordering": ["dias_uteis"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="respostacotacao",
            name="prazo_entrega_obj",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="respostas",
                to="purchasing.prazoentrega",
            ),
        ),
    ]
