# Generated by Django 5.0 — Sprint 14

import decimal
import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("name", models.CharField(db_index=True, max_length=200, verbose_name="Nome")),
                (
                    "cnpj",
                    models.CharField(blank=True, default="", max_length=14, verbose_name="CNPJ"),
                ),
                (
                    "cpf",
                    models.CharField(blank=True, default="", max_length=11, verbose_name="CPF"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, default="", verbose_name="E-mail"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="Telefone"
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Contato"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Observacoes"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Fornecedor",
                "verbose_name_plural": "Fornecedores",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PayableDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "description",
                    models.CharField(max_length=300, verbose_name="Descricao"),
                ),
                (
                    "document_number",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="No Documento"
                    ),
                ),
                (
                    "document_date",
                    models.DateField(blank=True, null=True, verbose_name="Data do documento"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=18, verbose_name="Valor"
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=decimal.Decimal("0.00"),
                        max_digits=18,
                        verbose_name="Valor pago",
                    ),
                ),
                ("due_date", models.DateField(db_index=True, verbose_name="Vencimento")),
                ("competence_date", models.DateField(verbose_name="Competencia")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Em Aberto"),
                            ("partial", "Parcialmente Pago"),
                            ("paid", "Pago"),
                            ("overdue", "Vencido"),
                            ("cancelled", "Cancelado"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("MAN", "Manual"),
                            ("FOLHA", "Folha de Pagamento"),
                            ("NFE_E", "NF-e de Entrada"),
                            ("AUTO", "Automatico"),
                        ],
                        default="MAN",
                        max_length=10,
                        verbose_name="Origem",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Observacoes"),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Cancelado em"),
                ),
                (
                    "cancel_reason",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Motivo do cancelamento",
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_payables",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cancelado por",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payables",
                        to="accounting.costcenter",
                        verbose_name="Centro de Custo",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payables",
                        to="accounts_payable.supplier",
                        verbose_name="Fornecedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Titulo a Pagar",
                "verbose_name_plural": "Titulos a Pagar",
                "ordering": ["due_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PayablePayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "payment_date",
                    models.DateField(verbose_name="Data do pagamento"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=18, verbose_name="Valor pago"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("bank_transfer", "Transferencia Bancaria"),
                            ("pix", "PIX"),
                            ("boleto", "Boleto"),
                            ("check", "Cheque"),
                            ("cash", "Dinheiro"),
                            ("credit_card", "Cartao de Credito"),
                            ("debit_card", "Cartao de Debito"),
                        ],
                        default="bank_transfer",
                        max_length=20,
                        verbose_name="Forma de pagamento",
                    ),
                ),
                (
                    "bank_account",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Conta bancaria"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Observacoes"),
                ),
                (
                    "journal_entry_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="Lancamento contabil"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="accounts_payable.payabledocument",
                        verbose_name="Titulo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pagamento",
                "verbose_name_plural": "Pagamentos",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.AddIndex(
            model_name="payabledocument",
            index=models.Index(
                fields=["status", "due_date"],
                name="accounts_pa_status_61c987_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payabledocument",
            index=models.Index(
                fields=["supplier", "status"],
                name="accounts_pa_supplie_9f4bf5_idx",
            ),
        ),
    ]
