# Generated by Django 5.0.10 on 2026-04-09 16:38

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NumberSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        help_text="Prefixo da sequência: JE, AP, AR, etc.",
                        max_length=20,
                        unique=True,
                        verbose_name="Chave",
                    ),
                ),
                (
                    "last_number",
                    models.PositiveIntegerField(default=0, verbose_name="Último número"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
            ],
            options={
                "verbose_name": "Sequência de Numeração",
                "verbose_name_plural": "Sequências de Numeração",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="ChartOfAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=30, unique=True, verbose_name="Código"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("A", "Ativo"),
                            ("L", "Passivo"),
                            ("E", "Patrimonio Liquido"),
                            ("R", "Receita"),
                            ("C", "Custo"),
                            ("X", "Despesa"),
                            ("O", "Outras"),
                        ],
                        max_length=1,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "nature",
                    models.CharField(
                        choices=[("D", "Devedora"), ("C", "Credora")],
                        max_length=1,
                        verbose_name="Natureza",
                    ),
                ),
                (
                    "is_analytical",
                    models.BooleanField(
                        default=False,
                        help_text="Contas analíticas aceitam lançamentos diretos.",
                        verbose_name="Analítica",
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        help_text="Nível na hierarquia (1 a 5).", verbose_name="Nível"
                    ),
                ),
                (
                    "sped_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Código referencial SPED ECD para exportação fiscal.",
                        max_length=30,
                        verbose_name="Código SPED ECD",
                    ),
                ),
                (
                    "accepts_cost_center",
                    models.BooleanField(default=False, verbose_name="Aceita centro de custo"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="accounting.chartofaccount",
                        verbose_name="Conta pai",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conta Contábil",
                "verbose_name_plural": "Plano de Contas",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="CostCenter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=20, unique=True, verbose_name="Código"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                (
                    "os_type_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Mapeamento para ServiceOrder.os_type.",
                        max_length=20,
                        verbose_name="Código tipo OS",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="accounting.costcenter",
                        verbose_name="CC pai",
                    ),
                ),
            ],
            options={
                "verbose_name": "Centro de Custo",
                "verbose_name_plural": "Centros de Custo",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="FiscalYear",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        db_index=True, unique=True, verbose_name="Ano"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Data início")),
                ("end_date", models.DateField(verbose_name="Data fim")),
                (
                    "is_closed",
                    models.BooleanField(db_index=True, default=False, verbose_name="Encerrado"),
                ),
                (
                    "closed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Encerrado em"),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="closed_fiscal_years",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Encerrado por",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Exercício Fiscal",
                "verbose_name_plural": "Exercícios Fiscais",
                "ordering": ["-year"],
            },
        ),
        migrations.CreateModel(
            name="FiscalPeriod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        help_text="1-12 (mensal) ou 13 (ajuste anual).", verbose_name="Número"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Data início")),
                ("end_date", models.DateField(verbose_name="Data fim")),
                (
                    "is_closed",
                    models.BooleanField(db_index=True, default=False, verbose_name="Fechado"),
                ),
                (
                    "is_adjustment",
                    models.BooleanField(
                        default=False,
                        help_text="13° período anual de ajuste.",
                        verbose_name="Período de ajuste",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fiscal_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="periods",
                        to="accounting.fiscalyear",
                        verbose_name="Exercício",
                    ),
                ),
            ],
            options={
                "verbose_name": "Período Fiscal",
                "verbose_name_plural": "Períodos Fiscais",
                "ordering": ["fiscal_year", "number"],
            },
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "number",
                    models.CharField(
                        db_index=True, max_length=20, unique=True, verbose_name="Número"
                    ),
                ),
                ("description", models.CharField(max_length=500, verbose_name="Descrição")),
                (
                    "competence_date",
                    models.DateField(db_index=True, verbose_name="Data de competência"),
                ),
                (
                    "document_date",
                    models.DateField(blank=True, null=True, verbose_name="Data do documento"),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("MAN", "Manual"),
                            ("OS", "Ordem de Serviço"),
                            ("NFE", "NF-e Emitida"),
                            ("NFCE", "NFC-e Emitida"),
                            ("NFSE", "NFS-e Emitida"),
                            ("NFE_E", "NF-e Entrada (Compra)"),
                            ("PAG", "Pagamento Bancário"),
                            ("REC", "Recebimento Bancário"),
                            ("ASAAS", "Asaas (Cobrança)"),
                            ("OFX", "Importação OFX"),
                            ("FOLHA", "Folha de Pagamento"),
                            ("DEP", "Depreciação"),
                            ("ENC", "Encerramento de Período"),
                            ("EST", "Ajuste de Estoque"),
                        ],
                        db_index=True,
                        max_length=10,
                        verbose_name="Origem",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ID do objeto de origem"
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(db_index=True, default=False, verbose_name="Aprovado"),
                ),
                ("is_reversed", models.BooleanField(default=False, verbose_name="Estornado")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_journal_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprovado por",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                        verbose_name="Tipo do objeto de origem",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fiscal_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_entries",
                        to="accounting.fiscalperiod",
                        verbose_name="Período fiscal",
                    ),
                ),
                (
                    "reversal_entry",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reversed_by",
                        to="accounting.journalentry",
                        verbose_name="Lançamento de estorno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lançamento Contábil",
                "verbose_name_plural": "Lançamentos Contábeis",
                "ordering": ["-competence_date", "-number"],
            },
        ),
        migrations.CreateModel(
            name="JournalEntryLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "debit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=18,
                        verbose_name="Débito",
                    ),
                ),
                (
                    "credit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=18,
                        verbose_name="Crédito",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=300, verbose_name="Descrição"
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Número do documento"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        limit_choices_to={"is_analytical": True},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_lines",
                        to="accounting.chartofaccount",
                        verbose_name="Conta",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journal_lines",
                        to="accounting.costcenter",
                        verbose_name="Centro de custo",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="accounting.journalentry",
                        verbose_name="Lançamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Linha de Lançamento",
                "verbose_name_plural": "Linhas de Lançamento",
            },
        ),
        migrations.AddIndex(
            model_name="chartofaccount",
            index=models.Index(fields=["code"], name="accounting__code_569b11_idx"),
        ),
        migrations.AddIndex(
            model_name="chartofaccount",
            index=models.Index(
                fields=["account_type", "is_analytical"], name="accounting__account_e2c456_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chartofaccount",
            index=models.Index(fields=["parent"], name="accounting__parent__3124f8_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="fiscalperiod",
            unique_together={("fiscal_year", "number")},
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(fields=["competence_date"], name="accounting__compete_f30045_idx"),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(fields=["origin"], name="accounting__origin_ae67d2_idx"),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(fields=["fiscal_period"], name="accounting__fiscal__7eaa99_idx"),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["content_type", "object_id"], name="accounting__content_2d5599_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["is_approved", "competence_date"], name="accounting__is_appr_f30ceb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentryline",
            index=models.Index(fields=["account", "entry"], name="accounting__account_d08382_idx"),
        ),
        migrations.AddIndex(
            model_name="journalentryline",
            index=models.Index(fields=["cost_center"], name="accounting__cost_ce_b02035_idx"),
        ),
    ]
