# Generated by Django 5.0.10 on 2026-04-17 19:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0001_initial"),
        ("pricing_profile", "0002_enquadramento_faltante"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DespesaRecorrente",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("aluguel", "Aluguel"),
                            ("energia", "Energia elétrica"),
                            ("agua", "Água"),
                            ("internet", "Internet / Telefonia"),
                            ("software", "Softwares / Licenças"),
                            ("folha_admin", "Folha administrativa"),
                            ("contabilidade", "Contabilidade"),
                            ("marketing", "Marketing"),
                            ("depreciacao", "Depreciação de equipamentos"),
                            ("seguro", "Seguros"),
                            ("limpeza", "Limpeza / Insumos administrativos"),
                            ("outros", "Outros"),
                        ],
                        max_length=40,
                        verbose_name="Tipo",
                    ),
                ),
                ("descricao", models.CharField(max_length=200, verbose_name="Descrição")),
                (
                    "valor_mensal",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor mensal"
                    ),
                ),
                ("vigente_desde", models.DateField(verbose_name="Vigente desde")),
                (
                    "vigente_ate",
                    models.DateField(
                        blank=True,
                        help_text="Null indica que a despesa está vigente até nova versão.",
                        null=True,
                        verbose_name="Vigente até",
                    ),
                ),
                ("observacoes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "conta_contabil",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="despesas_recorrentes",
                        to="accounting.chartofaccount",
                        verbose_name="Conta contábil",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="despesas_recorrentes",
                        to="pricing_profile.empresa",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Despesa Recorrente",
                "verbose_name_plural": "Despesas Recorrentes",
                "ordering": ["-vigente_desde"],
                "indexes": [
                    models.Index(
                        fields=["empresa", "vigente_desde", "vigente_ate"],
                        name="acc_despesa_emp_vig_idx",
                    )
                ],
            },
        ),
    ]
