# Generated by Django 5.0.10 on 2026-05-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_despesa_recorrente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalentry",
            name="object_id",
            field=models.CharField(
                blank=True, max_length=36, null=True, verbose_name="ID do objeto de origem"
            ),
        ),
    ]
