# Generated by Django 5.0.10 on 2026-04-03 02:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrcamentoCilia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("budget_id", models.BigIntegerField()),
                ("budget_version_id", models.BigIntegerField(unique=True)),
                (
                    "casualty_number",
                    models.CharField(max_length=50, verbose_name="Número do sinistro"),
                ),
                ("budget_number", models.IntegerField(verbose_name="Número do Orçamento")),
                (
                    "version_number",
                    models.IntegerField(default=1, verbose_name="Versão do Orçamento"),
                ),
                ("status", models.CharField(max_length=50)),
                ("license_plate", models.CharField(max_length=10)),
                ("vehicle_model", models.CharField(max_length=200)),
                ("vehicle_brand", models.CharField(max_length=100)),
                ("vehicle_year", models.IntegerField(null=True)),
                ("vehicle_chassi", models.CharField(blank=True, max_length=50)),
                ("vehicle_color", models.CharField(blank=True, max_length=50)),
                ("client_name", models.CharField(max_length=200)),
                ("client_document", models.CharField(blank=True, max_length=20)),
                ("client_phone", models.CharField(blank=True, max_length=30)),
                ("insurer_name", models.CharField(max_length=200)),
                ("insurer_cnpj", models.CharField(blank=True, max_length=20)),
                ("conclusion_key", models.CharField(blank=True, max_length=50)),
                ("conclusion_title", models.CharField(blank=True, max_length=200)),
                ("conclusion_at", models.DateTimeField(null=True)),
                ("total_liquid", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("total_pieces", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                (
                    "total_workforce",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("total_hours", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ("franchise", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("budget_created_at", models.DateTimeField(null=True)),
                ("version_created_at", models.DateTimeField(null=True)),
                ("raw_data", models.JSONField(default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Orçamento Cilia",
                "verbose_name_plural": "Orçamentos Cilia",
                "ordering": ["-version_created_at"],
                "indexes": [
                    models.Index(
                        fields=["casualty_number", "budget_number"],
                        name="cilia_orcam_casualt_d30833_idx",
                    )
                ],
            },
        ),
    ]
