# Generated by Django 5.0.10 on 2026-07-23 02:03

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cilia", "0003_add_xml_soma_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orcamentocilia",
            name="client_document",
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name="orcamentocilia",
            name="client_phone",
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
    ]
