# Generated by Django 5.0.10 on 2026-03-30 00:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("customer_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("phone", models.CharField(max_length=20)),
                (
                    "direction",
                    models.CharField(
                        choices=[("outbound", "Enviada"), ("inbound", "Recebida")], max_length=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("sent", "Enviada"),
                            ("failed", "Falhou"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("template_name", models.CharField(blank=True, default="", max_length=100)),
                ("message", models.TextField()),
                ("reference_id", models.UUIDField(blank=True, null=True)),
                ("reference_type", models.CharField(blank=True, default="", max_length=50)),
                ("error_message", models.TextField(blank=True, default="")),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensagem WhatsApp",
                "verbose_name_plural": "Mensagens WhatsApp",
                "db_table": "crm_whatsapp_message",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
