# Generated by Django 5.0.10 on 2026-03-30 00:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FiscalDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("nfe", "NF-e (produto B2B)"),
                            ("nfce", "NFC-e (consumidor)"),
                            ("nfse", "NFS-e (serviço)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("authorized", "Autorizada"),
                            ("cancelled", "Cancelada"),
                            ("rejected", "Rejeitada"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("reference_id", models.UUIDField(db_index=True)),
                ("reference_type", models.CharField(max_length=50)),
                ("key", models.CharField(blank=True, db_index=True, default="", max_length=44)),
                ("number", models.CharField(blank=True, default="", max_length=20)),
                ("series", models.CharField(blank=True, default="", max_length=5)),
                ("xml_s3_key", models.CharField(blank=True, default="", max_length=500)),
                ("total_value", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                (
                    "environment",
                    models.CharField(
                        choices=[("homologation", "Homologação"), ("production", "Produção")],
                        max_length=15,
                    ),
                ),
                ("authorized_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento Fiscal",
                "verbose_name_plural": "Documentos Fiscais",
                "db_table": "fiscal_document",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
