# Generated by Django 5.0.10 on 2026-04-18 19:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0001_initial"),
        ("pricing_catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NFeEntrada",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "chave_acesso",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Chave de 44 dígitos SEFAZ.",
                        max_length=44,
                    ),
                ),
                ("numero", models.CharField(blank=True, default="", max_length=20)),
                ("serie", models.CharField(blank=True, default="", max_length=5)),
                ("emitente_cnpj", models.CharField(blank=True, default="", max_length=18)),
                ("emitente_nome", models.CharField(blank=True, default="", max_length=200)),
                ("data_emissao", models.DateField(blank=True, null=True)),
                ("valor_total", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("importada", "Importada"),
                            ("validada", "Validada"),
                            ("estoque_gerado", "Estoque Gerado"),
                        ],
                        db_index=True,
                        default="importada",
                        max_length=20,
                    ),
                ),
                ("estoque_gerado", models.BooleanField(default=False)),
                ("xml_s3_key", models.CharField(blank=True, default="", max_length=500)),
                ("observacoes", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "NF-e de Entrada",
                "verbose_name_plural": "NF-es de Entrada",
                "db_table": "fiscal_nfe_entrada",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NFeEntradaItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("numero_item", models.PositiveSmallIntegerField()),
                ("descricao_original", models.CharField(max_length=300)),
                ("codigo_produto_nf", models.CharField(blank=True, default="", max_length=60)),
                ("ncm", models.CharField(blank=True, default="", max_length=8)),
                ("unidade_compra", models.CharField(max_length=20)),
                ("quantidade", models.DecimalField(decimal_places=4, max_digits=12)),
                ("valor_unitario_bruto", models.DecimalField(decimal_places=4, max_digits=12)),
                (
                    "valor_unitario_com_tributos",
                    models.DecimalField(decimal_places=4, max_digits=12),
                ),
                ("valor_total_com_tributos", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "fator_conversao",
                    models.DecimalField(
                        decimal_places=4,
                        default=1,
                        help_text="Quantas unidades_base cabem em 1 unidade_compra.",
                        max_digits=10,
                    ),
                ),
                (
                    "status_reconciliacao",
                    models.CharField(
                        choices=[
                            ("pendente", "Aguardando reconciliação"),
                            ("peca", "Mapeado: Peça"),
                            ("insumo", "Mapeado: Insumo"),
                            ("ignorado", "Ignorado"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                (
                    "codigo_fornecedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nfe_itens",
                        to="pricing_catalog.codigofornecedorpeca",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "material_canonico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nfe_itens",
                        to="pricing_catalog.materialcanonico",
                    ),
                ),
                (
                    "nfe_entrada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="fiscal.nfeentrada",
                    ),
                ),
                (
                    "peca_canonica",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nfe_itens",
                        to="pricing_catalog.pecacanonica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de NF-e Entrada",
                "verbose_name_plural": "Itens de NF-e Entrada",
                "db_table": "fiscal_nfe_entrada_item",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="nfeentrada",
            index=models.Index(fields=["status"], name="fiscal_nfe__status_a7c941_idx"),
        ),
        migrations.AddIndex(
            model_name="nfeentrada",
            index=models.Index(fields=["chave_acesso"], name="fiscal_nfe__chave_a_3f1050_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="nfeentradaitem",
            unique_together={("nfe_entrada", "numero_item")},
        ),
    ]
