# Generated by Django 5.0 — Ciclo 06B: Fiscal Foundation
# APENAS CREATE TABLE — sem ALTER/DROP em tabelas existentes.
# Validado com: python manage.py sqlmigrate fiscal 0003

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0002_nfeentrada_nfeentradaitem_and_more"),
    ]

    operations = [
        # ─── FiscalConfigModel ──────────────────────────────────────────────
        migrations.CreateModel(
            name="FiscalConfigModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cnpj", models.CharField(help_text="CNPJ sem formatação (14 dígitos).", max_length=14, unique=True)),
                ("inscricao_estadual", models.CharField(blank=True, default="", max_length=20)),
                ("inscricao_municipal", models.CharField(blank=True, default="", max_length=20)),
                ("razao_social", models.CharField(max_length=200)),
                ("nome_fantasia", models.CharField(blank=True, default="", max_length=200)),
                ("regime_tributario", models.PositiveSmallIntegerField(
                    default=1,
                    help_text="1=Simples Nacional, 2=Simples Nacional Excesso, 3=Normal",
                )),
                ("endereco", models.JSONField(blank=True, default=dict, help_text="Endereço completo do emissor.")),
                ("focus_token", models.CharField(blank=True, default="", max_length=255)),
                ("aliquota_iss_default", models.DecimalField(
                    decimal_places=2,
                    default=Decimal("2"),
                    help_text="Alíquota ISS padrão (%). Manaus: 2%.",
                    max_digits=5,
                )),
                ("seq_nfse", models.PositiveIntegerField(default=1)),
                ("seq_nfe", models.PositiveIntegerField(default=1)),
                ("seq_nfce", models.PositiveIntegerField(default=1)),
                ("serie_rps", models.CharField(default="1", max_length=5)),
                ("environment", models.CharField(
                    choices=[("homologacao", "Homologação"), ("producao", "Produção")],
                    default="homologacao",
                    max_length=15,
                )),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuração Fiscal",
                "verbose_name_plural": "Configurações Fiscais",
                "db_table": "fiscal_config",
            },
        ),
        # ─── FiscalDocumentItem ─────────────────────────────────────────────
        migrations.CreateModel(
            name="FiscalDocumentItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("document", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="itens",
                    to="fiscal.fiscaldocument",
                )),
                ("numero_item", models.PositiveSmallIntegerField()),
                ("descricao", models.CharField(max_length=500)),
                ("ncm", models.CharField(blank=True, default="", max_length=8)),
                ("cfop", models.CharField(blank=True, default="", max_length=5)),
                ("unidade", models.CharField(blank=True, default="", max_length=6)),
                ("quantidade", models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ("valor_unitario", models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ("valor_total", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("valor_desconto", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("aliquota_iss", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("aliquota_icms", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("aliquota_pis", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("aliquota_cofins", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("source_budget_item", models.UUIDField(
                    blank=True,
                    db_index=True,
                    help_text="UUID do OrcamentoIntervencao de origem (sem FK forçada).",
                    null=True,
                )),
                ("source_os_item", models.UUIDField(
                    blank=True,
                    db_index=True,
                    help_text="UUID do OSIntervencao de origem (sem FK forçada).",
                    null=True,
                )),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Item de Documento Fiscal",
                "verbose_name_plural": "Itens de Documentos Fiscais",
                "db_table": "fiscal_document_item",
            },
        ),
        migrations.AddConstraint(
            model_name="fiscaldocumentitem",
            constraint=models.UniqueConstraint(
                fields=("document", "numero_item"),
                name="fiscal_docitem_doc_numero_uniq",
            ),
        ),
        # ─── FiscalEvent ────────────────────────────────────────────────────
        migrations.CreateModel(
            name="FiscalEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("document", models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="events",
                    to="fiscal.fiscaldocument",
                )),
                ("event_type", models.CharField(
                    choices=[
                        ("EMIT_REQUEST", "Requisição de Emissão"),
                        ("EMIT_RESPONSE", "Resposta de Emissão"),
                        ("CONSULT", "Consulta de Status"),
                        ("CANCEL_REQUEST", "Requisição de Cancelamento"),
                        ("WEBHOOK", "Webhook Recebido"),
                        ("CCE", "Carta de Correção"),
                        ("INUTILIZACAO", "Inutilização"),
                    ],
                    db_index=True,
                    max_length=20,
                )),
                ("http_status", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, default=dict, help_text="Payload enviado ou recebido.")),
                ("response", models.JSONField(blank=True, default=dict, help_text="Resposta da API Focus.")),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("error_type", models.CharField(blank=True, default="", max_length=60)),
                ("error_message", models.TextField(blank=True, default="")),
                ("triggered_by", models.CharField(
                    choices=[
                        ("USER", "Usuário (automatizado)"),
                        ("USER_MANUAL", "Usuário (manual ad-hoc)"),
                        ("CELERY", "Tarefa Celery"),
                        ("WEBHOOK", "Webhook Focus"),
                    ],
                    default="USER",
                    max_length=15,
                )),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Evento Fiscal",
                "verbose_name_plural": "Eventos Fiscais",
                "db_table": "fiscal_event",
            },
        ),
        migrations.AddIndex(
            model_name="fiscalevent",
            index=models.Index(fields=["document", "event_type"], name="fiscal_event_doc_type_idx"),
        ),
        migrations.AddIndex(
            model_name="fiscalevent",
            index=models.Index(fields=["created_at"], name="fiscal_event_created_idx"),
        ),
    ]
