# Generated by Django 5.0.10 on 2026-04-24 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0004_fiscal_document_spec_52"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="fiscaldocumentitem",
            name="fiscal_docitem_doc_numero_uniq",
        ),
        migrations.RenameIndex(
            model_name="fiscalevent",
            new_name="fiscal_even_documen_77efe6_idx",
            old_name="fiscal_event_doc_type_idx",
        ),
        migrations.RenameIndex(
            model_name="fiscalevent",
            new_name="fiscal_even_created_50c73d_idx",
            old_name="fiscal_event_created_idx",
        ),
        migrations.AlterUniqueTogether(
            name="fiscaldocumentitem",
            unique_together={("document", "numero_item")},
        ),
    ]
