# Generated by Django 5.0.10 on 2026-04-24 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0005_remove_fiscaldocumentitem_fiscal_docitem_doc_numero_uniq_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fiscalconfigmodel",
            name="aliquota_cofins",
            field=models.DecimalField(
                decimal_places=2,
                default=3,
                help_text="Alíquota COFINS (%). Lucro Presumido cumulativo: 3%.",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="fiscalconfigmodel",
            name="aliquota_pis",
            field=models.DecimalField(
                decimal_places=2,
                default="0.65",
                help_text="Alíquota PIS (%). Lucro Presumido cumulativo: 0,65%.",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="fiscalconfigmodel",
            name="cst_cofins_saida",
            field=models.CharField(
                default="01",
                help_text="CST COFINS padrão saída. 01=operação tributável.",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="fiscalconfigmodel",
            name="cst_icms_saida",
            field=models.CharField(
                default="00",
                help_text="CST ICMS padrão para saída. 00=tributação integral.",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="fiscalconfigmodel",
            name="cst_pis_saida",
            field=models.CharField(
                default="01",
                help_text="CST PIS padrão saída. 01=operação tributável.",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="fiscalconfigmodel",
            name="icms_aliquota_interestadual_12",
            field=models.DecimalField(
                decimal_places=2,
                default=12,
                help_text="Alíquota ICMS interestadual para estados 12% (SP, RJ, MG…).",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="fiscalconfigmodel",
            name="icms_aliquota_interestadual_7",
            field=models.DecimalField(
                decimal_places=2,
                default=7,
                help_text="Alíquota ICMS interestadual para estados 7% (AC, AL, AP, BA, CE…).",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="fiscalconfigmodel",
            name="icms_aliquota_intraestadual",
            field=models.DecimalField(
                decimal_places=2,
                default=12,
                help_text="Alíquota ICMS intraestadual (%). Padrão AM: 12%.",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="fiscalconfigmodel",
            name="icms_modalidade_base_calculo",
            field=models.CharField(
                default="3", help_text="Modalidade base ICMS. 3=valor da operação.", max_length=1
            ),
        ),
        migrations.AddField(
            model_name="fiscalconfigmodel",
            name="nfe_bairro",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AddField(
            model_name="fiscalconfigmodel",
            name="nfe_cep",
            field=models.CharField(
                blank=True, default="", help_text="CEP sem traço (8 dígitos).", max_length=8
            ),
        ),
        migrations.AddField(
            model_name="fiscalconfigmodel",
            name="nfe_indicador_consumidor_final",
            field=models.CharField(
                default="1",
                help_text="1=consumidor final (PF), 0=não (PJ contribuinte).",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="fiscalconfigmodel",
            name="nfe_indicador_presenca",
            field=models.CharField(default="1", help_text="1=presencial; 9=outros.", max_length=1),
        ),
        migrations.AddField(
            model_name="fiscalconfigmodel",
            name="nfe_logradouro",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="fiscalconfigmodel",
            name="nfe_municipio",
            field=models.CharField(blank=True, default="Manaus", max_length=60),
        ),
        migrations.AddField(
            model_name="fiscalconfigmodel",
            name="nfe_natureza_operacao",
            field=models.CharField(default="Venda de mercadoria", max_length=60),
        ),
        migrations.AddField(
            model_name="fiscalconfigmodel",
            name="nfe_numero",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="fiscalconfigmodel",
            name="nfe_uf",
            field=models.CharField(blank=True, default="AM", max_length=2),
        ),
    ]
