# Generated by Django 5.0.10 on 2026-05-02 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0006_fiscalconfigmodel_aliquota_cofins_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fiscaldocument",
            name="environment",
            field=models.CharField(
                blank=True,
                choices=[("homologacao", "Homologação"), ("producao", "Produção")],
                default="homologacao",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="fiscalevent",
            name="triggered_by",
            field=models.CharField(
                choices=[
                    ("USER", "Usuário (automatizado)"),
                    ("USER_MANUAL", "Usuário (manual ad-hoc)"),
                    ("BILLING", "Faturamento de OS"),
                    ("CELERY", "Tarefa Celery"),
                    ("WEBHOOK", "Webhook Focus"),
                ],
                default="USER",
                max_length=15,
            ),
        ),
    ]
