# Generated by Django 5.0.10 on 2026-04-23 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0001_initial"),
        ("service_orders", "0021_versioning_and_events"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importattempt",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="importattempt",
            name="version_created",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="imports_version_attempts",
                to="service_orders.serviceorderversion",
            ),
        ),
    ]
