# Generated by Django 5.0.10 on 2026-03-30 00:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("number", models.PositiveIntegerField(db_index=True, verbose_name="Número da OS")),
                ("customer_id", models.UUIDField(db_index=True, verbose_name="ID do Cliente")),
                ("customer_name", models.CharField(max_length=200, verbose_name="Nome do cliente")),
                ("plate", models.CharField(db_index=True, max_length=10, verbose_name="Placa")),
                ("make", models.CharField(default="", max_length=100, verbose_name="Marca")),
                ("model", models.CharField(default="", max_length=100, verbose_name="Modelo")),
                (
                    "year",
                    models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Ano"),
                ),
                ("color", models.CharField(default="", max_length=50, verbose_name="Cor")),
                (
                    "mileage_in",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="KM entrada"),
                ),
                (
                    "mileage_out",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="KM saída"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reception", "Recepção"),
                            ("initial_survey", "Vistoria Inicial"),
                            ("budget", "Orçamento"),
                            ("waiting_parts", "Aguardando Peças"),
                            ("repair", "Reparo"),
                            ("mechanic", "Mecânica"),
                            ("bodywork", "Funilaria"),
                            ("painting", "Pintura"),
                            ("assembly", "Montagem"),
                            ("polishing", "Polimento"),
                            ("washing", "Lavagem"),
                            ("final_survey", "Vistoria Final"),
                            ("ready", "Pronto"),
                            ("delivered", "Entregue"),
                            ("cancelled", "Cancelado"),
                        ],
                        db_index=True,
                        default="reception",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("estimated_delivery", models.DateTimeField(blank=True, null=True)),
                ("parts_total", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("services_total", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("discount_total", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                (
                    "nfe_key",
                    models.CharField(
                        blank=True, default="", max_length=44, verbose_name="Chave NF-e"
                    ),
                ),
                (
                    "nfse_number",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="Número NFS-e"
                    ),
                ),
                ("ai_recommendations", models.JSONField(blank=True, default=list)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ordem de Serviço",
                "verbose_name_plural": "Ordens de Serviço",
                "db_table": "service_orders_order",
                "ordering": ["-created_at"],
                "abstract": False,
                "unique_together": {("number",)},
            },
        ),
        migrations.CreateModel(
            name="ServiceOrderPhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("reception", "Recepção"),
                            ("initial_survey", "Vistoria Inicial"),
                            ("budget", "Orçamento"),
                            ("waiting_parts", "Aguardando Peças"),
                            ("repair", "Reparo"),
                            ("mechanic", "Mecânica"),
                            ("bodywork", "Funilaria"),
                            ("painting", "Pintura"),
                            ("assembly", "Montagem"),
                            ("polishing", "Polimento"),
                            ("washing", "Lavagem"),
                            ("final_survey", "Vistoria Final"),
                            ("ready", "Pronto"),
                            ("delivered", "Entregue"),
                            ("cancelled", "Cancelado"),
                        ],
                        max_length=30,
                    ),
                ),
                ("s3_key", models.CharField(max_length=500, verbose_name="S3 Key")),
                ("uploaded_by_id", models.UUIDField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "service_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="service_orders.serviceorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foto de OS",
                "verbose_name_plural": "Fotos de OS",
                "db_table": "service_orders_photo",
            },
        ),
    ]
