# Generated by Django 5.2.12 on 2026-04-21 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('cnpj', models.CharField(blank=True, default='', max_length=18)),
                ('import_source', models.CharField(blank=True, choices=[('cilia_api', 'Cilia API'), ('html_upload', 'HTML Upload'), ('xml_upload', 'XML Upload')], default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
