# Generated by Django 5.2.12 on 2026-04-21 01:18

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_add_version_model'),
        ('persons', '0001_initial'),
        ('service_orders', '0003_seed_insurers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrderVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('external_version', models.CharField(blank=True, default='', max_length=40)),
                ('external_numero_vistoria', models.CharField(blank=True, default='', max_length=60)),
                ('external_integration_id', models.CharField(blank=True, default='', max_length=40)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('budget_approval', 'Da aprovação de Budget'), ('cilia', 'Cilia API'), ('hdi', 'HDI HTML'), ('xml_porto', 'XML Porto'), ('xml_azul', 'XML Azul'), ('xml_itau', 'XML Itaú')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada'), ('analisado', 'Analisado'), ('autorizado', 'Autorizado'), ('correcao', 'Em Correção'), ('em_analise', 'Em Análise'), ('negado', 'Negado'), ('superseded', 'Superada')], db_index=True, default='pending', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('net_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('labor_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('parts_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_seguradora', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_complemento_particular', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_franquia', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('raw_payload_s3_key', models.CharField(blank=True, default='', max_length=500)),
                ('hourly_rates', models.JSONField(blank=True, default=dict)),
                ('global_discount_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=120)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOrderVersionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.CharField(choices=[('IMPACTO', 'Impacto'), ('SEM_COBERTURA', 'Sem Cobertura'), ('SOB_ANALISE', 'Sob Análise')], db_index=True, default='IMPACTO', max_length=20)),
                ('payer_block', models.CharField(choices=[('SEGURADORA', 'Coberto pela Seguradora'), ('COMPLEMENTO_PARTICULAR', 'Complemento Particular'), ('FRANQUIA', 'Franquia'), ('PARTICULAR', 'Particular (OS particular inteira)')], db_index=True, default='PARTICULAR', max_length=30)),
                ('impact_area', models.IntegerField(blank=True, db_index=True, null=True)),
                ('item_type', models.CharField(choices=[('PART', 'Peça'), ('SERVICE', 'Serviço interno'), ('EXTERNAL_SERVICE', 'Serviço terceirizado'), ('FEE', 'Taxa'), ('DISCOUNT', 'Desconto')], default='PART', max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('external_code', models.CharField(blank=True, default='', max_length=60)),
                ('part_type', models.CharField(blank=True, choices=[('GENUINA', 'Genuína'), ('ORIGINAL', 'Original'), ('OUTRAS_FONTES', 'Outras Fontes'), ('VERDE', 'Verde (reuso)')], default='', max_length=20)),
                ('supplier', models.CharField(choices=[('OFICINA', 'Oficina'), ('SEGURADORA', 'Seguradora')], default='OFICINA', max_length=12)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('net_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('flag_abaixo_padrao', models.BooleanField(default=False)),
                ('flag_acima_padrao', models.BooleanField(default=False)),
                ('flag_inclusao_manual', models.BooleanField(default=False)),
                ('flag_codigo_diferente', models.BooleanField(default=False)),
                ('flag_servico_manual', models.BooleanField(default=False)),
                ('flag_peca_da_conta', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='casualty_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='customer_type',
            field=models.CharField(choices=[('PARTICULAR', 'Particular'), ('SEGURADORA', 'Seguradora')], db_index=True, default='PARTICULAR', max_length=12),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='external_budget_number',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='franchise_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='insurer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='service_orders.insurer'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='legacy_databox_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='policy_item',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='policy_number',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='previous_status',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='source_budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resulting_orders', to='budgets.budget'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('reception', 'Recepção'), ('initial_survey', 'Vistoria Inicial'), ('budget', 'Orçamento (aprovação de versão)'), ('waiting_parts', 'Aguardando Peças'), ('repair', 'Reparo'), ('mechanic', 'Mecânica'), ('bodywork', 'Funilaria'), ('painting', 'Pintura'), ('assembly', 'Montagem'), ('polishing', 'Polimento'), ('washing', 'Lavagem'), ('final_survey', 'Vistoria Final'), ('ready', 'Pronto para Entrega'), ('delivered', 'Entregue'), ('cancelled', 'Cancelada')], db_index=True, default='reception', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='serviceorder',
            constraint=models.UniqueConstraint(condition=models.Q(('casualty_number__gt', '')), fields=('insurer', 'casualty_number'), name='uq_insurer_casualty'),
        ),
        migrations.AddField(
            model_name='serviceorderversion',
            name='service_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='service_orders.serviceorder'),
        ),
        migrations.AddField(
            model_name='serviceorderversionitem',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='service_orders.serviceorderversion'),
        ),
        migrations.AlterUniqueTogether(
            name='serviceorderversion',
            unique_together={('service_order', 'version_number')},
        ),
    ]
