# Generated by Django 5.0.10 on 2026-04-03 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experts", "0002_alter_expert_created_by_alter_expert_is_active"),
        ("insurers", "0001_initial"),
        ("persons", "0002_logo_url_charfield"),
        ("service_orders", "0003_os_sprint_001_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="serviceorder",
            new_name="service_ord_custome_794e67_idx",
            old_name="so_customer_type_idx",
        ),
        migrations.RenameIndex(
            model_name="serviceorder",
            new_name="service_ord_insurer_624df9_idx",
            old_name="so_insurer_casualty_idx",
        ),
        migrations.AlterField(
            model_name="serviceorderphoto",
            name="stage",
            field=models.CharField(
                choices=[
                    ("reception", "Recepção"),
                    ("initial_survey", "Vistoria Inicial"),
                    ("budget", "Orçamento"),
                    ("waiting_auth", "Aguardando Autorização"),
                    ("authorized", "Autorizada"),
                    ("waiting_parts", "Aguardando Peças"),
                    ("repair", "Reparo"),
                    ("mechanic", "Mecânica"),
                    ("bodywork", "Funilaria"),
                    ("painting", "Pintura"),
                    ("assembly", "Montagem"),
                    ("polishing", "Polimento"),
                    ("washing", "Lavagem"),
                    ("final_survey", "Vistoria Final"),
                    ("ready", "Pronto para Entrega"),
                    ("delivered", "Entregue"),
                    ("cancelled", "Cancelada"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="statustransitionlog",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="serviceorder",
            index=models.Index(fields=["status"], name="service_ord_status_80aa05_idx"),
        ),
        migrations.AddIndex(
            model_name="serviceorder",
            index=models.Index(fields=["number"], name="service_ord_number_0979d3_idx"),
        ),
    ]
