# Generated by Django 5.2.12 on 2026-04-21 01:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0004_add_version_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='DEPRECATED — remover no Ciclo 2. Use active_version.net_total', max_digits=12),
        ),
        migrations.AddIndex(
            model_name='serviceorderversion',
            index=models.Index(fields=['status', '-created_at'], name='sov_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceorderversion',
            index=models.Index(fields=['source', 'status'], name='sov_source_status_idx'),
        ),
    ]
