# Generated by Django 5.0.10 on 2026-04-03 02:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "service_orders",
            "0004_rename_so_customer_type_idx_service_ord_custome_794e67_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceOrderActivityLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("created", "OS Aberta"),
                            ("status_changed", "Status Alterado"),
                            ("updated", "Informação Atualizada"),
                            ("reminder", "Lembrete Adicionado"),
                            ("file_upload", "Arquivo Anexado"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Descrição minuciosa (ex: Thiago mudou X para Y)"),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="service_orders.serviceorder",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Atividade",
                "verbose_name_plural": "Históricos de Atividade",
                "db_table": "service_orders_activity_log",
                "ordering": ["-created_at"],
            },
        ),
    ]
