# Generated by Django 5.2.12 on 2026-04-21 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0005_add_version_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrderParecer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('internal', 'Interno DSCar'), ('cilia', 'Cilia'), ('hdi', 'HDI'), ('xml_porto', 'XML Porto'), ('xml_azul', 'XML Azul'), ('xml_itau', 'XML Itaú')], max_length=20)),
                ('flow_number', models.IntegerField(blank=True, null=True)),
                ('author_external', models.CharField(blank=True, default='', max_length=120)),
                ('author_org', models.CharField(blank=True, default='', max_length=120)),
                ('author_internal', models.CharField(blank=True, default='', max_length=120)),
                ('parecer_type', models.CharField(blank=True, choices=[('CONCORDADO', 'Concordado'), ('AUTORIZADO', 'Autorizado'), ('CORRECAO', 'Correção'), ('NEGADO', 'Negado'), ('SEM_COBERTURA', 'Sem Cobertura'), ('COMENTARIO_INTERNO', 'Comentário Interno')], default='', max_length=30)),
                ('body', models.TextField()),
                ('created_at_external', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pareceres', to='service_orders.serviceorder')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pareceres', to='service_orders.serviceorderversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImpactAreaLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_number', models.IntegerField()),
                ('label_text', models.CharField(max_length=100)),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_labels', to='service_orders.serviceorder')),
            ],
            options={
                'ordering': ['area_number'],
                'unique_together': {('service_order', 'area_number')},
            },
        ),
        migrations.CreateModel(
            name='ServiceOrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('STATUS_CHANGE', 'Mudança de status'), ('AUTO_TRANSITION', 'Transição automática'), ('VERSION_CREATED', 'Nova versão criada'), ('VERSION_APPROVED', 'Versão aprovada'), ('VERSION_REJECTED', 'Versão rejeitada'), ('ITEM_ADDED', 'Item adicionado'), ('ITEM_REMOVED', 'Item removido'), ('ITEM_EDITED', 'Item editado'), ('IMPORT_RECEIVED', 'Importação recebida'), ('PARECER_ADDED', 'Parecer adicionado'), ('PHOTO_UPLOADED', 'Foto anexada'), ('PHOTO_REMOVED', 'Foto removida'), ('PAYMENT_RECORDED', 'Pagamento registrado'), ('FISCAL_ISSUED', 'Nota fiscal emitida'), ('SIGNATURE_CAPTURED', 'Assinatura capturada'), ('BUDGET_LINKED', 'Budget aprovado virou OS')], db_index=True, max_length=30)),
                ('actor', models.CharField(blank=True, default='Sistema', max_length=120)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('from_state', models.CharField(blank=True, default='', max_length=30)),
                ('to_state', models.CharField(blank=True, default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='service_orders.serviceorder')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['service_order', '-created_at'], name='soevent_os_created_idx'), models.Index(fields=['event_type', '-created_at'], name='soevent_type_created_idx')],
            },
        ),
    ]
