# Generated by Django 5.2.12 on 2026-04-21 01:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0006_add_event_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorderevent',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
    ]
