# Generated by Django 5.2.12 on 2026-04-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0009_backfill_v1_for_existing_os'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorderversion',
            name='external_budget_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceorderversion',
            name='external_flow_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceorderversion',
            name='external_version_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceorderversion',
            name='raw_payload',
            field=models.JSONField(blank=True, help_text='Payload bruto da fonte (Cilia JSON, XML parseado, etc) — preserva dados nao-mapeados', null=True),
        ),
        migrations.AddField(
            model_name='serviceorderversion',
            name='report_html_base64',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='serviceorderversion',
            name='report_pdf_base64',
            field=models.TextField(blank=True, default=''),
        ),
    ]
