# Generated by Django 5.0.10 on 2026-04-12 03:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0012_add_checklist_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='checklistitem',
            name='unique_checklist_item_per_os',
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='vehicle_version',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Versão'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='item_key',
            field=models.CharField(help_text='Identificador único do item dentro da categoria (ex: arranhoes)', max_length=60, verbose_name='Chave do Item'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='checklistitem',
            unique_together={('service_order', 'checklist_type', 'category', 'item_key')},
        ),
    ]
