# Generated by Django 5.0.10 on 2026-04-12 03:03
# Manually split from auto-generated migration — adds vehicle_version to ServiceOrder.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0013_fix_checklist_item_drift'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='vehicle_version',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Versão'),
        ),
    ]
