# Generated by Django 5.0.10 on 2026-04-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0014_vehicle_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceorder",
            name="customer_uuid",
            field=models.UUIDField(
                blank=True, db_index=True, null=True, verbose_name="UUID do cliente"
            ),
        ),
    ]
