# Generated by Django 5.0.10 on 2026-04-13 16:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0014_vehicle_version"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceCatalog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, verbose_name="Nome do serviço")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descrição / observação"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("funilaria", "Funilaria / Chapeação"),
                            ("pintura", "Pintura"),
                            ("mecanica", "Mecânica"),
                            ("eletrica", "Elétrica"),
                            ("estetica", "Estética"),
                            ("alinhamento", "Alinhamento / Balanceamento"),
                            ("revisao", "Revisão"),
                            ("lavagem", "Lavagem / Higienização"),
                            ("outros", "Outros"),
                        ],
                        default="outros",
                        max_length=20,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "suggested_price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="Preço sugerido"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Serviço do catálogo",
                "verbose_name_plural": "Catálogo de serviços",
                "db_table": "service_catalog",
                "ordering": ["category", "name"],
            },
        ),
        migrations.AddField(
            model_name="serviceorderlabor",
            name="service_catalog",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="labor_items",
                to="service_orders.servicecatalog",
                verbose_name="Serviço do catálogo",
            ),
        ),
    ]
