# Generated by Django 5.0.10 on 2026-04-13 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0015_add_customer_uuid"),
        ("service_orders", "0015_service_catalog"),
    ]

    operations = []
