# Generated by Django 5.0.10 on 2026-04-16 19:06

from django.db import migrations, models


def populate_empresa_id(apps, schema_editor):
    """
    Popula empresa_id nas OSs existentes com o UUID da primeira Empresa ativa
    do tenant. Em tenant fresco (sem Empresa ainda), deixa NULL — o seed
    setup_perfil_veicular será executado depois.
    """
    ServiceOrder = apps.get_model("service_orders", "ServiceOrder")
    try:
        Empresa = apps.get_model("pricing_profile", "Empresa")
        empresa = Empresa.objects.filter(is_active=True).order_by("created_at").first()
        if empresa:
            ServiceOrder.objects.filter(empresa_id__isnull=True).update(
                empresa_id=empresa.id
            )
    except Exception:
        # pricing_profile pode não existir no schema ainda (primeira migration)
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0017_holiday"),
        ("pricing_profile", "0001_initial"),  # garante que pricing_profile existe
    ]

    operations = [
        migrations.AddField(
            model_name="serviceorder",
            name="empresa_id",
            field=models.UUIDField(
                blank=True,
                help_text="UUID da Empresa (pricing_profile.Empresa) — referência solta, igual ao customer_uuid.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="segmento_codigo",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Código do SegmentoVeicular resolvido pelo EnquadramentoService.",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="tamanho_codigo",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Código da CategoriaTamanho resolvida pelo EnquadramentoService.",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="tipo_pintura_codigo",
            field=models.CharField(
                blank=True,
                help_text="Código do TipoPintura resolvido pelo EnquadramentoService.",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="vehicle_fipe_value_snapshot",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Valor FIPE congelado no momento de criação da OS (R$).",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="vehicle_make_id",
            field=models.CharField(
                blank=True,
                help_text="fipe_id da marca — referência solta a vehicle_catalog.VehicleMake",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="vehicle_model_id",
            field=models.CharField(
                blank=True,
                help_text="fipe_id do modelo — referência solta a vehicle_catalog.VehicleModel",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="vehicle_year_version_id",
            field=models.CharField(
                blank=True,
                help_text="fipe_id do ano/versão — referência solta a vehicle_catalog.VehicleYearVersion",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="holiday",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="holiday",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="servicecatalog",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Descrição / observação"),
        ),
        migrations.AlterField(
            model_name="serviceorderactivitylog",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("created", "OS Aberta"),
                    ("status_changed", "Status Alterado"),
                    ("updated", "Informação Atualizada"),
                    ("customer_updated", "Cliente Atualizado"),
                    ("vehicle_updated", "Veículo Atualizado"),
                    ("schedule_updated", "Datas/Prazo Atualizados"),
                    ("insurer_updated", "Seguradora Atualizada"),
                    ("reminder", "Lembrete Adicionado"),
                    ("file_upload", "Arquivo Anexado"),
                    ("note_added", "Nota Adicionada"),
                    ("budget_snapshot", "Snapshot de Orçamento"),
                    ("cilia_import", "Importação Cilia"),
                    ("delivery", "Entrega ao Cliente"),
                    ("part_added", "Peça Adicionada"),
                    ("part_removed", "Peça Removida"),
                    ("part_updated", "Peça Editada"),
                    ("labor_added", "Serviço Adicionado"),
                    ("labor_removed", "Serviço Removido"),
                    ("labor_updated", "Serviço Editado"),
                    ("invoice_issued", "NF Emitida"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="serviceorderphoto",
            name="folder",
            field=models.CharField(
                choices=[
                    ("vistoria_inicial", "Vistoria Inicial"),
                    ("complemento", "Complemento"),
                    ("checklist_entrada", "Checklist de Entrada"),
                    ("checklist_saida", "Checklist de Saída"),
                    ("documentos", "Documentos"),
                    ("orcamentos", "Orçamentos"),
                    ("acompanhamento", "Acompanhamento de Reparos"),
                    ("vistoria_final", "Vistoria Final"),
                    ("pericia", "Perícia"),
                    ("outros", "Outros"),
                ],
                default="vistoria_inicial",
                max_length=30,
                verbose_name="Pasta",
            ),
        ),
        migrations.RunPython(populate_empresa_id, migrations.RunPython.noop),
    ]
