# Generated by Django 5.0 — Motor de Orçamentos MO-7 (OSAreaImpacto, OSIntervencao, OSItemAdicional, ApontamentoHoras)

import django.db.models.deletion
import uuid

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_globaluser_push_token"),
        ("inventory", "0002_impressoraetiqueta_loteinsumo_consumoinsumo_and_more"),
        ("pricing_catalog", "0001_initial"),
        ("pricing_engine", "0004_snapshot_fk_no_db_constraint"),
        ("pricing_tech", "0001_initial"),
        ("quotes", "0001_initial"),
        ("service_orders", "0018_vehicle_profile_snapshot"),
    ]

    operations = [
        # ── OSAreaImpacto ──────────────────────────────────────────────────────
        migrations.CreateModel(
            name="OSAreaImpacto",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("titulo", models.CharField(max_length=120, verbose_name="Título")),
                ("ordem", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(
                    choices=[
                        ("aberta", "Aberta"),
                        ("aprovada", "Aprovada"),
                        ("negada_pre_exist", "Negada — pré-existência"),
                        ("parcial", "Parcial"),
                        ("cancelada", "Cancelada"),
                    ],
                    default="aprovada",
                    max_length=20,
                    verbose_name="Status",
                )),
                ("observacao_regulador", models.TextField(blank=True, verbose_name="Observação do regulador")),
                ("created_by", models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    to=settings.AUTH_USER_MODEL,
                    related_name="+",
                )),
                ("service_order", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="areas_motor",
                    to="service_orders.serviceorder",
                    verbose_name="OS",
                )),
                ("area_impacto_origem", models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name="os_areas",
                    to="quotes.areaimpacto",
                    verbose_name="Área de impacto origem",
                )),
            ],
            options={
                "verbose_name": "Área de Impacto (OS)",
                "verbose_name_plural": "Áreas de Impacto (OS)",
                "ordering": ["ordem"],
            },
        ),

        # ── OSIntervencao ──────────────────────────────────────────────────────
        migrations.CreateModel(
            name="OSIntervencao",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("acao", models.CharField(
                    choices=[
                        ("trocar", "Trocar"),
                        ("reparar", "Reparar"),
                        ("pintar", "Pintar"),
                        ("remocao_instalacao", "Remoção e instalação"),
                    ],
                    max_length=20,
                    verbose_name="Ação",
                )),
                ("qualificador_peca", models.CharField(blank=True, max_length=10, verbose_name="Qualificador de peça")),
                ("fornecimento", models.CharField(
                    choices=[("oficina", "Oficina"), ("seguradora", "Seguradora"), ("cliente", "Cliente")],
                    default="oficina",
                    max_length=20,
                    verbose_name="Fornecimento",
                )),
                ("codigo_peca", models.CharField(blank=True, max_length=60, verbose_name="Código da peça")),
                ("quantidade", models.PositiveIntegerField(default=1)),
                ("horas_mao_obra", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ("valor_peca", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("valor_mao_obra", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("valor_insumos", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("preco_total", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("status", models.CharField(
                    choices=[
                        ("orcado", "Orçado"),
                        ("aprovado", "Aprovado"),
                        ("sem_cobertura", "Sem cobertura"),
                        ("sob_analise", "Sob análise"),
                        ("executado", "Executado"),
                        ("cancelado", "Cancelado"),
                    ],
                    default="aprovado",
                    max_length=20,
                    verbose_name="Status Cilia",
                )),
                ("abaixo_padrao", models.BooleanField(default=False)),
                ("acima_padrao", models.BooleanField(default=False)),
                ("codigo_diferente", models.BooleanField(default=False)),
                ("ordem", models.PositiveIntegerField(default=0)),
                ("descricao_visivel", models.CharField(blank=True, max_length=300)),
                ("observacao", models.TextField(blank=True)),
                ("created_by", models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    to=settings.AUTH_USER_MODEL,
                    related_name="+",
                )),
                ("service_order", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="intervencoes_motor",
                    to="service_orders.serviceorder",
                    verbose_name="OS",
                )),
                ("area", models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name="intervencoes",
                    to="service_orders.osareaimpacto",
                    verbose_name="Área de impacto",
                )),
                ("orcamento_intervencao", models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name="os_intervencoes",
                    to="quotes.orcamentointervencao",
                    verbose_name="Intervenção do orçamento",
                )),
                ("peca_canonica", models.ForeignKey(
                    db_constraint=False,
                    on_delete=django.db.models.deletion.PROTECT,
                    to="pricing_catalog.pecacanonica",
                    verbose_name="Peça canônica",
                )),
                ("servico_canonico", models.ForeignKey(
                    db_constraint=False,
                    on_delete=django.db.models.deletion.PROTECT,
                    to="pricing_catalog.servicocanonico",
                    verbose_name="Serviço canônico",
                )),
                ("ficha_tecnica", models.ForeignKey(
                    blank=True,
                    db_constraint=False,
                    null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    to="pricing_tech.fichatecnicaservico",
                    verbose_name="Ficha técnica",
                )),
                ("snapshot", models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name="os_intervencoes",
                    to="pricing_engine.calculocustosnapshot",
                    verbose_name="Snapshot de custo",
                )),
                ("unidade_reservada", models.ForeignKey(
                    blank=True,
                    db_constraint=False,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name="os_intervencoes",
                    to="inventory.unidadefisica",
                    verbose_name="Unidade reservada",
                )),
            ],
            options={
                "verbose_name": "Intervenção (OS)",
                "verbose_name_plural": "Intervenções (OS)",
                "ordering": ["area__ordem", "ordem"],
            },
        ),
        migrations.AddIndex(
            model_name="osintervencao",
            index=models.Index(fields=["service_order", "status"], name="so_osiv_status_idx"),
        ),

        # ── OSItemAdicional ────────────────────────────────────────────────────
        migrations.CreateModel(
            name="OSItemAdicional",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("quantidade", models.PositiveIntegerField(default=1)),
                ("preco_unitario", models.DecimalField(decimal_places=2, max_digits=18)),
                ("preco_total", models.DecimalField(decimal_places=2, max_digits=18)),
                ("status", models.CharField(
                    choices=[
                        ("orcado", "Orçado"),
                        ("aprovado", "Aprovado"),
                        ("sem_cobertura", "Sem cobertura"),
                        ("sob_analise", "Sob análise"),
                        ("executado", "Executado"),
                        ("cancelado", "Cancelado"),
                    ],
                    default="aprovado",
                    max_length=20,
                )),
                ("fornecimento", models.CharField(
                    choices=[("oficina", "Oficina"), ("seguradora", "Seguradora"), ("cliente", "Cliente")],
                    default="oficina",
                    max_length=20,
                )),
                ("inclusao_manual", models.BooleanField(default=False)),
                ("abaixo_padrao", models.BooleanField(default=False)),
                ("acima_padrao", models.BooleanField(default=False)),
                ("ordem", models.PositiveIntegerField(default=0)),
                ("descricao_visivel", models.CharField(blank=True, max_length=300)),
                ("observacao", models.TextField(blank=True)),
                ("created_by", models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    to=settings.AUTH_USER_MODEL,
                    related_name="+",
                )),
                ("service_order", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="itens_adicionais_motor",
                    to="service_orders.serviceorder",
                    verbose_name="OS",
                )),
                ("orcamento_item_adicional", models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name="os_itens",
                    to="quotes.orcamentoitemadicional",
                    verbose_name="Item adicional do orçamento",
                )),
                ("service_catalog", models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name="os_itens",
                    to="service_orders.servicecatalog",
                    verbose_name="Serviço do catálogo",
                )),
                ("snapshot", models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name="os_itens",
                    to="pricing_engine.calculocustosnapshot",
                    verbose_name="Snapshot de custo",
                )),
            ],
            options={
                "verbose_name": "Item Adicional (OS)",
                "verbose_name_plural": "Itens Adicionais (OS)",
                "ordering": ["ordem"],
            },
        ),
        migrations.AddIndex(
            model_name="ositemadicional",
            index=models.Index(fields=["service_order", "status"], name="so_ositem_status_idx"),
        ),

        # ── ApontamentoHoras ───────────────────────────────────────────────────
        migrations.CreateModel(
            name="ApontamentoHoras",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("iniciado_em", models.DateTimeField(verbose_name="Iniciado em")),
                ("encerrado_em", models.DateTimeField(blank=True, null=True, verbose_name="Encerrado em")),
                ("horas_apontadas", models.DecimalField(
                    decimal_places=2, default=0, max_digits=6, verbose_name="Horas apontadas"
                )),
                ("observacao", models.TextField(blank=True)),
                ("status", models.CharField(
                    choices=[("iniciado", "Iniciado"), ("encerrado", "Encerrado"), ("validado", "Validado")],
                    default="iniciado",
                    max_length=20,
                    verbose_name="Status",
                )),
                ("created_by", models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    to=settings.AUTH_USER_MODEL,
                    related_name="+",
                )),
                ("service_order", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="apontamentos",
                    to="service_orders.serviceorder",
                    verbose_name="OS",
                )),
                ("os_intervencao", models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name="apontamentos",
                    to="service_orders.osintervencao",
                    verbose_name="Intervenção",
                )),
                ("tecnico", models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name="apontamentos",
                    to=settings.AUTH_USER_MODEL,
                    verbose_name="Técnico",
                )),
            ],
            options={
                "verbose_name": "Apontamento de Horas",
                "verbose_name_plural": "Apontamentos de Horas",
                "ordering": ["-iniciado_em"],
            },
        ),
        migrations.AddIndex(
            model_name="apontamentohoras",
            index=models.Index(fields=["service_order", "status"], name="so_apon_os_status_idx"),
        ),
        migrations.AddIndex(
            model_name="apontamentohoras",
            index=models.Index(fields=["tecnico", "-iniciado_em"], name="so_apon_tecnico_idx"),
        ),
    ]
