# Generated by Django 5.0.10 on 2026-04-19 23:38

import apps.service_orders.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0004_alter_employee_person"),
        ("pricing_catalog", "0001_initial"),
        ("service_orders", "0019_motor_entities"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BloqueioCapacidade",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("data_inicio", models.DateField(verbose_name="Data início")),
                ("data_fim", models.DateField(verbose_name="Data fim")),
                ("motivo", models.CharField(max_length=100, verbose_name="Motivo")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Bloqueio de Capacidade",
                "verbose_name_plural": "Bloqueios de Capacidade",
            },
        ),
        migrations.CreateModel(
            name="CapacidadeTecnico",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "horas_dia_util",
                    models.DecimalField(
                        decimal_places=2, default=8, max_digits=4, verbose_name="Horas por dia útil"
                    ),
                ),
                (
                    "dias_semana",
                    models.JSONField(
                        default=apps.service_orders.models._dias_semana_default,
                        help_text="Lista ISO weekdays (1=seg, 7=dom) em que o técnico trabalha.",
                        verbose_name="Dias de trabalho",
                    ),
                ),
                ("vigente_desde", models.DateField(verbose_name="Vigente desde")),
                (
                    "vigente_ate",
                    models.DateField(blank=True, null=True, verbose_name="Vigente até"),
                ),
            ],
            options={
                "verbose_name": "Capacidade de Técnico",
                "verbose_name_plural": "Capacidades de Técnicos",
            },
        ),
        migrations.RenameIndex(
            model_name="apontamentohoras",
            new_name="service_ord_service_b77a19_idx",
            old_name="so_apon_os_status_idx",
        ),
        migrations.RenameIndex(
            model_name="apontamentohoras",
            new_name="service_ord_tecnico_df4143_idx",
            old_name="so_apon_tecnico_idx",
        ),
        migrations.RenameIndex(
            model_name="osintervencao",
            new_name="service_ord_service_ef97b4_idx",
            old_name="so_osiv_status_idx",
        ),
        migrations.RenameIndex(
            model_name="ositemadicional",
            new_name="service_ord_service_3d5070_idx",
            old_name="so_ositem_status_idx",
        ),
        migrations.AlterField(
            model_name="apontamentohoras",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="apontamentohoras",
            name="horas_apontadas",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Calculado: (encerrado_em - iniciado_em) em horas.",
                max_digits=6,
                verbose_name="Horas apontadas",
            ),
        ),
        migrations.AlterField(
            model_name="osareaimpacto",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="osintervencao",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ositemadicional",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bloqueiocapacidade",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bloqueiocapacidade",
            name="tecnico",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bloqueios",
                to="hr.employee",
                verbose_name="Técnico",
            ),
        ),
        migrations.AddField(
            model_name="capacidadetecnico",
            name="categoria_mao_obra",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="capacidades",
                to="pricing_catalog.categoriamaoobra",
                verbose_name="Categoria de Mão de Obra",
            ),
        ),
        migrations.AddField(
            model_name="capacidadetecnico",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="capacidadetecnico",
            name="tecnico",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="capacidades",
                to="hr.employee",
                verbose_name="Técnico",
            ),
        ),
        migrations.AddIndex(
            model_name="bloqueiocapacidade",
            index=models.Index(
                fields=["tecnico", "data_inicio", "data_fim"], name="service_ord_tecnico_b868d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="capacidadetecnico",
            index=models.Index(
                fields=["tecnico", "vigente_ate"], name="service_ord_tecnico_5c9750_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="capacidadetecnico",
            index=models.Index(
                fields=["categoria_mao_obra"], name="service_ord_categor_eb0ae6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="capacidadetecnico",
            unique_together={("tecnico", "categoria_mao_obra", "vigente_desde")},
        ),
    ]
