# Generated by Django 5.0.10 on 2026-04-22 15:58

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cilia", "0002_import_attempt"),
        ("items", "0003_fix_fk_column_types"),
        ("service_orders", "0020_capacity_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceorder",
            name="previous_status",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Status antes de entrar em 'budget' (auto-Kanban). Restaurado ao aprovar versão.",
                max_length=20,
                verbose_name="Status anterior",
            ),
        ),
        migrations.CreateModel(
            name="ServiceOrderVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("version_number", models.IntegerField(verbose_name="Versão")),
                ("external_version", models.CharField(blank=True, default="", max_length=40)),
                (
                    "external_numero_vistoria",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                (
                    "external_integration_id",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("budget_approval", "Da aprovação de Orçamento"),
                            ("cilia", "Cilia API"),
                            ("hdi", "HDI HTML"),
                            ("xml_porto", "XML Porto"),
                            ("xml_azul", "XML Azul"),
                            ("xml_itau", "XML Itaú"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("approved", "Aprovada"),
                            ("rejected", "Rejeitada"),
                            ("analisado", "Analisado"),
                            ("autorizado", "Autorizado"),
                            ("correcao", "Em Correção"),
                            ("em_analise", "Em Análise"),
                            ("negado", "Negado"),
                            ("superseded", "Superada"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=14),
                ),
                (
                    "discount_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=14),
                ),
                (
                    "net_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=14),
                ),
                (
                    "labor_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=14),
                ),
                (
                    "parts_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=14),
                ),
                (
                    "total_seguradora",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=14),
                ),
                (
                    "total_complemento_particular",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=14),
                ),
                (
                    "total_franquia",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=14),
                ),
                ("content_hash", models.CharField(blank=True, default="", max_length=64)),
                ("raw_payload_s3_key", models.CharField(blank=True, default="", max_length=500)),
                ("hourly_rates", models.JSONField(blank=True, default=dict)),
                (
                    "global_discount_pct",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("created_by", models.CharField(blank=True, default="", max_length=120)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "import_attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cilia.importattempt",
                    ),
                ),
                (
                    "service_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="service_orders.serviceorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Versão de OS",
                "verbose_name_plural": "Versões de OS",
                "ordering": ["-version_number"],
            },
        ),
        migrations.CreateModel(
            name="ServiceOrderParecer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("internal", "Interno DSCar"),
                            ("cilia", "Cilia"),
                            ("hdi", "HDI"),
                            ("xml_porto", "XML Porto"),
                            ("xml_azul", "XML Azul"),
                            ("xml_itau", "XML Itaú"),
                        ],
                        max_length=20,
                    ),
                ),
                ("flow_number", models.IntegerField(blank=True, null=True)),
                ("author_external", models.CharField(blank=True, default="", max_length=120)),
                ("author_org", models.CharField(blank=True, default="", max_length=120)),
                ("author_internal", models.CharField(blank=True, default="", max_length=120)),
                (
                    "parecer_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CONCORDADO", "Concordado"),
                            ("AUTORIZADO", "Autorizado"),
                            ("CORRECAO", "Correção"),
                            ("NEGADO", "Negado"),
                            ("SEM_COBERTURA", "Sem Cobertura"),
                            ("COMENTARIO_INTERNO", "Comentário Interno"),
                        ],
                        default="",
                        max_length=30,
                    ),
                ),
                ("body", models.TextField()),
                ("created_at_external", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "service_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pareceres",
                        to="service_orders.serviceorder",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pareceres",
                        to="service_orders.serviceorderversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parecer de OS",
                "verbose_name_plural": "Pareceres de OS",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceOrderVersionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "bucket",
                    models.CharField(
                        choices=[
                            ("IMPACTO", "Impacto"),
                            ("SEM_COBERTURA", "Sem Cobertura"),
                            ("SOB_ANALISE", "Sob Análise"),
                        ],
                        db_index=True,
                        default="IMPACTO",
                        max_length=20,
                        verbose_name="Bucket",
                    ),
                ),
                (
                    "payer_block",
                    models.CharField(
                        choices=[
                            ("SEGURADORA", "Seguradora"),
                            ("COMPLEMENTO_PARTICULAR", "Complemento Particular"),
                            ("FRANQUIA", "Franquia"),
                            ("PARTICULAR", "Particular"),
                        ],
                        db_index=True,
                        default="PARTICULAR",
                        max_length=30,
                        verbose_name="Bloco Pagador",
                    ),
                ),
                (
                    "impact_area",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        help_text="ID da área de impacto do veículo (ex: capô, porta dianteira esquerda).",
                        null=True,
                        verbose_name="Área de Impacto",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("PART", "Peça"),
                            ("SERVICE", "Serviço"),
                            ("EXTERNAL_SERVICE", "Serviço Externo"),
                            ("FEE", "Taxa"),
                            ("DISCOUNT", "Desconto"),
                        ],
                        default="PART",
                        max_length=20,
                        verbose_name="Tipo de Item",
                    ),
                ),
                ("description", models.CharField(max_length=300, verbose_name="Descrição")),
                (
                    "external_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Código da peça/serviço no sistema da seguradora ou fornecedor.",
                        max_length=60,
                        verbose_name="Código Externo",
                    ),
                ),
                (
                    "part_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GENUINA", "Genuína"),
                            ("ORIGINAL", "Original"),
                            ("OUTRAS_FONTES", "Outras Fontes"),
                            ("VERDE", "Verde (Reciclada)"),
                        ],
                        default="",
                        help_text="Aplicável apenas quando item_type=PART.",
                        max_length=20,
                        verbose_name="Tipo de Peça",
                    ),
                ),
                (
                    "supplier",
                    models.CharField(
                        choices=[("OFICINA", "Oficina"), ("SEGURADORA", "Seguradora")],
                        default="OFICINA",
                        max_length=20,
                        verbose_name="Fornecedor",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("1"),
                        max_digits=10,
                        verbose_name="Quantidade",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="Preço Unitário",
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Custo de aquisição da peça/insumo. Pode ser null para serviços.",
                        max_digits=14,
                        null=True,
                        verbose_name="Custo Unitário",
                    ),
                ),
                (
                    "discount_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Percentual de desconto sobre o preço unitário.",
                        max_digits=5,
                        verbose_name="Desconto (%)",
                    ),
                ),
                (
                    "net_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Preço unitário após desconto × quantidade.",
                        max_digits=14,
                        verbose_name="Preço Líquido",
                    ),
                ),
                (
                    "flag_abaixo_padrao",
                    models.BooleanField(
                        default=False,
                        help_text="Item precificado abaixo da tabela de referência.",
                        verbose_name="Abaixo do Padrão",
                    ),
                ),
                (
                    "flag_acima_padrao",
                    models.BooleanField(
                        default=False,
                        help_text="Item precificado acima da tabela de referência.",
                        verbose_name="Acima do Padrão",
                    ),
                ),
                (
                    "flag_inclusao_manual",
                    models.BooleanField(
                        default=False,
                        help_text="Item incluído manualmente (não gerado pelo motor de orçamento).",
                        verbose_name="Inclusão Manual",
                    ),
                ),
                (
                    "flag_codigo_diferente",
                    models.BooleanField(
                        default=False,
                        help_text="Código do item difere do código da seguradora.",
                        verbose_name="Código Diferente",
                    ),
                ),
                (
                    "flag_servico_manual",
                    models.BooleanField(
                        default=False,
                        help_text="Serviço inserido manualmente sem catálogo canônico.",
                        verbose_name="Serviço Manual",
                    ),
                ),
                (
                    "flag_peca_da_conta",
                    models.BooleanField(
                        default=False,
                        help_text="Peça cujo custo é responsabilidade da seguradora (da conta do sinistro).",
                        verbose_name="Peça da Conta",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Ordem de Exibição")),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="service_orders.serviceorderversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Versão de OS",
                "verbose_name_plural": "Itens de Versão de OS",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ImpactAreaLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("area_number", models.IntegerField()),
                ("label_text", models.CharField(max_length=100)),
                (
                    "service_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="area_labels",
                        to="service_orders.serviceorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Label de Área de Impacto",
                "verbose_name_plural": "Labels de Áreas de Impacto",
                "unique_together": {("service_order", "area_number")},
            },
        ),
        migrations.CreateModel(
            name="ServiceOrderEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("STATUS_CHANGE", "Mudança de status"),
                            ("AUTO_TRANSITION", "Transição automática"),
                            ("VERSION_CREATED", "Nova versão criada"),
                            ("VERSION_APPROVED", "Versão aprovada"),
                            ("VERSION_REJECTED", "Versão rejeitada"),
                            ("ITEM_ADDED", "Item adicionado"),
                            ("ITEM_REMOVED", "Item removido"),
                            ("ITEM_EDITED", "Item editado"),
                            ("IMPORT_RECEIVED", "Importação recebida"),
                            ("PARECER_ADDED", "Parecer adicionado"),
                            ("PHOTO_UPLOADED", "Foto anexada"),
                            ("PHOTO_REMOVED", "Foto removida (soft)"),
                            ("PAYMENT_RECORDED", "Pagamento registrado"),
                            ("FISCAL_ISSUED", "Nota fiscal emitida"),
                            ("SIGNATURE_CAPTURED", "Assinatura capturada"),
                            ("BUDGET_LINKED", "Orçamento aprovado virou OS"),
                            ("COMPLEMENT_ADDED", "Complemento particular adicionado"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("actor", models.CharField(blank=True, default="Sistema", max_length=120)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("from_state", models.CharField(blank=True, default="", max_length=30)),
                ("to_state", models.CharField(blank=True, default="", max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "service_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="service_orders.serviceorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de OS",
                "verbose_name_plural": "Eventos de OS",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["service_order", "-created_at"], name="soe_os_date_idx"),
                    models.Index(fields=["event_type", "-created_at"], name="soe_type_date_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="serviceorderversion",
            index=models.Index(fields=["service_order", "status"], name="sov_os_status_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="serviceorderversion",
            unique_together={("service_order", "version_number")},
        ),
    ]
