# Generated by Django 5.0.10 on 2026-04-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0021_versioning_and_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceorder",
            name="make_logo",
            field=models.URLField(
                blank=True, default="", max_length=500, verbose_name="Logo da montadora"
            ),
        ),
    ]
