# Generated by Django 5.0.10 on 2026-04-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0022_add_make_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceorderphoto",
            name="folder",
            field=models.CharField(
                choices=[
                    ("vistoria_inicial", "Vistoria Inicial"),
                    ("complemento", "Complemento"),
                    ("checklist_entrada", "Checklist de Entrada"),
                    ("checklist_saida", "Checklist de Saída"),
                    ("documentos", "Documentos"),
                    ("orcamentos", "Orçamentos"),
                    ("acompanhamento", "Acompanhamento de Reparos"),
                    ("vistoria_final", "Vistoria Final"),
                    ("pericia", "Perícia"),
                    ("outros", "Outros"),
                    ("financeiro", "Financeiro"),
                ],
                default="vistoria_inicial",
                max_length=30,
                verbose_name="Pasta",
            ),
        ),
    ]
