# Generated by Django 5.0.10 on 2026-04-27 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0023_add_financeiro_folder"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceorderpart",
            name="ncm",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Código NCM 8 dígitos — obrigatório para NF-e",
                max_length=8,
                verbose_name="NCM",
            ),
        ),
    ]
