# Generated by Django 5.0.10 on 2026-05-02 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0024_add_ncm_to_part"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceorderactivitylog",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("created", "OS Aberta"),
                    ("status_changed", "Status Alterado"),
                    ("updated", "Informação Atualizada"),
                    ("customer_updated", "Cliente Atualizado"),
                    ("vehicle_updated", "Veículo Atualizado"),
                    ("schedule_updated", "Datas/Prazo Atualizados"),
                    ("insurer_updated", "Seguradora Atualizada"),
                    ("reminder", "Lembrete Adicionado"),
                    ("file_upload", "Arquivo Anexado"),
                    ("note_added", "Nota Adicionada"),
                    ("budget_snapshot", "Snapshot de Orçamento"),
                    ("cilia_import", "Importação Cilia"),
                    ("delivery", "Entrega ao Cliente"),
                    ("part_added", "Peça Adicionada"),
                    ("part_removed", "Peça Removida"),
                    ("part_updated", "Peça Editada"),
                    ("labor_added", "Serviço Adicionado"),
                    ("labor_removed", "Serviço Removido"),
                    ("labor_updated", "Serviço Editado"),
                    ("invoice_issued", "NF Emitida"),
                    ("document_generated", "Documento Gerado"),
                ],
                max_length=30,
            ),
        ),
    ]
