# Generated by Django 5.0.10 on 2026-05-04 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_nullable_canonica_fks"),
        ("service_orders", "0025_wms_movimentacao_estoque"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceorderpart",
            name="custo_real",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Custo real (valor_nf). PC-6: só preenchido quando peça chega.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="serviceorderpart",
            name="origem",
            field=models.CharField(
                choices=[
                    ("estoque", "Estoque"),
                    ("compra", "Compra"),
                    ("seguradora", "Seguradora"),
                    ("manual", "Manual"),
                ],
                default="manual",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="serviceorderpart",
            name="status_peca",
            field=models.CharField(
                choices=[
                    ("bloqueada", "Bloqueada no estoque"),
                    ("aguardando_cotacao", "Aguardando Cotação"),
                    ("em_cotacao", "Em Cotação"),
                    ("aguardando_aprovacao", "Aguardando Aprovação"),
                    ("comprada", "Comprada — Aguardando Entrega"),
                    ("recebida", "Recebida e Bloqueada"),
                    ("aguardando_seguradora", "Aguardando Seguradora"),
                    ("manual", "Adicionada manualmente"),
                ],
                default="manual",
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="serviceorderpart",
            name="tipo_qualidade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("genuina", "Genuína"),
                    ("reposicao", "Reposição Original"),
                    ("similar", "Similar/Paralela"),
                    ("usada", "Usada/Recondicionada"),
                ],
                default="",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="serviceorderpart",
            name="unidade_fisica",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="os_parts_wms",
                to="inventory.unidadefisica",
            ),
        ),
    ]
