# Generated by Django 5.0.10 on 2026-05-04 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0001_initial"),
        ("service_orders", "0026_parts_wms_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceorderpart",
            name="pedido_compra",
            field=models.ForeignKey(
                blank=True,
                help_text="Pedido de compra quando origem=compra.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="os_parts",
                to="purchasing.pedidocompra",
            ),
        ),
    ]
