# Generated by Django 5.0.10 on 2026-05-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0027_add_pedido_compra_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceorderlabor",
            name="billed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Data do faturamento"),
        ),
        migrations.AddField(
            model_name="serviceorderlabor",
            name="billing_status",
            field=models.CharField(
                choices=[("pending", "Pendente"), ("billed", "Faturado")],
                default="pending",
                max_length=20,
                verbose_name="Status de faturamento",
            ),
        ),
        migrations.AddField(
            model_name="serviceorderlabor",
            name="payer",
            field=models.CharField(
                choices=[("insurer", "Seguradora"), ("customer", "Cliente/Particular")],
                default="insurer",
                max_length=20,
                verbose_name="Pagador",
            ),
        ),
        migrations.AddField(
            model_name="serviceorderlabor",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("import", "Importado"),
                    ("complement", "Complemento Particular"),
                    ("manual", "Manual"),
                ],
                default="manual",
                max_length=20,
                verbose_name="Origem do item",
            ),
        ),
        migrations.AddField(
            model_name="serviceorderpart",
            name="billed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Data do faturamento"),
        ),
        migrations.AddField(
            model_name="serviceorderpart",
            name="billing_status",
            field=models.CharField(
                choices=[("pending", "Pendente"), ("billed", "Faturado")],
                default="pending",
                max_length=20,
                verbose_name="Status de faturamento",
            ),
        ),
        migrations.AddField(
            model_name="serviceorderpart",
            name="payer",
            field=models.CharField(
                choices=[("insurer", "Seguradora"), ("customer", "Cliente/Particular")],
                default="insurer",
                max_length=20,
                verbose_name="Pagador",
            ),
        ),
        migrations.AddField(
            model_name="serviceorderpart",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("import", "Importado"),
                    ("complement", "Complemento Particular"),
                    ("manual", "Manual"),
                ],
                default="manual",
                max_length=20,
                verbose_name="Origem do item",
            ),
        ),
    ]
