# Generated by Django 5.0.10 on 2026-05-08 18:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0028_add_payer_source_billing"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceorderevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("STATUS_CHANGE", "Mudança de status"),
                    ("AUTO_TRANSITION", "Transição automática"),
                    ("VERSION_CREATED", "Nova versão criada"),
                    ("VERSION_APPROVED", "Versão aprovada"),
                    ("VERSION_REJECTED", "Versão rejeitada"),
                    ("ITEM_ADDED", "Item adicionado"),
                    ("ITEM_REMOVED", "Item removido"),
                    ("ITEM_EDITED", "Item editado"),
                    ("IMPORT_RECEIVED", "Importação recebida"),
                    ("PARECER_ADDED", "Parecer adicionado"),
                    ("PHOTO_UPLOADED", "Foto anexada"),
                    ("PHOTO_REMOVED", "Foto removida (soft)"),
                    ("PAYMENT_RECORDED", "Pagamento registrado"),
                    ("FISCAL_ISSUED", "Nota fiscal emitida"),
                    ("SIGNATURE_CAPTURED", "Assinatura capturada"),
                    ("BUDGET_LINKED", "Orçamento aprovado virou OS"),
                    ("COMPLEMENT_ADDED", "Complemento particular adicionado"),
                    ("OVERRIDE_REQUESTED", "Override solicitado"),
                    ("OVERRIDE_APPROVED", "Override aprovado"),
                    ("OVERRIDE_REJECTED", "Override rejeitado"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="TransitionOverrideRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("from_status", models.CharField(max_length=20, verbose_name="Status atual")),
                ("to_status", models.CharField(max_length=20, verbose_name="Status desejado")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("approved", "Aprovado"),
                            ("rejected", "Rejeitado"),
                            ("expired", "Expirado"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "blocks_snapshot",
                    models.JSONField(
                        default=list, help_text="Soft blocks no momento da solicitação"
                    ),
                ),
                ("request_reason", models.TextField(verbose_name="Motivo da solicitação")),
                (
                    "justification",
                    models.TextField(
                        blank=True, default="", verbose_name="Justificativa do gerente"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Resolvido em"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expira em")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="override_requests_resolved",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Resolvido por",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="override_requests_made",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Solicitado por",
                    ),
                ),
                (
                    "service_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="override_requests",
                        to="service_orders.serviceorder",
                        verbose_name="OS",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitação de Override",
                "verbose_name_plural": "Solicitações de Override",
                "db_table": "service_orders_override_request",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["service_order", "status"], name="service_ord_service_fa6d4d_idx"
                    ),
                    models.Index(
                        fields=["status", "expires_at"], name="service_ord_status_48d1f3_idx"
                    ),
                ],
            },
        ),
    ]
