# Generated by Django 5.0.10 on 2026-05-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0029_transition_override_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceorder",
            name="authorization_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Data/hora de autorização do orçamento pela SEGURADORA. Usado pelo TransitionValidator (AUTH_DATE_SET) para liberar a transição waiting_auth → authorized. Não confundir com service_authorization_date (particular).",
                null=True,
                verbose_name="Data de autorização (seguradora)",
            ),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="service_authorization_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Data/hora de autorização do serviço pelo CLIENTE PARTICULAR. Preenchido quando o cliente aprova o orçamento. Não confundir com authorization_date (seguradora).",
                null=True,
                verbose_name="Autorização do serviço (particular)",
            ),
        ),
    ]
