# Generated by Django 5.0.10 on 2026-06-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0030_alter_serviceorder_authorization_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='external_invoice_date',
            field=models.DateField(blank=True, help_text='Data da NF emitida fora do sistema.', null=True, verbose_name='Data NF externa'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='external_invoice_number',
            field=models.CharField(blank=True, default='', help_text='Número da NF emitida fora do sistema (uso temporário enquanto Focus não está disponível). Quando preenchido junto com external_invoice_date, a OS é considerada faturada para fins de fechamento.', max_length=50, verbose_name='Nº NF externa'),
        ),
    ]
