# Generated by Django 5.0.10 on 2026-07-10 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0014_cleanup_dead_apps"),
        ("service_orders", "0034_add_total_seguradora_oficial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apontamentohoras",
            name="client_uuid",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="UUID v7 gerado no cliente — idempotência do sync offline (PWA onda 5)",
                max_length=36,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="client_uuid",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="UUID v7 gerado no cliente — idempotência do sync offline (PWA onda 5)",
                max_length=36,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="serviceorderpart",
            name="client_uuid",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="UUID v7 gerado no cliente — idempotência do sync offline (PWA onda 5)",
                max_length=36,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="serviceorderphoto",
            name="client_uuid",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="UUID v7 gerado no cliente — idempotência do sync offline (PWA onda 5)",
                max_length=36,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="expert",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"roles__role": "EXPERT"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service_orders_as_expert",
                to="persons.person",
                verbose_name="Perito",
            ),
        ),
    ]
