# Generated by Django 5.0.10 on 2026-07-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0035_apontamentohoras_client_uuid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceorderlabor",
            name="client_uuid",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="UUID v7 gerado no cliente — idempotência do sync offline (PWA onda 5)",
                max_length=36,
                null=True,
                unique=True,
            ),
        ),
    ]
