# Generated by Django 5.0.10 on 2026-04-17 19:20

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pricing_catalog", "0001_initial"),
        ("pricing_profile", "0002_enquadramento_faltante"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustoHoraFallback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("vigente_desde", models.DateField(verbose_name="Vigente desde")),
                (
                    "vigente_ate",
                    models.DateField(blank=True, null=True, verbose_name="Vigente até"),
                ),
                (
                    "valor_hora",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(Decimal("1.0"))],
                        verbose_name="Valor por hora (R$)",
                    ),
                ),
                (
                    "motivo",
                    models.CharField(
                        blank=True,
                        help_text="Razão para uso do fallback (ex: 'aguardando integração RH').",
                        max_length=200,
                        verbose_name="Motivo",
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fallbacks_custo_hora",
                        to="pricing_catalog.categoriamaoobra",
                        verbose_name="Categoria de mão de obra",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="custos_hora_fallback",
                        to="pricing_profile.empresa",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Custo Hora Fallback",
                "verbose_name_plural": "Custos Hora Fallback",
                "indexes": [
                    models.Index(
                        fields=["empresa", "categoria", "vigente_desde"],
                        name="pricing_eng_empresa_ed31a5_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ParametroCustoHora",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("vigente_desde", models.DateField(verbose_name="Vigente desde")),
                (
                    "vigente_ate",
                    models.DateField(blank=True, null=True, verbose_name="Vigente até"),
                ),
                (
                    "provisao_13_ferias",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.1389"),
                        help_text="Provisão de 13º + férias como fração do bruto. Padrão: 0.1389 (13.89%)",
                        max_digits=5,
                        verbose_name="Provisão 13º + férias",
                    ),
                ),
                (
                    "multa_fgts_rescisao",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0320"),
                        help_text="Multa FGTS rescisão como fração. Padrão: 0.0320 (3.20%)",
                        max_digits=5,
                        verbose_name="Multa FGTS rescisão",
                    ),
                ),
                (
                    "beneficios_por_funcionario",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="VT + VA + plano de saúde etc por funcionário/mês em R$.",
                        max_digits=10,
                        verbose_name="Benefícios por funcionário (R$)",
                    ),
                ),
                (
                    "horas_produtivas_mes",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("168.00"),
                        help_text="Horas produtivas individuais por mês. Padrão: 168h (8h × 21 dias).",
                        max_digits=6,
                        verbose_name="Horas produtivas individuais/mês",
                    ),
                ),
                ("observacoes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parametros_custo_hora",
                        to="pricing_profile.empresa",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parâmetro de Custo Hora",
                "verbose_name_plural": "Parâmetros de Custo Hora",
                "indexes": [
                    models.Index(
                        fields=["empresa", "vigente_desde"], name="pricing_eng_empresa_eae7e6_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ParametroRateio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("vigente_desde", models.DateField(verbose_name="Vigente desde")),
                (
                    "vigente_ate",
                    models.DateField(blank=True, null=True, verbose_name="Vigente até"),
                ),
                (
                    "horas_produtivas_mes",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Horas produtivas totais da oficina no mês. Default conservador: 168h.",
                        max_digits=7,
                        validators=[django.core.validators.MinValueValidator(Decimal("1.0"))],
                        verbose_name="Horas produtivas/mês",
                    ),
                ),
                (
                    "metodo",
                    models.CharField(
                        choices=[
                            ("por_hora", "Por hora produtiva"),
                            ("por_os", "Por OS concluída"),
                        ],
                        default="por_hora",
                        max_length=20,
                        verbose_name="Método de rateio",
                    ),
                ),
                ("observacoes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parametros_rateio",
                        to="pricing_profile.empresa",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parâmetro de Rateio",
                "verbose_name_plural": "Parâmetros de Rateio",
                "indexes": [
                    models.Index(
                        fields=["empresa", "vigente_desde"], name="pricing_eng_empresa_af717d_idx"
                    )
                ],
            },
        ),
    ]
