# Generated by Django 5.0.10 on 2026-04-19 23:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing_catalog", "0001_initial"),
        ("pricing_engine", "0004_snapshot_fk_no_db_constraint"),
        ("pricing_profile", "0002_enquadramento_faltante"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditoriaMotor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "operacao",
                    models.CharField(
                        choices=[
                            ("calcular_servico", "Calcular Serviço"),
                            ("calcular_peca", "Calcular Peça"),
                            ("simular", "Simular Composição"),
                            ("benchmark_check", "Verificação Benchmark"),
                        ],
                        max_length=30,
                        verbose_name="Operação",
                    ),
                ),
                ("empresa_id", models.UUIDField(blank=True, null=True, verbose_name="Empresa ID")),
                (
                    "contexto_input",
                    models.JSONField(
                        help_text="Parâmetros passados ao motor (servico_id, segmento, tamanho, etc.).",
                        verbose_name="Contexto de entrada",
                    ),
                ),
                (
                    "resultado_output",
                    models.JSONField(
                        blank=True,
                        help_text="DTO retornado pelo motor (preço, margens, custos).",
                        null=True,
                        verbose_name="Resultado de saída",
                    ),
                ),
                ("sucesso", models.BooleanField(default=True, verbose_name="Sucesso")),
                ("erro_msg", models.TextField(blank=True, verbose_name="Mensagem de erro")),
                ("tempo_ms", models.IntegerField(default=0, verbose_name="Tempo de resposta (ms)")),
                (
                    "snapshot_id",
                    models.UUIDField(
                        blank=True,
                        help_text="FK lógica para CalculoCustoSnapshot gerado nesta chamada.",
                        null=True,
                        verbose_name="Snapshot ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Auditoria do Motor",
                "verbose_name_plural": "Auditorias do Motor",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="markuppeca",
            name="markup_peca_ou_faixa",
        ),
        migrations.RenameIndex(
            model_name="calculocustosnapshot",
            new_name="pricing_eng_empresa_ba2be2_idx",
            old_name="pricing_eng_snap_servico_idx",
        ),
        migrations.RenameIndex(
            model_name="calculocustosnapshot",
            new_name="pricing_eng_empresa_4150e2_idx",
            old_name="pricing_eng_snap_peca_idx",
        ),
        migrations.RenameIndex(
            model_name="calculocustosnapshot",
            new_name="pricing_eng_origem_dde7e4_idx",
            old_name="pricing_eng_snap_origem_idx",
        ),
        migrations.RenameIndex(
            model_name="margemoperacao",
            new_name="pricing_eng_empresa_8f8565_idx",
            old_name="pricing_eng_empresa_segmento_tipo_idx",
        ),
        migrations.RenameIndex(
            model_name="markuppeca",
            new_name="pricing_eng_empresa_0eb8fd_idx",
            old_name="pricing_eng_markup_empresa_idx",
        ),
        migrations.AlterField(
            model_name="calculocustosnapshot",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="calculocustosnapshot",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="calculocustosnapshot",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="margemoperacao",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="margemoperacao",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="margemoperacao",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="markuppeca",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="markuppeca",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="markuppeca",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddConstraint(
            model_name="markuppeca",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("faixa_custo_min__isnull", True), ("peca_canonica__isnull", False)),
                    models.Q(("faixa_custo_min__isnull", False), ("peca_canonica__isnull", True)),
                    _connector="OR",
                ),
                name="markup_peca_ou_faixa",
            ),
        ),
        migrations.AddField(
            model_name="auditoriamotor",
            name="chamado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="auditorias_motor",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Chamado por",
            ),
        ),
        migrations.AddField(
            model_name="auditoriamotor",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="auditoriamotor",
            index=models.Index(
                fields=["operacao", "-created_at"], name="pricing_eng_operaca_39b006_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditoriamotor",
            index=models.Index(
                fields=["empresa_id", "-created_at"], name="pricing_eng_empresa_180210_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditoriamotor",
            index=models.Index(
                fields=["sucesso", "-created_at"], name="pricing_eng_sucesso_128511_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditoriamotor",
            index=models.Index(fields=["snapshot_id"], name="pricing_eng_snapsho_41b73b_idx"),
        ),
    ]
