# Generated by Django 5.0.10 on 2026-04-17 21:12

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pricing_catalog", "0001_initial"),
        ("pricing_profile", "0002_enquadramento_faltante"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FichaTecnicaServico",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "versao",
                    models.PositiveIntegerField(
                        help_text="Incrementado a cada revisão da ficha. Nunca reutilizar.",
                        verbose_name="Versão",
                    ),
                ),
                ("criada_em", models.DateTimeField(auto_now_add=True, verbose_name="Criada em")),
                ("observacoes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "motivo_nova_versao",
                    models.CharField(
                        blank=True,
                        help_text="Descreve por que esta versão foi criada (ex: 'ajuste de tempo após treinamento').",
                        max_length=300,
                        verbose_name="Motivo da nova versão",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "criada_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fichas_tecnicas_criadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criada por",
                    ),
                ),
                (
                    "servico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fichas",
                        to="pricing_catalog.servicocanonico",
                        verbose_name="Serviço canônico",
                    ),
                ),
                (
                    "tipo_pintura",
                    models.ForeignKey(
                        blank=True,
                        help_text="Opcional — ficha distinta por tipo de pintura. NULL = genérica.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fichas_tecnicas",
                        to="pricing_profile.tipopintura",
                        verbose_name="Tipo de pintura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ficha Técnica de Serviço",
                "verbose_name_plural": "Fichas Técnicas de Serviços",
            },
        ),
        migrations.CreateModel(
            name="FichaTecnicaMaoObra",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "horas",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Horas de mão de obra desta categoria para executar o serviço.",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="Horas",
                    ),
                ),
                (
                    "afetada_por_tamanho",
                    models.BooleanField(
                        default=True,
                        help_text="TRUE para mão de obra que varia com porte (pintura, funilaria). FALSE para elétrica/diagnóstico/configuração.",
                        verbose_name="Afetada por tamanho",
                    ),
                ),
                (
                    "observacao",
                    models.CharField(blank=True, max_length=200, verbose_name="Observação"),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fichas_mao_obra",
                        to="pricing_catalog.categoriamaoobra",
                        verbose_name="Categoria de mão de obra",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ficha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maos_obra",
                        to="pricing_tech.fichatecnicaservico",
                        verbose_name="Ficha técnica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mão de Obra da Ficha Técnica",
                "verbose_name_plural": "Mãos de Obra das Fichas Técnicas",
            },
        ),
        migrations.CreateModel(
            name="FichaTecnicaInsumo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "quantidade",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Quantidade do material necessária para executar o serviço.",
                        max_digits=9,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.0001"))],
                        verbose_name="Quantidade",
                    ),
                ),
                (
                    "unidade",
                    models.CharField(
                        help_text="Deve corresponder à unidade_base do material canônico.",
                        max_length=20,
                        verbose_name="Unidade",
                    ),
                ),
                (
                    "afetado_por_tamanho",
                    models.BooleanField(
                        default=True,
                        help_text="TRUE para insumos que variam com porte (tinta, massa). FALSE para itens fixos (esponja, lixa).",
                        verbose_name="Afetado por tamanho",
                    ),
                ),
                (
                    "observacao",
                    models.CharField(blank=True, max_length=200, verbose_name="Observação"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "material_canonico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fichas_insumo",
                        to="pricing_catalog.materialcanonico",
                        verbose_name="Material canônico",
                    ),
                ),
                (
                    "ficha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insumos",
                        to="pricing_tech.fichatecnicaservico",
                        verbose_name="Ficha técnica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Insumo da Ficha Técnica",
                "verbose_name_plural": "Insumos das Fichas Técnicas",
            },
        ),
        migrations.AddIndex(
            model_name="fichatecnicaservico",
            index=models.Index(
                fields=["servico", "is_active", "tipo_pintura"], name="pt_ficha_servico_ativo_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fichatecnicaservico",
            unique_together={("servico", "versao", "tipo_pintura")},
        ),
    ]
