# Generated by Django 5.0.10 on 2026-04-19 23:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing_tech", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VarianciaFicha",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "servico_canonico_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="UUID do ServicoCanonico (sem FK para suportar mudanças de catálogo).",
                        verbose_name="ID Serviço Canônico",
                    ),
                ),
                (
                    "mes_referencia",
                    models.DateField(
                        help_text="Primeiro dia do mês ao qual a variância se refere.",
                        verbose_name="Mês de referência",
                    ),
                ),
                ("qtd_os", models.IntegerField(default=0, verbose_name="Qtd OS amostradas")),
                (
                    "horas_estimadas_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Horas estimadas (total)",
                    ),
                ),
                (
                    "horas_realizadas_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Horas realizadas (total)",
                    ),
                ),
                (
                    "variancia_horas_pct",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="(realizadas - estimadas) / estimadas. Negativo = mais rápido que o estimado.",
                        max_digits=7,
                        verbose_name="Variância horas (%)",
                    ),
                ),
                (
                    "custo_insumo_estimado",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Custo insumo estimado",
                    ),
                ),
                (
                    "custo_insumo_realizado",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Custo insumo realizado",
                    ),
                ),
                (
                    "variancia_insumo_pct",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=7,
                        verbose_name="Variância insumo (%)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Variância de Ficha Técnica",
                "verbose_name_plural": "Variâncias de Ficha Técnica",
                "indexes": [
                    models.Index(fields=["mes_referencia"], name="pricing_tec_mes_ref_786d6d_idx"),
                    models.Index(
                        fields=["variancia_horas_pct"], name="pricing_tec_varianc_8317bb_idx"
                    ),
                ],
                "unique_together": {("servico_canonico_id", "mes_referencia")},
            },
        ),
        migrations.CreateModel(
            name="VarianciaPecaCusto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "peca_canonica_id",
                    models.UUIDField(db_index=True, verbose_name="ID Peça Canônica"),
                ),
                ("mes_referencia", models.DateField(verbose_name="Mês de referência")),
                ("qtd_amostras", models.IntegerField(default=0, verbose_name="Amostras")),
                (
                    "custo_snapshot_medio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Custo snapshot médio",
                    ),
                ),
                (
                    "custo_nfe_medio",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=14, verbose_name="Custo NF-e médio"
                    ),
                ),
                (
                    "variancia_pct",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=7, verbose_name="Variância (%)"
                    ),
                ),
                (
                    "alerta",
                    models.BooleanField(
                        default=False,
                        help_text="True quando |variancia_pct| > 0.15 (15%).",
                        verbose_name="Alerta",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Variância de Custo de Peça",
                "verbose_name_plural": "Variâncias de Custo de Peças",
                "indexes": [
                    models.Index(
                        fields=["mes_referencia", "alerta"], name="pricing_tec_mes_ref_241795_idx"
                    )
                ],
                "unique_together": {("peca_canonica_id", "mes_referencia")},
            },
        ),
    ]
