# Generated by Django 5.0.10 on 2026-05-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_globaluser_push_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="globaluser",
            name="username",
            field=models.CharField(
                blank=True,
                help_text="Gerado automaticamente na admissão: primeiro.ultimo",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Login do colaborador",
            ),
        ),
    ]
