# Generated by Django 5.0.10 on 2026-05-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signatures", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signature",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("BUDGET_APPROVAL", "Aprovação de Orçamento"),
                    ("OS_OPEN", "Recepção do Veículo"),
                    ("OS_DELIVERY", "Entrega do Veículo"),
                    ("COMPLEMENT_APPROVAL", "Aprovação de Complemento"),
                    ("INSURANCE_ACCEPTANCE", "Aceite da Seguradora"),
                    ("VISTORIA_ENTRADA", "Vistoria de Entrada"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
    ]
