# Generated by Django 5.0.10 on 2026-07-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signatures", "0002_add_vistoria_entrada_doctype"),
    ]

    operations = [
        migrations.AddField(
            model_name="signature",
            name="client_uuid",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="UUID v7 gerado no cliente — idempotência do sync offline (PWA onda 5)",
                max_length=36,
                null=True,
                unique=True,
            ),
        ),
    ]
