# Generated by Django 5.0.10 on 2026-07-23 02:03

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("signatures", "0003_signature_client_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signature",
            name="signer_cpf",
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default=""),
        ),
    ]
