# Generated by Django 5.0.10 on 2026-05-14 19:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vehicle_catalog", "0005_alter_platecache_fetched_at_alter_platecache_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Slug uppercase: CARROCERIA, ILUMINACAO, etc.",
                        max_length=30,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Nome")),
                ("description", models.TextField(blank=True, default="", verbose_name="Descrição")),
                ("order", models.PositiveSmallIntegerField(default=100, verbose_name="Ordem")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "Categoria de Peça",
                "verbose_name_plural": "Categorias de Peças",
                "db_table": "parts_catalog_category",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PartReference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "manufacturer_code",
                    models.CharField(
                        db_index=True,
                        help_text="Part number único do fabricante (ex: 52058207, 5U0941005D).",
                        max_length=60,
                        unique=True,
                        verbose_name="Código do fabricante",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=300, verbose_name="Descrição normalizada"),
                ),
                (
                    "description_original",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="Descrição original (legado)",
                    ),
                ),
                (
                    "ncm",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Código NCM 8 dígitos — obrigatório para NF-e.",
                        max_length=8,
                        verbose_name="NCM",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="PC",
                        help_text="PC, UN, LT, JG, KT, etc.",
                        max_length=10,
                        verbose_name="Unidade",
                    ),
                ),
                (
                    "ean",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=14,
                        verbose_name="EAN/GTIN",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parts",
                        to="parts_catalog.partcategory",
                        verbose_name="Categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Referência de Peça",
                "verbose_name_plural": "Referências de Peças",
                "db_table": "parts_catalog_reference",
                "ordering": ["description"],
            },
        ),
        migrations.CreateModel(
            name="PartApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "year_start",
                    models.IntegerField(blank=True, null=True, verbose_name="Ano início"),
                ),
                ("year_end", models.IntegerField(blank=True, null=True, verbose_name="Ano fim")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("seed", "Seed (legado)"),
                            ("os_auto", "Automático (OS)"),
                            ("api_external", "API Externa"),
                            ("manual", "Manual"),
                        ],
                        default="manual",
                        max_length=15,
                        verbose_name="Origem",
                    ),
                ),
                (
                    "confidence_score",
                    models.PositiveSmallIntegerField(
                        default=50,
                        help_text="0-100. seed=50, api=80, os_auto=90, manual=100.",
                        verbose_name="Confiança (%)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "make",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="part_applications",
                        to="vehicle_catalog.vehiclemake",
                        verbose_name="Marca",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null = compatível com todos os modelos da marca.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="part_applications",
                        to="vehicle_catalog.vehiclemodel",
                        verbose_name="Modelo",
                    ),
                ),
                (
                    "part_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="parts_catalog.partreference",
                        verbose_name="Peça",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aplicação Veicular",
                "verbose_name_plural": "Aplicações Veiculares",
                "db_table": "parts_catalog_application",
                "ordering": ["-confidence_score", "make__nome"],
            },
        ),
        migrations.CreateModel(
            name="PartSupplierRef",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "supplier_name",
                    models.CharField(
                        help_text="Nome normalizado (ex: PMZ DISTRIBUIDORA, FORTBRAS).",
                        max_length=200,
                        verbose_name="Nome do fornecedor",
                    ),
                ),
                (
                    "supplier_code",
                    models.CharField(
                        blank=True, default="", max_length=60, verbose_name="Código no fornecedor"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "part_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suppliers",
                        to="parts_catalog.partreference",
                        verbose_name="Peça",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fornecedor de Referência",
                "verbose_name_plural": "Fornecedores de Referência",
                "db_table": "parts_catalog_supplier_ref",
                "ordering": ["supplier_name"],
            },
        ),
        migrations.AddIndex(
            model_name="partreference",
            index=models.Index(fields=["category", "is_active"], name="idx_partref_cat_active"),
        ),
        migrations.AddConstraint(
            model_name="partapplication",
            constraint=models.UniqueConstraint(
                fields=("part_ref", "make", "model", "source"),
                name="uq_part_app_ref_make_model_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="partsupplierref",
            constraint=models.UniqueConstraint(
                fields=("part_ref", "supplier_name"), name="uq_part_supplier_ref_name"
            ),
        ),
    ]
