# Generated by Django 5.0.10 on 2026-04-16 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle_catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleMake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("fipe_id", models.CharField(db_index=True, max_length=10, unique=True)),
                ("nome", models.CharField(db_index=True, max_length=80, unique=True)),
                (
                    "nome_normalizado",
                    models.CharField(
                        db_index=True,
                        help_text="Nome em lowercase sem acentos — usado para fuzzy match e aliases.",
                        max_length=80,
                    ),
                ),
            ],
            options={
                "verbose_name": "Marca (FIPE)",
                "verbose_name_plural": "Marcas (FIPE)",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="VehicleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("fipe_id", models.CharField(db_index=True, max_length=10)),
                ("nome", models.CharField(db_index=True, max_length=120)),
                ("nome_normalizado", models.CharField(db_index=True, max_length=120)),
                (
                    "marca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modelos",
                        to="vehicle_catalog.vehiclemake",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modelo (FIPE)",
                "verbose_name_plural": "Modelos (FIPE)",
                "ordering": ["nome"],
                "unique_together": {("marca", "fipe_id")},
            },
        ),
        migrations.CreateModel(
            name="VehicleYearVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("fipe_id", models.CharField(db_index=True, max_length=20)),
                ("ano", models.IntegerField(db_index=True)),
                (
                    "combustivel",
                    models.CharField(
                        help_text="gasolina | flex | diesel | eletrico", max_length=20
                    ),
                ),
                ("descricao", models.CharField(max_length=200)),
                ("codigo_fipe", models.CharField(blank=True, db_index=True, max_length=20)),
                (
                    "valor_referencia",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "modelo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versoes",
                        to="vehicle_catalog.vehiclemodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Versão/Ano (FIPE)",
                "verbose_name_plural": "Versões/Anos (FIPE)",
                "ordering": ["ano"],
                "unique_together": {("modelo", "fipe_id")},
            },
        ),
    ]
