# Generated by Django 5.0.10 on 2026-05-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle_catalog", "0004_platecache_version_engine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platecache",
            name="fetched_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="platecache",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="platecache",
            name="raw_response",
            field=models.JSONField(default=dict, help_text="Resposta bruta da API para auditoria."),
        ),
    ]
