# Generated by Django 5.0.10 on 2026-07-22 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle_catalog", "0005_alter_platecache_fetched_at_alter_platecache_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiclemake",
            name="logo_url",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="URL do logo"
            ),
        ),
    ]
