# Generated by Django 5.0.10 on 2026-04-28 19:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts_receivable', '0003_fiscal_document_fk'),
        ('service_orders', '0024_add_ncm_to_part'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentGeneration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('document_type', models.CharField(choices=[('os_report', 'Ordem de Serviço'), ('warranty', 'Termo de Garantia'), ('settlement', 'Termo de Quitação'), ('receipt', 'Recibo de Pagamento')], max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('data_snapshot', models.JSONField(help_text='Dados completos no momento da geração. Permite regerar PDF idêntico.')),
                ('s3_key', models.CharField(max_length=500)),
                ('file_size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents_generated', to=settings.AUTH_USER_MODEL)),
                ('receivable', models.ForeignKey(blank=True, help_text='Apenas para recibos', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts_receivable.receivabledocument')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='service_orders.serviceorder')),
            ],
            options={
                'verbose_name': 'Documento Gerado',
                'verbose_name_plural': 'Documentos Gerados',
                'db_table': 'documents_generation',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['service_order', 'document_type', '-version'], name='idx_doc_so_type_ver')],
            },
        ),
        migrations.AddConstraint(
            model_name='documentgeneration',
            constraint=models.UniqueConstraint(fields=('service_order', 'document_type', 'version'), name='unique_doc_version'),
        ),
    ]
