# Generated by Django 5.0 — Motor de Orçamentos MO-7

import django.db.models.deletion
import uuid

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0003_globaluser_push_token"),
        ("customers", "0004_address_split"),
        ("insurers", "0003_insurer_logo_url"),
        ("pricing_catalog", "0001_initial"),
        ("pricing_engine", "0004_snapshot_fk_no_db_constraint"),
        ("pricing_profile", "0001_initial"),
        ("pricing_tech", "0001_initial"),
        ("service_orders", "0018_vehicle_profile_snapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="Orcamento",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("numero", models.CharField(max_length=20, verbose_name="Número")),
                ("versao", models.PositiveIntegerField(default=1, verbose_name="Versão")),
                ("tipo_responsabilidade", models.CharField(
                    choices=[("cliente", "Cliente"), ("seguradora", "Seguradora"), ("rcf", "RCF — responsabilidade de terceiros")],
                    default="cliente",
                    max_length=20,
                    verbose_name="Tipo de responsabilidade",
                )),
                ("sinistro_numero", models.CharField(blank=True, max_length=40, verbose_name="Número do sinistro")),
                ("veiculo_marca", models.CharField(max_length=60, verbose_name="Marca")),
                ("veiculo_modelo", models.CharField(max_length=100, verbose_name="Modelo")),
                ("veiculo_ano", models.PositiveIntegerField(verbose_name="Ano")),
                ("veiculo_versao", models.CharField(blank=True, max_length=60, verbose_name="Versão")),
                ("veiculo_placa", models.CharField(blank=True, max_length=10, verbose_name="Placa")),
                ("enquadramento_snapshot", models.JSONField(
                    help_text="{segmento_codigo, tamanho_codigo, fator_resp, tipo_pintura_codigo}",
                    verbose_name="Enquadramento snapshot",
                )),
                ("status", models.CharField(
                    choices=[
                        ("rascunho", "Rascunho"),
                        ("enviado", "Enviado ao cliente"),
                        ("aprovado", "Aprovado"),
                        ("aprovado_parc", "Aprovação parcial"),
                        ("recusado", "Recusado"),
                        ("expirado", "Expirado"),
                        ("convertido_os", "Convertido em OS"),
                    ],
                    default="rascunho",
                    max_length=20,
                )),
                ("validade", models.DateField(verbose_name="Válido até")),
                ("enviado_em", models.DateTimeField(blank=True, null=True, verbose_name="Enviado em")),
                ("aprovado_em", models.DateTimeField(blank=True, null=True, verbose_name="Aprovado em")),
                ("subtotal", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("desconto", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("total", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("observacoes", models.TextField(blank=True, verbose_name="Observações")),
                ("created_by", models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    to=settings.AUTH_USER_MODEL,
                    related_name="+",
                )),
                ("empresa", models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name="orcamentos",
                    to="pricing_profile.empresa",
                    verbose_name="Empresa",
                )),
                ("customer", models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name="orcamentos",
                    to="customers.unifiedcustomer",
                    verbose_name="Cliente",
                )),
                ("insurer", models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name="orcamentos",
                    to="insurers.insurer",
                    verbose_name="Seguradora",
                )),
                ("service_order", models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name="orcamentos",
                    to="service_orders.serviceorder",
                    verbose_name="OS gerada",
                )),
            ],
            options={
                "verbose_name": "Orçamento",
                "verbose_name_plural": "Orçamentos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="orcamento",
            index=models.Index(fields=["empresa", "status", "-created_at"], name="quotes_orc_empresa_status_idx"),
        ),
        migrations.AddIndex(
            model_name="orcamento",
            index=models.Index(fields=["customer", "-created_at"], name="quotes_orc_customer_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="orcamento",
            unique_together={("empresa", "numero", "versao")},
        ),

        migrations.CreateModel(
            name="AreaImpacto",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("titulo", models.CharField(max_length=120, verbose_name="Título")),
                ("ordem", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(
                    choices=[
                        ("aberta", "Aberta"),
                        ("aprovada", "Aprovada"),
                        ("negada_pre_exist", "Negada — pré-existência"),
                        ("parcial", "Parcial"),
                        ("cancelada", "Cancelada"),
                    ],
                    default="aberta",
                    max_length=20,
                )),
                ("observacao_regulador", models.TextField(blank=True, verbose_name="Observação do regulador")),
                ("created_by", models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    to=settings.AUTH_USER_MODEL,
                    related_name="+",
                )),
                ("orcamento", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="areas",
                    to="quotes.orcamento",
                    verbose_name="Orçamento",
                )),
            ],
            options={
                "verbose_name": "Área de Impacto",
                "verbose_name_plural": "Áreas de Impacto",
                "ordering": ["ordem"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="areaimpacto",
            unique_together={("orcamento", "titulo")},
        ),

        migrations.CreateModel(
            name="OrcamentoIntervencao",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("acao", models.CharField(
                    choices=[
                        ("trocar", "Trocar"),
                        ("reparar", "Reparar"),
                        ("pintar", "Pintar"),
                        ("remocao_instalacao", "Remoção e instalação"),
                    ],
                    max_length=20,
                    verbose_name="Ação",
                )),
                ("qualificador_peca", models.CharField(
                    blank=True,
                    choices=[("PPO", "Peça Original (PPO)"), ("PRO", "Peça Recondicionada Original (PRO)"), ("PR", "Peça de Reposição (PR)"), ("PREC", "Peça Recondicionada (PREC)")],
                    max_length=10,
                    verbose_name="Qualificador de peça",
                )),
                ("fornecimento", models.CharField(
                    choices=[("oficina", "Oficina"), ("seguradora", "Seguradora"), ("cliente", "Cliente")],
                    default="oficina",
                    max_length=20,
                    verbose_name="Fornecimento",
                )),
                ("codigo_peca", models.CharField(blank=True, max_length=60, verbose_name="Código da peça")),
                ("horas_mao_obra", models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name="Horas MO")),
                ("valor_peca", models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name="Valor da peça")),
                ("valor_mao_obra", models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name="Valor MO")),
                ("valor_insumos", models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name="Valor insumos")),
                ("preco_total", models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name="Preço total")),
                ("status", models.CharField(
                    choices=[
                        ("orcado", "Orçado"),
                        ("aprovado", "Aprovado"),
                        ("sem_cobertura", "Sem cobertura"),
                        ("sob_analise", "Sob análise"),
                        ("executado", "Executado"),
                        ("cancelado", "Cancelado"),
                    ],
                    default="orcado",
                    max_length=20,
                    verbose_name="Status Cilia",
                )),
                ("abaixo_padrao", models.BooleanField(default=False)),
                ("acima_padrao", models.BooleanField(default=False)),
                ("inclusao_manual", models.BooleanField(default=False)),
                ("codigo_diferente", models.BooleanField(default=False)),
                ("quantidade", models.PositiveIntegerField(default=1)),
                ("ordem", models.PositiveIntegerField(default=0)),
                ("descricao_visivel", models.CharField(blank=True, max_length=300)),
                ("observacao", models.TextField(blank=True)),
                ("created_by", models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    to=settings.AUTH_USER_MODEL,
                    related_name="+",
                )),
                ("orcamento", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="intervencoes",
                    to="quotes.orcamento",
                    verbose_name="Orçamento",
                )),
                ("area_impacto", models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name="intervencoes",
                    to="quotes.areaimpacto",
                    verbose_name="Área de impacto",
                )),
                ("peca_canonica", models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    to="pricing_catalog.pecacanonica",
                    verbose_name="Peça canônica",
                )),
                ("servico_canonico", models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    to="pricing_catalog.servicocanonico",
                    verbose_name="Serviço canônico",
                )),
                ("ficha_tecnica", models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    to="pricing_tech.fichatecnicaservico",
                    verbose_name="Ficha técnica",
                )),
                ("snapshot", models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name="intervencoes",
                    to="pricing_engine.calculocustosnapshot",
                    verbose_name="Snapshot de custo",
                )),
            ],
            options={
                "verbose_name": "Intervenção",
                "verbose_name_plural": "Intervenções",
                "ordering": ["area_impacto__ordem", "ordem"],
            },
        ),
        migrations.AddIndex(
            model_name="orcamentointervencao",
            index=models.Index(fields=["orcamento", "status"], name="quotes_iv_orc_status_idx"),
        ),
        migrations.AddIndex(
            model_name="orcamentointervencao",
            index=models.Index(fields=["area_impacto", "status"], name="quotes_iv_area_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="orcamentointervencao",
            constraint=models.UniqueConstraint(
                fields=["orcamento", "area_impacto", "peca_canonica", "acao"],
                name="orcamento_intervencao_unica_por_area",
            ),
        ),

        migrations.CreateModel(
            name="OrcamentoItemAdicional",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("quantidade", models.PositiveIntegerField(default=1)),
                ("preco_unitario", models.DecimalField(decimal_places=2, max_digits=18, verbose_name="Preço unitário")),
                ("preco_total", models.DecimalField(decimal_places=2, max_digits=18, verbose_name="Preço total")),
                ("status", models.CharField(
                    choices=[
                        ("orcado", "Orçado"),
                        ("aprovado", "Aprovado"),
                        ("sem_cobertura", "Sem cobertura"),
                        ("sob_analise", "Sob análise"),
                        ("executado", "Executado"),
                        ("cancelado", "Cancelado"),
                    ],
                    default="orcado",
                    max_length=20,
                )),
                ("fornecimento", models.CharField(
                    choices=[("oficina", "Oficina"), ("seguradora", "Seguradora"), ("cliente", "Cliente")],
                    default="oficina",
                    max_length=20,
                )),
                ("inclusao_manual", models.BooleanField(default=False)),
                ("abaixo_padrao", models.BooleanField(default=False)),
                ("acima_padrao", models.BooleanField(default=False)),
                ("ordem", models.PositiveIntegerField(default=0)),
                ("descricao_visivel", models.CharField(blank=True, max_length=300)),
                ("observacao", models.TextField(blank=True)),
                ("created_by", models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    to=settings.AUTH_USER_MODEL,
                    related_name="+",
                )),
                ("orcamento", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="itens_adicionais",
                    to="quotes.orcamento",
                    verbose_name="Orçamento",
                )),
                ("service_catalog", models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    to="service_orders.servicecatalog",
                    verbose_name="Serviço do catálogo",
                )),
                ("snapshot", models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name="itens_adicionais",
                    to="pricing_engine.calculocustosnapshot",
                    verbose_name="Snapshot de custo",
                )),
            ],
            options={
                "verbose_name": "Item adicional",
                "verbose_name_plural": "Itens adicionais",
                "ordering": ["ordem"],
            },
        ),
        migrations.AddIndex(
            model_name="orcamentoitemadicional",
            index=models.Index(fields=["orcamento", "status"], name="quotes_item_orc_status_idx"),
        ),
    ]
