# Generated by Django 5.0.10 on 2026-04-21 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing_catalog", "0001_initial"),
        ("quotes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="orcamento",
            new_name="quotes_orca_empresa_1b8645_idx",
            old_name="quotes_orc_empresa_status_idx",
        ),
        migrations.RenameIndex(
            model_name="orcamento",
            new_name="quotes_orca_custome_855853_idx",
            old_name="quotes_orc_customer_idx",
        ),
        migrations.RenameIndex(
            model_name="orcamentointervencao",
            new_name="quotes_orca_orcamen_a7aed0_idx",
            old_name="quotes_iv_orc_status_idx",
        ),
        migrations.RenameIndex(
            model_name="orcamentointervencao",
            new_name="quotes_orca_area_im_bdc3c2_idx",
            old_name="quotes_iv_area_status_idx",
        ),
        migrations.RenameIndex(
            model_name="orcamentoitemadicional",
            new_name="quotes_orca_orcamen_5159fd_idx",
            old_name="quotes_item_orc_status_idx",
        ),
        migrations.AlterField(
            model_name="areaimpacto",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="orcamento",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="orcamentointervencao",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="orcamentointervencao",
            name="servico_canonico",
            field=models.ForeignKey(
                help_text="Resolvido via MAPEAMENTO_ACAO_SERVICO na criação.",
                on_delete=django.db.models.deletion.PROTECT,
                to="pricing_catalog.servicocanonico",
                verbose_name="Serviço canônico",
            ),
        ),
        migrations.AlterField(
            model_name="orcamentoitemadicional",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
