# Generated by Django 5.0.10 on 2026-04-16 18:57

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaTamanho",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "codigo",
                    models.SlugField(
                        help_text='Slug único, ex: "compacto", "suv-grande".',
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                ("nome", models.CharField(max_length=60, verbose_name="Nome")),
                (
                    "ordem",
                    models.PositiveSmallIntegerField(
                        help_text="Menor valor aparece primeiro.", verbose_name="Ordem de exibição"
                    ),
                ),
                (
                    "multiplicador_insumos",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Fator aplicado ao custo de insumos (tintas, produtos).",
                        max_digits=4,
                        verbose_name="Multiplicador de insumos",
                    ),
                ),
                (
                    "multiplicador_horas",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Fator aplicado às horas de mão de obra.",
                        max_digits=4,
                        verbose_name="Multiplicador de horas",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria de Tamanho",
                "verbose_name_plural": "Categorias de Tamanho",
                "ordering": ["ordem"],
            },
        ),
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "cnpj",
                    models.CharField(
                        db_index=True,
                        help_text="CNPJ sem pontuação (14 dígitos).",
                        max_length=14,
                        unique=True,
                        verbose_name="CNPJ",
                    ),
                ),
                ("nome_fantasia", models.CharField(max_length=120, verbose_name="Nome fantasia")),
                ("razao_social", models.CharField(max_length=200, verbose_name="Razão social")),
                (
                    "inscricao_estadual",
                    models.CharField(blank=True, max_length=20, verbose_name="Inscrição estadual"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
                "ordering": ["nome_fantasia"],
            },
        ),
        migrations.CreateModel(
            name="SegmentoVeicular",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "codigo",
                    models.SlugField(
                        help_text='Slug único, ex: "popular", "premium".',
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                ("nome", models.CharField(max_length=60, verbose_name="Nome")),
                (
                    "ordem",
                    models.PositiveSmallIntegerField(
                        help_text="Menor valor aparece primeiro.", verbose_name="Ordem de exibição"
                    ),
                ),
                (
                    "fator_responsabilidade",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Multiplicador do custo base de responsabilidade civil (0.5–5.0).",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.5")),
                            django.core.validators.MaxValueValidator(Decimal("5.0")),
                        ],
                        verbose_name="Fator responsabilidade",
                    ),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Segmento Veicular",
                "verbose_name_plural": "Segmentos Veiculares",
                "ordering": ["ordem"],
            },
        ),
        migrations.CreateModel(
            name="TipoPintura",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "codigo",
                    models.SlugField(
                        help_text='Slug único, ex: "solida", "metalica", "perolizada", "tricoat".',
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                ("nome", models.CharField(max_length=60, verbose_name="Nome")),
                (
                    "complexidade",
                    models.PositiveSmallIntegerField(
                        help_text="Nível de complexidade da pintura: 1 (Sólida) a 4 (Tricoat).",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                        verbose_name="Complexidade",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Pintura",
                "verbose_name_plural": "Tipos de Pintura",
                "ordering": ["complexidade"],
            },
        ),
        migrations.CreateModel(
            name="EnquadramentoVeiculo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("marca", models.CharField(db_index=True, max_length=60, verbose_name="Marca")),
                (
                    "modelo",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Deixar em branco para regra que cobre toda a marca.",
                        max_length=100,
                        verbose_name="Modelo",
                    ),
                ),
                (
                    "ano_inicio",
                    models.IntegerField(
                        blank=True,
                        help_text="Ano de fabricação inicial do intervalo (inclusive). Null = sem limite.",
                        null=True,
                        verbose_name="Ano início",
                    ),
                ),
                (
                    "ano_fim",
                    models.IntegerField(
                        blank=True,
                        help_text="Ano de fabricação final do intervalo (inclusive). Null = sem limite.",
                        null=True,
                        verbose_name="Ano fim",
                    ),
                ),
                (
                    "prioridade",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="Quanto menor, mais específico. Match exato (marca+modelo+ano) = 10; só marca = 100.",
                        verbose_name="Prioridade",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tamanho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enquadramentos",
                        to="pricing_profile.categoriatamanho",
                        verbose_name="Tamanho",
                    ),
                ),
                (
                    "segmento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enquadramentos",
                        to="pricing_profile.segmentoveicular",
                        verbose_name="Segmento",
                    ),
                ),
                (
                    "tipo_pintura_default",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tipo de pintura mais comum para este enquadramento. Pode ser sobrescrito na OS.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enquadramentos",
                        to="pricing_profile.tipopintura",
                        verbose_name="Tipo de pintura padrão",
                    ),
                ),
            ],
            options={
                "verbose_name": "Enquadramento de Veículo",
                "verbose_name_plural": "Enquadramentos de Veículos",
                "ordering": ["prioridade", "marca", "modelo"],
                "indexes": [
                    models.Index(
                        fields=["marca", "modelo", "ano_inicio", "ano_fim"],
                        name="pricing_pro_marca_46a571_idx",
                    )
                ],
            },
        ),
    ]
