# Generated by Django 5.0.10 on 2026-04-16 19:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing_profile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoriatamanho",
            name="multiplicador_horas",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Fator aplicado às horas de mão de obra. Intervalo: 0.1–5.0.",
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.1")),
                    django.core.validators.MaxValueValidator(Decimal("5.0")),
                ],
                verbose_name="Multiplicador de horas",
            ),
        ),
        migrations.AlterField(
            model_name="categoriatamanho",
            name="multiplicador_insumos",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Fator aplicado ao custo de insumos (tintas, produtos). Intervalo: 0.1–5.0.",
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.1")),
                    django.core.validators.MaxValueValidator(Decimal("5.0")),
                ],
                verbose_name="Multiplicador de insumos",
            ),
        ),
        migrations.CreateModel(
            name="EnquadramentoFaltante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("marca", models.CharField(db_index=True, max_length=60, verbose_name="Marca")),
                (
                    "modelo",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, verbose_name="Modelo"
                    ),
                ),
                ("ocorrencias", models.PositiveIntegerField(default=1, verbose_name="Ocorrências")),
                (
                    "primeira_ocorrencia",
                    models.DateTimeField(auto_now_add=True, verbose_name="Primeira ocorrência"),
                ),
                (
                    "ultima_ocorrencia",
                    models.DateTimeField(auto_now=True, verbose_name="Última ocorrência"),
                ),
            ],
            options={
                "verbose_name": "Enquadramento Faltante",
                "verbose_name_plural": "Enquadramentos Faltantes",
                "ordering": ["-ocorrencias"],
                "unique_together": {("marca", "modelo")},
            },
        ),
    ]
