# Generated by Django 5.0.10 on 2026-03-30 00:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sku", models.CharField(db_index=True, max_length=100, unique=True)),
                ("name", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True, default="")),
                ("unit", models.CharField(default="un", max_length=20)),
                ("category", models.CharField(blank=True, default="", max_length=100)),
                ("brand", models.CharField(blank=True, default="", max_length=100)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
                "db_table": "inventory_product",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("quantity", models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                (
                    "min_quantity",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=15, verbose_name="Estoque mínimo"
                    ),
                ),
                ("cost_price", models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ("sale_price", models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                (
                    "location",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="Localização"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Estoque",
                "verbose_name_plural": "Itens de Estoque",
                "db_table": "inventory_item",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("entry", "Entrada"),
                            ("exit", "Saída"),
                            ("transfer_out", "Transferência saída"),
                            ("transfer_in", "Transferência entrada"),
                            ("adjustment", "Ajuste"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=15)),
                ("unit_cost", models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ("reference_id", models.UUIDField(blank=True, null=True)),
                ("reference_type", models.CharField(blank=True, default="", max_length=50)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimentação de Estoque",
                "verbose_name_plural": "Movimentações de Estoque",
                "db_table": "inventory_movement",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="inventoryitem",
            constraint=models.CheckConstraint(
                check=models.Q(("quantity__gte", 0)), name="inventory_item_quantity_non_negative"
            ),
        ),
    ]
