# Generated by Django 5.0.10 on 2026-04-18 19:27

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0002_nfeentrada_nfeentradaitem_and_more"),
        ("inventory", "0001_initial"),
        ("pricing_catalog", "0001_initial"),
        ("service_orders", "0018_vehicle_profile_snapshot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImpressoraEtiqueta",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("nome", models.CharField(max_length=50)),
                (
                    "modelo",
                    models.CharField(
                        choices=[
                            ("zebra_gk420", "Zebra GK420t"),
                            ("zebra_zd220", "Zebra ZD220"),
                            ("argox_os214", "Argox OS-214"),
                            ("elgin_l42", "Elgin L42"),
                            ("outro", "Outro"),
                        ],
                        default="zebra_gk420",
                        max_length=20,
                    ),
                ),
                (
                    "endpoint",
                    models.CharField(
                        help_text="Ex: http://10.0.0.15:9100 (Zebra direct print).", max_length=200
                    ),
                ),
                ("largura_mm", models.PositiveIntegerField(default=50)),
                ("altura_mm", models.PositiveIntegerField(default=30)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Impressora de Etiqueta",
                "verbose_name_plural": "Impressoras de Etiqueta",
                "db_table": "inventory_impressora_etiqueta",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LoteInsumo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "codigo_barras",
                    models.CharField(blank=True, default="", max_length=40, unique=True),
                ),
                ("unidade_compra", models.CharField(max_length=20)),
                ("quantidade_compra", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "fator_conversao",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Quantas unidade_base cabem em 1 unidade_compra.",
                        max_digits=10,
                    ),
                ),
                ("quantidade_base", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "saldo",
                    models.DecimalField(
                        decimal_places=3, help_text="Saldo restante em unidade_base.", max_digits=10
                    ),
                ),
                ("valor_total_nf", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "valor_unitario_base",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Custo unitário em unidade_base. Calculado no save().",
                        max_digits=12,
                    ),
                ),
                ("validade", models.DateField(blank=True, null=True)),
                (
                    "localizacao",
                    models.CharField(
                        blank=True, default="", max_length=80, verbose_name="Localização física"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "material_canonico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lotes",
                        to="pricing_catalog.materialcanonico",
                    ),
                ),
                (
                    "nfe_entrada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lotes_insumo",
                        to="fiscal.nfeentrada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lote de Insumo",
                "verbose_name_plural": "Lotes de Insumo",
                "db_table": "inventory_lote_insumo",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConsumoInsumo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("quantidade_base", models.DecimalField(decimal_places=3, max_digits=10)),
                ("valor_unitario_na_baixa", models.DecimalField(decimal_places=4, max_digits=12)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ordem_servico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consumos_insumo",
                        to="service_orders.serviceorder",
                    ),
                ),
                (
                    "lote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consumos",
                        to="inventory.loteinsumo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consumo de Insumo",
                "verbose_name_plural": "Consumos de Insumo",
                "db_table": "inventory_consumo_insumo",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UnidadeFisica",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("numero_serie", models.CharField(blank=True, default="", max_length=80)),
                (
                    "codigo_barras",
                    models.CharField(blank=True, default="", max_length=40, unique=True),
                ),
                (
                    "valor_nf",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor unitário na NF-e COM tributação embutida.",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "localizacao",
                    models.CharField(
                        blank=True, default="", max_length=80, verbose_name="Localização física"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Disponível"),
                            ("reserved", "Reservada para OS"),
                            ("consumed", "Consumida em OS"),
                            ("returned", "Devolvida ao fornecedor"),
                            ("lost", "Perdida/Avariada"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("consumida_em", models.DateTimeField(blank=True, null=True)),
                (
                    "codigo_fornecedor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Variante específica do fornecedor (se aplicável).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pricing_catalog.codigofornecedorpeca",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "nfe_entrada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unidades_fisicas",
                        to="fiscal.nfeentrada",
                    ),
                ),
                (
                    "ordem_servico",
                    models.ForeignKey(
                        blank=True,
                        help_text="Preenchido quando status=reserved/consumed.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unidades_fisicas",
                        to="service_orders.serviceorder",
                    ),
                ),
                (
                    "peca_canonica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unidades",
                        to="pricing_catalog.pecacanonica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unidade Física",
                "verbose_name_plural": "Unidades Físicas",
                "db_table": "inventory_unidade_fisica",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EtiquetaImpressa",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("zpl_payload", models.TextField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "impressa_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "impressora",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="etiquetas",
                        to="inventory.impressoraetiqueta",
                    ),
                ),
                (
                    "lote_insumo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etiquetas",
                        to="inventory.loteinsumo",
                    ),
                ),
                (
                    "unidade_fisica",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etiquetas",
                        to="inventory.unidadefisica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Etiqueta Impressa",
                "verbose_name_plural": "Etiquetas Impressas",
                "db_table": "inventory_etiqueta_impressa",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="loteinsumo",
            index=models.Index(
                fields=["material_canonico", "saldo"], name="inventory_l_materia_c69d31_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loteinsumo",
            index=models.Index(fields=["codigo_barras"], name="inventory_l_codigo__19889c_idx"),
        ),
        migrations.AddIndex(
            model_name="loteinsumo",
            index=models.Index(fields=["created_at"], name="inventory_l_created_6cc4e7_idx"),
        ),
        migrations.AddConstraint(
            model_name="loteinsumo",
            constraint=models.CheckConstraint(
                check=models.Q(("saldo__gte", 0)), name="lote_saldo_nao_negativo"
            ),
        ),
        migrations.AddConstraint(
            model_name="loteinsumo",
            constraint=models.CheckConstraint(
                check=models.Q(("saldo__lte", models.F("quantidade_base"))),
                name="lote_saldo_menor_que_inicial",
            ),
        ),
        migrations.AddIndex(
            model_name="consumoinsumo",
            index=models.Index(
                fields=["ordem_servico", "created_at"], name="inventory_c_ordem_s_071ca2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unidadefisica",
            index=models.Index(
                fields=["peca_canonica", "status"], name="inventory_u_peca_ca_9b596d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unidadefisica",
            index=models.Index(fields=["codigo_barras"], name="inventory_u_codigo__9c10ef_idx"),
        ),
        migrations.AddIndex(
            model_name="unidadefisica",
            index=models.Index(
                fields=["ordem_servico", "status"], name="inventory_u_ordem_s_78e6d2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="etiquetaimpressa",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("lote_insumo__isnull", True), ("unidade_fisica__isnull", False)),
                    models.Q(("lote_insumo__isnull", False), ("unidade_fisica__isnull", True)),
                    _connector="OR",
                ),
                name="etiqueta_xor_unidade_lote",
            ),
        ),
    ]
