# Generated by Django 5.0.10 on 2026-05-02 23:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_impressoraetiqueta_loteinsumo_consumoinsumo_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Armazem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("nome", models.CharField(max_length=80)),
                ("codigo", models.CharField(help_text="Código curto: G1, G2, PT1.", max_length=10)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("galpao", "Galpão"), ("patio", "Pátio")],
                        default="galpao",
                        max_length=10,
                    ),
                ),
                ("endereco", models.CharField(blank=True, default="", max_length=200)),
                ("observacoes", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="armazens_responsavel",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Armazém",
                "verbose_name_plural": "Armazéns",
                "db_table": "inventory_armazem",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Prateleira",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("codigo", models.CharField(help_text="P01, P02.", max_length=10)),
                ("descricao", models.CharField(blank=True, default="", max_length=80)),
                (
                    "capacidade_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Peso máximo suportado (kg).",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("ordem", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Prateleira",
                "verbose_name_plural": "Prateleiras",
                "db_table": "inventory_prateleira",
                "ordering": ["ordem", "codigo"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Nivel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("codigo", models.CharField(help_text="N1, N2.", max_length=10)),
                ("descricao", models.CharField(blank=True, default="", max_length=80)),
                ("altura_cm", models.PositiveIntegerField(blank=True, null=True)),
                ("largura_cm", models.PositiveIntegerField(blank=True, null=True)),
                ("profundidade_cm", models.PositiveIntegerField(blank=True, null=True)),
                ("ordem", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prateleira",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="niveis",
                        to="inventory.prateleira",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nível",
                "verbose_name_plural": "Níveis",
                "db_table": "inventory_nivel",
                "ordering": ["ordem", "codigo"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Rua",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("codigo", models.CharField(help_text="R01, R02.", max_length=10)),
                ("descricao", models.CharField(blank=True, default="", max_length=80)),
                ("ordem", models.PositiveIntegerField(default=0)),
                (
                    "armazem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ruas",
                        to="inventory.armazem",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rua",
                "verbose_name_plural": "Ruas",
                "db_table": "inventory_rua",
                "ordering": ["ordem", "codigo"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="prateleira",
            name="rua",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prateleiras",
                to="inventory.rua",
            ),
        ),
        migrations.AddConstraint(
            model_name="armazem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("codigo",),
                name="unique_armazem_codigo_active",
            ),
        ),
        migrations.AddIndex(
            model_name="nivel",
            index=models.Index(
                fields=["prateleira", "ordem"], name="inventory_n_pratele_7f348f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="nivel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("prateleira", "codigo"),
                name="unique_nivel_prateleira_codigo_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="rua",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("armazem", "codigo"),
                name="unique_rua_armazem_codigo_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="prateleira",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("rua", "codigo"),
                name="unique_prateleira_rua_codigo_active",
            ),
        ),
    ]
