# Generated by Django 5.0.10 on 2026-05-02 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_wms_location_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="loteinsumo",
            name="nivel",
            field=models.ForeignKey(
                blank=True,
                help_text="Posição no armazém (WMS).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lotes_insumo",
                to="inventory.nivel",
            ),
        ),
        migrations.AddField(
            model_name="unidadefisica",
            name="nivel",
            field=models.ForeignKey(
                blank=True,
                help_text="Posição no armazém (WMS).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unidades_fisicas",
                to="inventory.nivel",
            ),
        ),
    ]
