# Generated by Django 5.0.10 on 2026-05-02 23:45

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_wms_add_nivel_fk"),
        ("pricing_catalog", "0002_pecacanonica_ncm"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaInsumo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("nome", models.CharField(max_length=120)),
                (
                    "codigo",
                    models.CharField(
                        help_text="Código curto único (ex: TINT, VERN).", max_length=20
                    ),
                ),
                (
                    "margem_padrao_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Margem padrão (%) para insumos desta categoria.",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                ("ordem", models.PositiveSmallIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria de Insumo",
                "verbose_name_plural": "Categorias de Insumo",
                "db_table": "inventory_categoria_insumo",
                "ordering": ["ordem", "nome"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CategoriaProduto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("nome", models.CharField(max_length=120)),
                (
                    "codigo",
                    models.CharField(
                        help_text="Código curto único (ex: FUN, PINT).", max_length=20
                    ),
                ),
                (
                    "margem_padrao_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Margem padrão (%) para produtos desta categoria.",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                ("ordem", models.PositiveSmallIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria de Produto (Peça)",
                "verbose_name_plural": "Categorias de Produto (Peça)",
                "db_table": "inventory_categoria_produto",
                "ordering": ["ordem", "nome"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProdutoComercialInsumo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "sku_interno",
                    models.CharField(
                        help_text="SKU interno da empresa (ex: VN-001).", max_length=40
                    ),
                ),
                (
                    "nome_interno",
                    models.CharField(
                        help_text="Nome comercial do insumo (ex: Verniz PU Lazzuril 900ml).",
                        max_length=255,
                    ),
                ),
                (
                    "codigo_fabricante",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Part number do fabricante.",
                        max_length=60,
                    ),
                ),
                (
                    "codigo_ean",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Código EAN/GTIN (8 ou 13 dígitos).",
                        max_length=14,
                    ),
                ),
                (
                    "nome_fabricante",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Nome do fabricante (ex: Lazzuril, Sikkens).",
                        max_length=120,
                    ),
                ),
                (
                    "unidade_base",
                    models.CharField(
                        default="un",
                        help_text="Unidade de medida base (L, ml, kg, un).",
                        max_length=10,
                    ),
                ),
                (
                    "preco_venda_sugerido",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Preço de venda sugerido (R$).",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "margem_padrao_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Margem (%) — sobrescreve a da categoria se preenchida.",
                        max_digits=5,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                ("observacoes", models.TextField(blank=True, default="")),
                (
                    "categoria_insumo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="produtos",
                        to="inventory.categoriainsumo",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "material_canonico",
                    models.ForeignKey(
                        blank=True,
                        help_text="Material canônico do catálogo técnico.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="produtos_comerciais",
                        to="pricing_catalog.materialcanonico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produto Comercial (Insumo)",
                "verbose_name_plural": "Produtos Comerciais (Insumos)",
                "db_table": "inventory_produto_comercial_insumo",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="loteinsumo",
            name="produto_insumo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lotes",
                to="inventory.produtocomercialinsumo",
            ),
        ),
        migrations.CreateModel(
            name="ProdutoComercialPeca",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "sku_interno",
                    models.CharField(
                        help_text="SKU interno da empresa (ex: PC-001).", max_length=40
                    ),
                ),
                (
                    "nome_interno",
                    models.CharField(
                        help_text="Nome comercial da peça (ex: Para-choque Gol G5 Dianteiro).",
                        max_length=255,
                    ),
                ),
                (
                    "codigo_fabricante",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Part number do fabricante.",
                        max_length=60,
                    ),
                ),
                (
                    "codigo_ean",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Código EAN/GTIN (8 ou 13 dígitos).",
                        max_length=14,
                    ),
                ),
                (
                    "codigo_distribuidor",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Código do distribuidor/atacadista.",
                        max_length=60,
                    ),
                ),
                (
                    "nome_fabricante",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Nome do fabricante (ex: Volkswagen, Cibie).",
                        max_length=120,
                    ),
                ),
                (
                    "posicao_veiculo",
                    models.CharField(
                        choices=[
                            ("dianteiro", "Dianteiro"),
                            ("traseiro", "Traseiro"),
                            ("lateral_esq", "Lateral Esquerdo"),
                            ("lateral_dir", "Lateral Direito"),
                            ("superior", "Superior"),
                            ("inferior", "Inferior"),
                            ("na", "N/A"),
                        ],
                        default="na",
                        max_length=20,
                    ),
                ),
                (
                    "lado",
                    models.CharField(
                        choices=[
                            ("esquerdo", "Esquerdo"),
                            ("direito", "Direito"),
                            ("central", "Central"),
                            ("na", "N/A"),
                        ],
                        default="na",
                        max_length=20,
                    ),
                ),
                (
                    "preco_venda_sugerido",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Preço de venda sugerido (R$).",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "margem_padrao_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Margem (%) — sobrescreve a da categoria se preenchida.",
                        max_digits=5,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                ("observacoes", models.TextField(blank=True, default="")),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="produtos",
                        to="inventory.categoriaproduto",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "peca_canonica",
                    models.ForeignKey(
                        blank=True,
                        help_text="Peça canônica do catálogo técnico.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="produtos_comerciais",
                        to="pricing_catalog.pecacanonica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produto Comercial (Peça)",
                "verbose_name_plural": "Produtos Comerciais (Peças)",
                "db_table": "inventory_produto_comercial_peca",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="unidadefisica",
            name="produto_peca",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unidades_fisicas",
                to="inventory.produtocomercialpeca",
            ),
        ),
        migrations.CreateModel(
            name="TipoPeca",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("nome", models.CharField(max_length=120)),
                (
                    "codigo",
                    models.CharField(
                        help_text="Código curto único (ex: PCHQ, FAROL).", max_length=20
                    ),
                ),
                ("ordem", models.PositiveSmallIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Peça",
                "verbose_name_plural": "Tipos de Peça",
                "db_table": "inventory_tipo_peca",
                "ordering": ["ordem", "nome"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="produtocomercialpeca",
            name="tipo_peca",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="produtos",
                to="inventory.tipopeca",
            ),
        ),
        migrations.AddConstraint(
            model_name="categoriainsumo",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("codigo",),
                name="uq_categoria_insumo_codigo_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="categoriaproduto",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("codigo",),
                name="uq_categoria_produto_codigo_active",
            ),
        ),
        migrations.AddIndex(
            model_name="produtocomercialinsumo",
            index=models.Index(fields=["codigo_ean"], name="idx_prod_insumo_ean"),
        ),
        migrations.AddIndex(
            model_name="produtocomercialinsumo",
            index=models.Index(fields=["codigo_fabricante"], name="idx_prod_insumo_fab"),
        ),
        migrations.AddIndex(
            model_name="produtocomercialinsumo",
            index=models.Index(fields=["material_canonico"], name="idx_prod_insumo_canonico"),
        ),
        migrations.AddConstraint(
            model_name="produtocomercialinsumo",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("sku_interno",),
                name="uq_produto_insumo_sku_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="tipopeca",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("codigo",),
                name="uq_tipo_peca_codigo_active",
            ),
        ),
        migrations.AddIndex(
            model_name="produtocomercialpeca",
            index=models.Index(fields=["codigo_ean"], name="idx_prod_peca_ean"),
        ),
        migrations.AddIndex(
            model_name="produtocomercialpeca",
            index=models.Index(fields=["codigo_fabricante"], name="idx_prod_peca_fab"),
        ),
        migrations.AddIndex(
            model_name="produtocomercialpeca",
            index=models.Index(fields=["peca_canonica"], name="idx_prod_peca_canonica"),
        ),
        migrations.AddIndex(
            model_name="produtocomercialpeca",
            index=models.Index(
                fields=["tipo_peca", "posicao_veiculo", "lado"], name="idx_prod_peca_tipo_pos_lado"
            ),
        ),
        migrations.AddConstraint(
            model_name="produtocomercialpeca",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("sku_interno",),
                name="uq_produto_peca_sku_active",
            ),
        ),
    ]
