# Generated by Django 5.0.10 on 2026-05-02 23:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0007_wms_movimentacao_estoque"),
        ("inventory", "0005_wms_product_models"),
        ("service_orders", "0025_wms_movimentacao_estoque"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MovimentacaoEstoque",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("entrada_nf", "Entrada via NF-e"),
                            ("entrada_manual", "Entrada Manual"),
                            ("entrada_devolucao", "Devolução"),
                            ("saida_os", "Saída para OS"),
                            ("saida_perda", "Perda/Avaria"),
                            ("transferencia", "Transferência"),
                            ("ajuste_inventario", "Ajuste de Inventário"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "quantidade",
                    models.DecimalField(
                        decimal_places=3, help_text="1 para peça, N para insumo.", max_digits=10
                    ),
                ),
                (
                    "motivo",
                    models.TextField(
                        blank=True, default="", help_text="Obrigatório para PERDA e AJUSTE."
                    ),
                ),
                (
                    "evidencia",
                    models.FileField(
                        blank=True,
                        help_text="Foto para perda/ajuste.",
                        null=True,
                        upload_to="inventory/evidencias/%Y/%m/",
                    ),
                ),
                ("aprovado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "aprovado_por",
                    models.ForeignKey(
                        blank=True,
                        help_text="PERDA e AJUSTE requerem MANAGER+.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimentacoes_aprovadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lote_insumo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimentacoes",
                        to="inventory.loteinsumo",
                    ),
                ),
                (
                    "nfe_entrada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimentacoes_estoque",
                        to="fiscal.nfeentrada",
                    ),
                ),
                (
                    "nivel_destino",
                    models.ForeignKey(
                        blank=True,
                        help_text="Para onde foi.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimentacoes_destino",
                        to="inventory.nivel",
                    ),
                ),
                (
                    "nivel_origem",
                    models.ForeignKey(
                        blank=True,
                        help_text="De onde saiu.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimentacoes_origem",
                        to="inventory.nivel",
                    ),
                ),
                (
                    "ordem_servico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimentacoes_estoque",
                        to="service_orders.serviceorder",
                    ),
                ),
                (
                    "realizado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimentacoes_realizadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unidade_fisica",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimentacoes",
                        to="inventory.unidadefisica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimentação de Estoque",
                "verbose_name_plural": "Movimentações de Estoque",
                "db_table": "inventory_movimentacao_estoque",
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(fields=["tipo", "created_at"], name="inventory_m_tipo_9472ae_idx"),
                    models.Index(fields=["unidade_fisica"], name="inventory_m_unidade_bb3828_idx"),
                    models.Index(fields=["lote_insumo"], name="inventory_m_lote_in_e0a6a7_idx"),
                    models.Index(fields=["ordem_servico"], name="inventory_m_ordem_s_727998_idx"),
                    models.Index(fields=["realizado_por"], name="inventory_m_realiza_1508b2_idx"),
                ],
            },
        ),
    ]
