# Generated by Django 5.0.10 on 2026-05-02 23:54

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_wms_movimentacao_estoque"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContagemInventario",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("ciclica", "Cíclica"), ("total", "Total")], max_length=15
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aberta", "Aberta"),
                            ("em_andamento", "Em Andamento"),
                            ("finalizada", "Finalizada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="aberta",
                        max_length=15,
                    ),
                ),
                ("data_abertura", models.DateTimeField(auto_now_add=True)),
                ("data_fechamento", models.DateTimeField(blank=True, null=True)),
                ("observacoes", models.TextField(blank=True, default="")),
                (
                    "armazem",
                    models.ForeignKey(
                        blank=True,
                        help_text="Contagem total = armazém inteiro.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contagens",
                        to="inventory.armazem",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fechado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contagens_fechadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "iniciado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contagens_iniciadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rua",
                    models.ForeignKey(
                        blank=True,
                        help_text="Contagem cíclica = por rua.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contagens",
                        to="inventory.rua",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contagem de Inventário",
                "verbose_name_plural": "Contagens de Inventário",
                "db_table": "inventory_contagem_inventario",
                "ordering": ["-data_abertura"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ItemContagem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "quantidade_sistema",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Quantidade que o sistema registra.",
                        max_digits=10,
                    ),
                ),
                (
                    "quantidade_contada",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Quantidade contada pelo operador.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "divergencia",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0"),
                        help_text="contada - sistema. Computado no save().",
                        max_digits=10,
                    ),
                ),
                ("observacao", models.CharField(blank=True, default="", max_length=200)),
                (
                    "contado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="itens_contados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contagem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="inventory.contageminventario",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lote_insumo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="itens_contagem",
                        to="inventory.loteinsumo",
                    ),
                ),
                (
                    "nivel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens_contagem",
                        to="inventory.nivel",
                    ),
                ),
                (
                    "unidade_fisica",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="itens_contagem",
                        to="inventory.unidadefisica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Contagem",
                "verbose_name_plural": "Itens de Contagem",
                "db_table": "inventory_item_contagem",
                "ordering": ["nivel__prateleira__codigo", "nivel__codigo"],
                "abstract": False,
            },
        ),
    ]
