# Generated by Django 5.0.10 on 2026-05-03 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_wms_contagem_inventario"),
        ("pricing_catalog", "0002_pecacanonica_ncm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loteinsumo",
            name="material_canonico",
            field=models.ForeignKey(
                blank=True,
                help_text="Nullable para insumos sem catálogo canônico.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lotes",
                to="pricing_catalog.materialcanonico",
            ),
        ),
        migrations.AlterField(
            model_name="unidadefisica",
            name="peca_canonica",
            field=models.ForeignKey(
                blank=True,
                help_text="Nullable para peças sem catálogo canônico (avulsas, recondicionadas).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="unidades",
                to="pricing_catalog.pecacanonica",
            ),
        ),
    ]
