# Generated by Django 5.0.10 on 2026-05-14 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_nullable_canonica_fks"),
        ("parts_catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produtocomercialpeca",
            name="part_ref",
            field=models.ForeignKey(
                blank=True,
                help_text="Referência no catálogo shared de peças (cross-tenant).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="produtos_comerciais",
                to="parts_catalog.partreference",
            ),
        ),
    ]
