# Generated by Django 5.2.12 on 2026-04-21 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_seed_ref_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_type', models.CharField(choices=[('BUDGET', 'Orçamento Particular'), ('SERVICE_ORDER', 'Ordem de Serviço')], max_length=20, unique=True)),
                ('prefix', models.CharField(max_length=10)),
                ('padding', models.IntegerField(default=6)),
                ('next_number', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Sequência de Numeração',
                'verbose_name_plural': 'Sequências de Numeração',
            },
        ),
    ]
