# Generated by Django 5.2.12 on 2026-04-21 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_add_version_indexes'),
        ('items', '0004_seed_number_sequences'),
        ('service_orders', '0005_add_version_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('item_budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='budgets.budgetversionitem')),
                ('item_so', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='service_orders.serviceorderversionitem')),
                ('labor_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='items.laborcategory')),
                ('operation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='items.itemoperationtype')),
            ],
            options={
                'verbose_name': 'Operação de Item',
                'verbose_name_plural': 'Operações de Item',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('item_budget__isnull', False), ('item_so__isnull', True)), models.Q(('item_budget__isnull', True), ('item_so__isnull', False)), _connector='OR'), name='itemop_xor_parent')],
            },
        ),
    ]
