"""
Paddock Solutions — JWT Authentication Backends

NativeJWTAuthentication: validates tokens generated by our native auth system.
KeycloakJWTAuthentication: DEPRECATED — kept for migration period only.
"""
import hashlib
import logging

import jwt as pyjwt
from rest_framework.authentication import BaseAuthentication
from rest_framework.exceptions import AuthenticationFailed

from .jwt_utils import decode_token

logger = logging.getLogger(__name__)


class NativeJWTAuthentication(BaseAuthentication):
    """Authenticates requests using native JWT tokens (HS256 dev / RS256 prod).

    Returns (user, payload) where payload is the decoded JWT dict.
    request.auth will contain the payload with role, permissions, etc.
    Returns None if the token is missing or invalid (allows fallback to other backends).
    """

    def authenticate(self, request) -> tuple | None:  # type: ignore[override]
        from apps.authentication.models import GlobalUser

        auth_header: str = request.META.get("HTTP_AUTHORIZATION", "")
        if not auth_header.startswith("Bearer "):
            return None

        token = auth_header[7:]
        try:
            payload = decode_token(token)
        except pyjwt.ExpiredSignatureError:
            raise AuthenticationFailed("Token expirado.")
        except pyjwt.InvalidTokenError:
            return None

        if payload.get("token_type") != "access":
            return None

        user_id = payload.get("sub")
        if not user_id:
            return None

        try:
            user = GlobalUser.objects.get(pk=user_id, is_active=True)
        except GlobalUser.DoesNotExist:
            raise AuthenticationFailed("Usuário não encontrado ou desativado.")

        return (user, payload)

    def authenticate_header(self, request) -> str:  # type: ignore[override]
        return "Bearer"


class KeycloakJWTAuthentication(BaseAuthentication):
    """DEPRECATED: Autentica JWTs RS256 emitidos pelo Keycloak.

    Mantido temporariamente para periodo de migracao.
    Sera removido quando todos os tokens Keycloak expirarem.
    """

    def authenticate(self, request) -> tuple | None:  # type: ignore[override]
        from apps.authentication.models import GlobalUser

        auth_header: str = request.META.get("HTTP_AUTHORIZATION", "")
        if not auth_header.startswith("Bearer "):
            return None

        raw_token = auth_header.split(" ", 1)[1]

        try:
            unverified_header = pyjwt.get_unverified_header(raw_token)
        except pyjwt.exceptions.DecodeError:
            return None

        # Only handle RS256 tokens (Keycloak)
        if unverified_header.get("alg") != "RS256":
            return None

        # Try to validate with JWKS endpoint
        from django.conf import settings
        jwks_endpoint = getattr(settings, "OIDC_OP_JWKS_ENDPOINT", "")
        if not jwks_endpoint:
            return None

        try:
            from jwt import PyJWKClient
            jwks_client = PyJWKClient(jwks_endpoint, cache_keys=True)
            signing_key = jwks_client.get_signing_key_from_jwt(raw_token)
            payload = pyjwt.decode(
                raw_token,
                signing_key.key,
                algorithms=["RS256"],
                options={"verify_aud": False},
            )
        except pyjwt.exceptions.ExpiredSignatureError:
            raise AuthenticationFailed("Token Keycloak expirado.")
        except Exception as exc:
            logger.warning("KeycloakJWTAuthentication: falha ao validar token RS256: %s", exc)
            return None

        email: str = payload.get("email") or payload.get("preferred_username", "")
        if not email:
            raise AuthenticationFailed(
                "Claim 'email' ou 'preferred_username' ausente no token Keycloak."
            )

        email_hash = hashlib.sha256(email.lower().encode()).hexdigest()
        user, created = GlobalUser.objects.get_or_create(
            email_hash=email_hash,
            defaults={
                "email": email,
                "name": payload.get("name", email.split("@")[0]),
                "is_active": True,
            },
        )
        if created:
            logger.info("Keycloak: usuario criado automaticamente (hash=%s...)", email_hash[:8])

        return (user, payload)

    def authenticate_header(self, request) -> str:  # type: ignore[override]
        return "Bearer"
