# Generated by Django 5.0.10 on 2026-04-03 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="insurer",
            name="uses_cilia",
            field=models.BooleanField(
                default=False,
                help_text="Marque se a seguradora envia orçamentos pelo sistema Cilia",
                verbose_name="Utiliza Cilia?",
            ),
        ),
    ]
