# Generated by Django 5.0.10 on 2026-04-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurers", "0003_insurer_logo_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="insurer",
            name="code",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                max_length=40,
                null=True,
                unique=True,
                verbose_name="Código interno",
            ),
        ),
    ]
