# Generated by Django 5.0.10 on 2026-04-25 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurers", "0004_add_code_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="InsurerTenantProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "contact_sinistro_nome",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Sinistros — Nome"
                    ),
                ),
                (
                    "contact_sinistro_phone",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="Sinistros — Telefone"
                    ),
                ),
                (
                    "contact_sinistro_email",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Sinistros — E-mail"
                    ),
                ),
                (
                    "contact_financeiro_nome",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Financeiro — Nome"
                    ),
                ),
                (
                    "contact_financeiro_phone",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="Financeiro — Telefone"
                    ),
                ),
                (
                    "contact_financeiro_email",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Financeiro — E-mail"
                    ),
                ),
                (
                    "contact_comercial_nome",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Comercial — Nome"
                    ),
                ),
                (
                    "contact_comercial_phone",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="Comercial — Telefone"
                    ),
                ),
                (
                    "contact_comercial_email",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Comercial — E-mail"
                    ),
                ),
                (
                    "portal_url",
                    models.URLField(
                        blank=True, default="", verbose_name="Portal de acionamento (URL)"
                    ),
                ),
                (
                    "sla_dias_uteis",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="SLA de resposta (dias úteis)"
                    ),
                ),
                (
                    "observacoes_operacionais",
                    models.TextField(
                        blank=True, default="", verbose_name="Observações operacionais"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "insurer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tenant_profile",
                        to="insurers.insurer",
                        verbose_name="Seguradora",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil Operacional da Seguradora",
                "verbose_name_plural": "Perfis Operacionais de Seguradoras",
            },
        ),
    ]
