# Generated by Django 5.0.10 on 2026-05-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurers", "0006_insurer_tenant_profile_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="insurertenantprofile",
            name="import_tool",
            field=models.CharField(
                choices=[
                    ("cilia", "Cilia (Webservice)"),
                    ("soma", "Soma (XML)"),
                    ("audatex", "Audatex (HTML)"),
                    ("manual", "Manual"),
                ],
                default="manual",
                help_text="Ferramenta usada para importar orçamentos desta seguradora.",
                max_length=20,
                verbose_name="Ferramenta de importação",
            ),
        ),
    ]
