# Generated by Django 5.0.10 on 2026-05-26 14:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurers", "0007_add_import_tool"),
    ]

    operations = [
        migrations.AddField(
            model_name="insurer",
            name="trade_names",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200),
                blank=True,
                default=list,
                help_text="Nomes usados por sistemas externos (Cilia, Soma, Audatex) para identificar esta seguradora.",
                size=None,
                verbose_name="Nomes comerciais (importacao)",
            ),
        ),
    ]
