# Generated by Django 5.0.10 on 2026-04-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0008_backfill_person_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personcontact",
            name="value_hash",
            field=models.CharField(
                db_index=True, default="", max_length=64, verbose_name="Hash do valor"
            ),
        ),
    ]
