# Generated by Django 5.0.10 on 2026-04-25 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0009_alter_personcontact_value_hash"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="department",
        ),
        migrations.RemoveField(
            model_name="person",
            name="document",
        ),
        migrations.RemoveField(
            model_name="person",
            name="insurer_code",
        ),
        migrations.RemoveField(
            model_name="person",
            name="job_title",
        ),
        migrations.RemoveField(
            model_name="person",
            name="logo_url",
        ),
    ]
