# Generated by Django 5.0.10 on 2026-04-25 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0010_person_cleanup"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrokerOffice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broker_office",
                        to="persons.person",
                        verbose_name="Pessoa (PJ)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Escritório de Corretagem",
                "verbose_name_plural": "Escritórios de Corretagem",
            },
        ),
        migrations.CreateModel(
            name="BrokerPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "office",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="members",
                        to="persons.brokeroffice",
                        verbose_name="Escritório de corretagem",
                    ),
                ),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broker_person",
                        to="persons.person",
                        verbose_name="Pessoa (PF)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Corretor",
                "verbose_name_plural": "Corretores",
            },
        ),
        migrations.CreateModel(
            name="ClientProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "lgpd_consent_version",
                    models.CharField(
                        default="1.0", max_length=10, verbose_name="Versão do consentimento LGPD"
                    ),
                ),
                (
                    "lgpd_consent_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data do consentimento LGPD"
                    ),
                ),
                (
                    "lgpd_consent_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP do consentimento LGPD"
                    ),
                ),
                (
                    "group_sharing_consent",
                    models.BooleanField(
                        default=False,
                        help_text="Opt-in EXPLÍCITO — verificar antes de cross-sell entre empresas do grupo.",
                        verbose_name="Consentimento de compartilhamento no grupo",
                    ),
                ),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_profile",
                        to="persons.person",
                        verbose_name="Pessoa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Cliente",
                "verbose_name_plural": "Perfis de Cliente",
            },
        ),
    ]
