# Generated by Django 5.0.10 on 2026-06-22 15:58

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurers", "0009_seed_cilia_insurers"),
        ("persons", "0011_add_submodels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personrole",
            name="role",
            field=models.CharField(
                choices=[
                    ("CLIENT", "Cliente"),
                    ("INSURER", "Seguradora"),
                    ("BROKER", "Corretor"),
                    ("EMPLOYEE", "Funcionário"),
                    ("SUPPLIER", "Fornecedor"),
                    ("EXPERT", "Perito"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ExpertProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="CREA ou registro profissional",
                        max_length=50,
                        verbose_name="Número de registro",
                    ),
                ),
                (
                    "legacy_expert_id",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        help_text="ID original em experts.Expert — preenchido na migração",
                        null=True,
                    ),
                ),
                (
                    "insurers",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Seguradoras para as quais este perito atua",
                        related_name="experts_as_person",
                        to="insurers.insurer",
                        verbose_name="Seguradoras",
                    ),
                ),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expert_profile",
                        to="persons.person",
                        verbose_name="Pessoa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Perito",
                "verbose_name_plural": "Perfis de Perito",
            },
        ),
        migrations.CreateModel(
            name="SupplierProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PARTS", "Peças"),
                            ("SERVICE", "Serviços"),
                            ("MATERIAL", "Material"),
                            ("GENERAL", "Geral"),
                        ],
                        default="GENERAL",
                        max_length=10,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "default_payment_days",
                    models.PositiveIntegerField(default=30, verbose_name="Prazo padrão (dias)"),
                ),
                (
                    "default_payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bank_transfer", "Transferência"),
                            ("pix", "PIX"),
                            ("boleto", "Boleto"),
                            ("check", "Cheque"),
                            ("cash", "Dinheiro"),
                        ],
                        default="",
                        max_length=20,
                        verbose_name="Forma de pagamento padrão",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(blank=True, default="", max_length=100, verbose_name="Banco"),
                ),
                (
                    "bank_agency",
                    models.CharField(blank=True, default="", max_length=20, verbose_name="Agência"),
                ),
                (
                    "bank_account",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, default="", verbose_name="Conta"
                    ),
                ),
                (
                    "pix_key",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, default="", verbose_name="Chave PIX"
                    ),
                ),
                (
                    "pix_key_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CPF", "CPF"),
                            ("CNPJ", "CNPJ"),
                            ("EMAIL", "E-mail"),
                            ("PHONE", "Telefone"),
                            ("RANDOM", "Aleatória"),
                        ],
                        default="",
                        max_length=10,
                        verbose_name="Tipo de chave PIX",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="", verbose_name="Observações")),
                (
                    "legacy_supplier_id",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        help_text="ID original em accounts_payable.Supplier — preenchido na migração",
                        null=True,
                    ),
                ),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_profile",
                        to="persons.person",
                        verbose_name="Pessoa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Fornecedor",
                "verbose_name_plural": "Perfis de Fornecedor",
            },
        ),
    ]
