# Generated by Django 5.0 — Sprint 14

import decimal
import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceivableDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "customer_id",
                    models.UUIDField(db_index=True, verbose_name="ID do cliente"),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=200, verbose_name="Nome do cliente"),
                ),
                (
                    "description",
                    models.CharField(max_length=300, verbose_name="Descricao"),
                ),
                (
                    "document_number",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="No Documento"
                    ),
                ),
                (
                    "document_date",
                    models.DateField(blank=True, null=True, verbose_name="Data do documento"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=18, verbose_name="Valor"
                    ),
                ),
                (
                    "amount_received",
                    models.DecimalField(
                        decimal_places=2,
                        default=decimal.Decimal("0.00"),
                        max_digits=18,
                        verbose_name="Valor recebido",
                    ),
                ),
                ("due_date", models.DateField(db_index=True, verbose_name="Vencimento")),
                ("competence_date", models.DateField(verbose_name="Competencia")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Em Aberto"),
                            ("partial", "Parcialmente Recebido"),
                            ("received", "Recebido"),
                            ("overdue", "Vencido"),
                            ("cancelled", "Cancelado"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("MAN", "Manual"),
                            ("OS", "Ordem de Servico"),
                            ("NFE", "NF-e Emitida"),
                            ("NFCE", "NFC-e Emitida"),
                            ("NFSE", "NFS-e Emitida"),
                        ],
                        default="MAN",
                        max_length=10,
                        verbose_name="Origem",
                    ),
                ),
                (
                    "service_order_id",
                    models.UUIDField(
                        blank=True, db_index=True, null=True, verbose_name="ID da OS"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Observacoes"),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Cancelado em"),
                ),
                (
                    "cancel_reason",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Motivo do cancelamento",
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_receivables",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cancelado por",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receivables",
                        to="accounting.costcenter",
                        verbose_name="Centro de Custo",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Titulo a Receber",
                "verbose_name_plural": "Titulos a Receber",
                "ordering": ["due_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReceivableReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "receipt_date",
                    models.DateField(verbose_name="Data do recebimento"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=18, verbose_name="Valor recebido"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("bank_transfer", "Transferencia Bancaria"),
                            ("pix", "PIX"),
                            ("boleto", "Boleto"),
                            ("check", "Cheque"),
                            ("cash", "Dinheiro"),
                            ("credit_card", "Cartao de Credito"),
                            ("debit_card", "Cartao de Debito"),
                        ],
                        default="pix",
                        max_length=20,
                        verbose_name="Forma de pagamento",
                    ),
                ),
                (
                    "bank_account",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Conta bancaria"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Observacoes"),
                ),
                (
                    "journal_entry_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="Lancamento contabil"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipts",
                        to="accounts_receivable.receivabledocument",
                        verbose_name="Titulo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recebimento",
                "verbose_name_plural": "Recebimentos",
                "ordering": ["-receipt_date"],
            },
        ),
        migrations.AddIndex(
            model_name="receivabledocument",
            index=models.Index(
                fields=["status", "due_date"],
                name="accounts_re_status_b61b6a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="receivabledocument",
            index=models.Index(
                fields=["customer_id", "status"],
                name="accounts_re_custome_27fec7_idx",
            ),
        ),
    ]
