# Generated by Django 5.2.12 on 2026-04-21 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_add_version_model'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='budgetversion',
            index=models.Index(fields=['status', 'valid_until'], name='bv_status_valid_idx'),
        ),
    ]
