# Generated by Django 5.0.10 on 2026-04-27 15:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0003_budget_color_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="vehicle_fuel_type",
            field=models.CharField(
                blank=True, default="", help_text="Combustível ex: Flex, Gasolina", max_length=30
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="vehicle_color",
            field=models.CharField(
                blank=True, default="", help_text="Cor do veículo", max_length=40
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="vehicle_year",
            field=models.IntegerField(blank=True, help_text="Ano modelo do veículo", null=True),
        ),
        migrations.AlterField(
            model_name="budgetversion",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="budgetversionitem",
            name="bucket",
            field=models.CharField(
                choices=[
                    ("IMPACTO", "Impacto"),
                    ("SEM_COBERTURA", "Sem Cobertura"),
                    ("SOB_ANALISE", "Sob Análise"),
                ],
                db_index=True,
                default="IMPACTO",
                max_length=20,
                verbose_name="Bucket",
            ),
        ),
        migrations.AlterField(
            model_name="budgetversionitem",
            name="description",
            field=models.CharField(max_length=300, verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="budgetversionitem",
            name="discount_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Percentual de desconto sobre o preço unitário.",
                max_digits=5,
                verbose_name="Desconto (%)",
            ),
        ),
        migrations.AlterField(
            model_name="budgetversionitem",
            name="external_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Código da peça/serviço no sistema da seguradora ou fornecedor.",
                max_length=60,
                verbose_name="Código Externo",
            ),
        ),
        migrations.AlterField(
            model_name="budgetversionitem",
            name="flag_abaixo_padrao",
            field=models.BooleanField(
                default=False,
                help_text="Item precificado abaixo da tabela de referência.",
                verbose_name="Abaixo do Padrão",
            ),
        ),
        migrations.AlterField(
            model_name="budgetversionitem",
            name="flag_acima_padrao",
            field=models.BooleanField(
                default=False,
                help_text="Item precificado acima da tabela de referência.",
                verbose_name="Acima do Padrão",
            ),
        ),
        migrations.AlterField(
            model_name="budgetversionitem",
            name="flag_codigo_diferente",
            field=models.BooleanField(
                default=False,
                help_text="Código do item difere do código da seguradora.",
                verbose_name="Código Diferente",
            ),
        ),
        migrations.AlterField(
            model_name="budgetversionitem",
            name="flag_inclusao_manual",
            field=models.BooleanField(
                default=False,
                help_text="Item incluído manualmente (não gerado pelo motor de orçamento).",
                verbose_name="Inclusão Manual",
            ),
        ),
        migrations.AlterField(
            model_name="budgetversionitem",
            name="flag_peca_da_conta",
            field=models.BooleanField(
                default=False,
                help_text="Peça cujo custo é responsabilidade da seguradora (da conta do sinistro).",
                verbose_name="Peça da Conta",
            ),
        ),
        migrations.AlterField(
            model_name="budgetversionitem",
            name="flag_servico_manual",
            field=models.BooleanField(
                default=False,
                help_text="Serviço inserido manualmente sem catálogo canônico.",
                verbose_name="Serviço Manual",
            ),
        ),
        migrations.AlterField(
            model_name="budgetversionitem",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="budgetversionitem",
            name="impact_area",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="ID da área de impacto do veículo (ex: capô, porta dianteira esquerda).",
                null=True,
                verbose_name="Área de Impacto",
            ),
        ),
        migrations.AlterField(
            model_name="budgetversionitem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("PART", "Peça"),
                    ("SERVICE", "Serviço"),
                    ("EXTERNAL_SERVICE", "Serviço Externo"),
                    ("FEE", "Taxa"),
                    ("DISCOUNT", "Desconto"),
                ],
                default="PART",
                max_length=20,
                verbose_name="Tipo de Item",
            ),
        ),
        migrations.AlterField(
            model_name="budgetversionitem",
            name="net_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Preço unitário após desconto × quantidade.",
                max_digits=14,
                verbose_name="Preço Líquido",
            ),
        ),
        migrations.AlterField(
            model_name="budgetversionitem",
            name="part_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GENUINA", "Genuína"),
                    ("ORIGINAL", "Original"),
                    ("OUTRAS_FONTES", "Outras Fontes"),
                    ("VERDE", "Verde (Reciclada)"),
                ],
                default="",
                help_text="Aplicável apenas quando item_type=PART.",
                max_length=20,
                verbose_name="Tipo de Peça",
            ),
        ),
        migrations.AlterField(
            model_name="budgetversionitem",
            name="payer_block",
            field=models.CharField(
                choices=[
                    ("SEGURADORA", "Seguradora"),
                    ("COMPLEMENTO_PARTICULAR", "Complemento Particular"),
                    ("FRANQUIA", "Franquia"),
                    ("PARTICULAR", "Particular"),
                ],
                db_index=True,
                default="PARTICULAR",
                max_length=30,
                verbose_name="Bloco Pagador",
            ),
        ),
        migrations.AlterField(
            model_name="budgetversionitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("1"), max_digits=10, verbose_name="Quantidade"
            ),
        ),
        migrations.AlterField(
            model_name="budgetversionitem",
            name="sort_order",
            field=models.IntegerField(default=0, verbose_name="Ordem de Exibição"),
        ),
        migrations.AlterField(
            model_name="budgetversionitem",
            name="supplier",
            field=models.CharField(
                choices=[("OFICINA", "Oficina"), ("SEGURADORA", "Seguradora")],
                default="OFICINA",
                max_length=20,
                verbose_name="Fornecedor",
            ),
        ),
        migrations.AlterField(
            model_name="budgetversionitem",
            name="unit_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Custo de aquisição da peça/insumo. Pode ser null para serviços.",
                max_digits=14,
                null=True,
                verbose_name="Custo Unitário",
            ),
        ),
        migrations.AlterField(
            model_name="budgetversionitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=14, verbose_name="Preço Unitário"
            ),
        ),
    ]
