# Generated by Django 5.0.10 on 2026-04-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0004_add_vehicle_fuel_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="vehicle_make_logo",
            field=models.URLField(
                blank=True, default="", help_text="URL da logo da montadora", max_length=500
            ),
        ),
    ]
