# Generated by Django 5.0.10 on 2026-04-06 19:11

import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('department', models.CharField(choices=[('reception', 'Recepção'), ('bodywork', 'Funilaria'), ('painting', 'Pintura'), ('mechanical', 'Mecânica'), ('aesthetics', 'Estética'), ('polishing', 'Polimento'), ('washing', 'Lavagem'), ('inventory', 'Almoxarifado'), ('financial', 'Financeiro'), ('administrative', 'Administrativo'), ('management', 'Gerência'), ('direction', 'Diretoria')], db_index=True, max_length=30, verbose_name='Setor')),
                ('position', models.CharField(choices=[('receptionist', 'Recepcionista'), ('consultant', 'Consultor de Serviços'), ('bodyworker', 'Funileiro'), ('painter', 'Pintor'), ('mechanic', 'Mecânico'), ('polisher', 'Polidor'), ('washer', 'Lavador'), ('storekeeper', 'Almoxarife'), ('manager', 'Gerente'), ('financial', 'Financeiro'), ('administrative', 'Administrativo'), ('director', 'Diretor')], db_index=True, max_length=30, verbose_name='Cargo')),
                ('registration_number', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Matrícula')),
                ('contract_type', models.CharField(choices=[('clt', 'CLT'), ('pj', 'PJ / Prestador'), ('intern', 'Estagiário'), ('temp', 'Temporário'), ('apprentice', 'Jovem Aprendiz')], default='clt', max_length=15, verbose_name='Tipo de contrato')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('on_leave', 'Afastado'), ('vacation', 'Férias'), ('terminated', 'Desligado')], db_index=True, default='active', max_length=15, verbose_name='Status')),
                ('hire_date', models.DateField(verbose_name='Data de admissão')),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name='Data de desligamento')),
                ('cpf', encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', verbose_name='CPF')),
                ('cpf_hash', models.CharField(blank=True, db_index=True, default='', help_text='SHA-256 do CPF — para lookup sem expor dado bruto', max_length=64)),
                ('rg', encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', verbose_name='RG')),
                ('rg_issuer', models.CharField(blank=True, default='', max_length=20, verbose_name='Órgão emissor RG')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('mother_name', encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', verbose_name='Nome da mãe')),
                ('father_name', encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', verbose_name='Nome do pai')),
                ('marital_status', models.CharField(blank=True, default='', max_length=20, verbose_name='Estado civil')),
                ('education_level', models.CharField(blank=True, default='', max_length=30, verbose_name='Escolaridade')),
                ('nationality', models.CharField(default='Brasileira', max_length=50, verbose_name='Nacionalidade')),
                ('personal_email', encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', verbose_name='E-mail pessoal')),
                ('personal_phone', encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', verbose_name='Telefone pessoal')),
                ('emergency_contact_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Contato emergência — nome')),
                ('emergency_contact_phone', encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', verbose_name='Contato emergência — telefone')),
                ('address_street', models.CharField(blank=True, default='', max_length=300, verbose_name='Logradouro')),
                ('address_number', models.CharField(blank=True, default='', max_length=20, verbose_name='Número')),
                ('address_complement', models.CharField(blank=True, default='', max_length=100, verbose_name='Complemento')),
                ('address_neighborhood', models.CharField(blank=True, default='', max_length=100, verbose_name='Bairro')),
                ('address_city', models.CharField(default='Manaus', max_length=100, verbose_name='Cidade')),
                ('address_state', models.CharField(default='AM', max_length=2, verbose_name='Estado')),
                ('address_zip', models.CharField(blank=True, default='', max_length=9, verbose_name='CEP')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Salário base')),
                ('pix_key', encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', verbose_name='Chave PIX')),
                ('pix_key_type', models.CharField(blank=True, default='', help_text='cpf | email | phone | random | cnpj', max_length=10, verbose_name='Tipo de chave PIX')),
                ('weekly_hours', models.DecimalField(decimal_places=1, default=44.0, max_digits=4, verbose_name='Carga horária semanal')),
                ('work_schedule', models.CharField(default='6x1', help_text='6x1 (padrão DS Car), 5x2, 12x36, custom', max_length=20, verbose_name='Escala')),
                ('legacy_databox_id', models.IntegerField(blank=True, db_index=True, help_text='ID no Box Empresa para rastreabilidade de migração', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='Conta de acesso ao sistema', on_delete=django.db.models.deletion.PROTECT, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'ordering': ['user__name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('document_type', models.CharField(choices=[('cnh', 'CNH'), ('rg', 'RG'), ('birth_cert', 'Certidão de Nascimento'), ('marriage_cert', 'Certidão de Casamento'), ('work_card', 'Carteira de Trabalho (CTPS)'), ('voter_id', 'Título de Eleitor'), ('military_cert', 'Certificado de Reservista'), ('school_cert', 'Certificado Escolar'), ('medical_exam', 'Atestado / Exame Médico'), ('contract', 'Contrato de Trabalho'), ('other', 'Outro')], db_index=True, max_length=20, verbose_name='Tipo de documento')),
                ('document_number', encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', verbose_name='Número do documento')),
                ('file_key', models.CharField(help_text='Chave do arquivo no R2/S3 — NUNCA deletar fisicamente', max_length=500, verbose_name='Chave no storage')),
                ('file_name', models.CharField(max_length=255, verbose_name='Nome do arquivo')),
                ('file_size', models.PositiveIntegerField(help_text='Tamanho em bytes', verbose_name='Tamanho')),
                ('mime_type', models.CharField(default='application/pdf', max_length=100, verbose_name='Tipo MIME')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Data de emissão')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Data de validade')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Documento do Colaborador',
                'verbose_name_plural': 'Documentos dos Colaboradores',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalaryHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('previous_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário anterior')),
                ('new_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Novo salário')),
                ('effective_date', models.DateField(db_index=True, verbose_name='Data de vigência')),
                ('reason', models.CharField(blank=True, default='', help_text='Promoção, dissídio, mérito, etc.', max_length=300, verbose_name='Motivo')),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_authorizations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_history', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Histórico de Salário',
                'verbose_name_plural': 'Históricos de Salário',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department', 'status'], name='hr_employee_departm_406000_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['status', 'hire_date'], name='hr_employee_status_7478c3_idx'),
        ),
        migrations.AddIndex(
            model_name='employeedocument',
            index=models.Index(fields=['employee', 'document_type'], name='hr_employee_employe_a9f87b_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryhistory',
            index=models.Index(fields=['employee', 'effective_date'], name='hr_salaryhi_employe_15ca1e_idx'),
        ),
    ]
