# Generated by Django 5.0.10 on 2026-04-09 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0003_sprint_11"),
        ("persons", "0004_person_job_title_department_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="person",
            field=models.ForeignKey(
                blank=True,
                help_text="Pessoa vinculada ao colaborador (criada automaticamente na admissão).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employee_profile",
                to="persons.person",
            ),
        ),
    ]
