# Generated by Django 5.0.10 on 2026-04-25 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0004_alter_employee_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="bank_account",
            field=models.CharField(blank=True, default="", max_length=30, verbose_name="Conta"),
        ),
        migrations.AddField(
            model_name="employee",
            name="bank_account_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="corrente ou poupanca",
                max_length=15,
                verbose_name="Tipo de conta",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="bank_agency",
            field=models.CharField(blank=True, default="", max_length=20, verbose_name="Agência"),
        ),
        migrations.AddField(
            model_name="employee",
            name="bank_name",
            field=models.CharField(blank=True, default="", max_length=100, verbose_name="Banco"),
        ),
        migrations.AddField(
            model_name="employee",
            name="emergency_contact_relationship",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Ex: Esposa, Pai, Filho",
                max_length=50,
                verbose_name="Contato emergência — parentesco",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="emergency_contact_phone",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="Contato emergência — telefone"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="father_name",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Nome do pai"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="mother_name",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Nome da mãe"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="rg",
            field=models.CharField(blank=True, default="", max_length=20, verbose_name="RG"),
        ),
    ]
