# Generated by Django 5.0.10 on 2026-05-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0006_reencrypt_emergency_contact_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="dependents_count",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Dependentes para dedução de IRRF (R$ 189,59/dependente).",
                verbose_name="Nº de dependentes",
            ),
        ),
    ]
