# Generated by Django 5.0.10 on 2026-05-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0007_add_dependents_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="signature_image",
            field=models.ImageField(
                blank=True,
                help_text="Assinatura digital do funcionário (PNG transparente).",
                null=True,
                upload_to="employees/signatures/",
            ),
        ),
    ]
