# Generated by Django 5.0.10 on 2026-05-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0008_add_employee_signature_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="extra_permissions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista de permissões granulares além da role base. Ex: ['can_close_os', 'can_approve_purchase']",
                verbose_name="Permissões extras",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="role",
            field=models.CharField(
                choices=[
                    ("STOREKEEPER", "Almoxarife"),
                    ("CONSULTANT", "Consultor"),
                    ("MANAGER", "Gerente"),
                    ("ADMIN", "Administrador"),
                    ("OWNER", "Proprietário"),
                ],
                db_index=True,
                default="CONSULTANT",
                help_text="Nível de acesso do colaborador no sistema.",
                max_length=20,
                verbose_name="Role RBAC",
            ),
        ),
    ]
