# Generated by Django 5.0.10 on 2026-05-08 15:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0009_add_role_and_extra_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vacation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("acquisition_start", models.DateField(verbose_name="Início período aquisitivo")),
                ("acquisition_end", models.DateField(verbose_name="Fim período aquisitivo")),
                ("start_date", models.DateField(verbose_name="Início das férias")),
                ("end_date", models.DateField(verbose_name="Fim das férias")),
                (
                    "days_taken",
                    models.PositiveSmallIntegerField(
                        help_text="Dias de gozo (20 a 30)", verbose_name="Dias de férias"
                    ),
                ),
                (
                    "days_sold",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Dias vendidos (0 a 10)",
                        verbose_name="Abono pecuniário",
                    ),
                ),
                (
                    "base_salary_snapshot",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Salário base na data"
                    ),
                ),
                (
                    "vacation_pay",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Valor das férias"
                    ),
                ),
                (
                    "one_third_pay",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="1/3 constitucional",
                    ),
                ),
                (
                    "sold_pay",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Valor abono pecuniário",
                    ),
                ),
                (
                    "total_pay",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Total a pagar"
                    ),
                ),
                (
                    "deductions",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Descontos (INSS+IRRF)",
                    ),
                ),
                (
                    "net_pay",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Líquido férias"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Agendada"),
                            ("active", "Em gozo"),
                            ("completed", "Concluída"),
                            ("cancelled", "Cancelada"),
                        ],
                        db_index=True,
                        default="scheduled",
                        max_length=12,
                    ),
                ),
            ],
            options={
                "verbose_name": "Férias",
                "verbose_name_plural": "Férias",
                "ordering": ["-start_date"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="payslip",
            name="unique_payslip_per_month",
        ),
        migrations.AddField(
            model_name="payslip",
            name="payslip_type",
            field=models.CharField(
                choices=[
                    ("regular", "Folha mensal"),
                    ("thirteenth_first", "13º — 1ª parcela"),
                    ("thirteenth_second", "13º — 2ª parcela"),
                    ("thirteenth_full", "13º — Integral"),
                ],
                db_index=True,
                default="regular",
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
        migrations.AddConstraint(
            model_name="payslip",
            constraint=models.UniqueConstraint(
                fields=("employee", "reference_month", "payslip_type"),
                name="unique_payslip_per_month_type",
            ),
        ),
        migrations.AddField(
            model_name="vacation",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vacation",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vacations",
                to="hr.employee",
            ),
        ),
        migrations.AddIndex(
            model_name="vacation",
            index=models.Index(
                fields=["employee", "acquisition_start"], name="hr_vacation_employe_ebd9fc_idx"
            ),
        ),
    ]
